### ISSUE TITLE
Add new coin RTM

### ISSUE THREAD

**Issue by riabikov** [coinfoundry/miningcore#1001]
Hi. I tried to add a new coin (Raptoreum) but it failed. I ask for help.
What I've done?

1. Took the algorithm from here, files gr.h and gr.c — https://github.com/npq7721/gr_hash
1.1. Added all dependencies .h files mentioned in gr.c (/sph/.. /cryptonote/..) — https://github.com/npq7721/gr_hash
2. Add /miningcore/src/Native/libmultihash\gr.h
2.1 Edit /miningcore/src/Native/libmultihash\gr.h
`void gr_hash(const char* input, char* output, uint32_t len);`
3. Add /miningcore/src/Native/libmultihash\gr.c
4. Add /miningcore/src/Miningcore/Crypto/Hashing/Algorithms/Ghostrider.cs
```
using System;
using Miningcore.Contracts;
using Miningcore.Native;

namespace Miningcore.Crypto.Hashing.Algorithms
{
    public unsafe class Ghostrider : IHashAlgorithm
    {
        public void Digest(ReadOnlySpan<byte> data, Span<byte> result, params object[] extra)
        {
            Contract.Requires<ArgumentException>(result.Length >= 32, $"{nameof(result)} must be greater or equal 32 bytes");

            fixed (byte* input = data)
            {
                fixed (byte* output = result)
                {
                    LibMultihash.ghostrider(input, output, (uint) data.Length);
                }
            }
        }
    }
}
```
5. Edit /miningcore/src/Native/libmultihash/libmultihash.vcxproj.filters
```
<ClInclude Include=\"gr.h\">
  <Filter>Header Files</Filter>
</ClInclude>
<ClCompile Include=\"gr.c\">
  <Filter>Source Files</Filter>
</ClCompile>
```
6. Edit /miningcore/src/Native/libmultihash/libmultihash.vcxproj
```
<ClInclude Include="gr.h" />
<ClCompile Include="gr.c" />
```

7. Edit /miningcore/src/Native/libmultihash/exports.cpp
```
extern "C" MODULE_API void ghostrider_export(const char* input, char* output, uint32_t input_len)
{
	gr_hash(input, output, input_len);
}
```
8. Edit /miningcore/src/Native/libmultihash/Makefile
```
Lyra2.o Lyra2RE.o Sponge.o geek.o gr.o  \
```
9. Edit /miningcore/src/Miningcore/Native/LibMultihash.cs
```
[DllImport("libmultihash", EntryPoint = "ghostrider_export", CallingConvention = CallingConvention.Cdecl)]
public static extern void ghostrider(byte* input, void* output, uint inputLength);
```
10. Edit /miningcore/src/Miningcore/coins.json
```
"raptoreum": {
     "name": "Raptoreum",
     "symbol": "RTM",
     "family": "bitcoin",
     "coinbaseHasher": {
         "hash": "sha256d"
     },
     "headerHasher": {
         "hash": "ghostrider"
     },
     "blockHasher": {
         "hash": "reverse",
         "args": [ { "hash": "ghostrider" } ]
     },
     "hasFounderFee": true,
     "hasMasterNodes": true,
     "shareMultiplier": 65536,
     "explorerBlockLink": "https://explorer.raptoreum.com/block-height/$height$",
     "explorerTxLink": "https://explorer.raptoreum.com/tx/{0}",
     "explorerAccountLink": "https://explorer.raptoreum.com/address/{0}"
},
```
I compiled the project for both Windows and Linux without any problems, but when I run I get an error:
```
[2021-11-22 23:31:29.5038] [I] [Core] Version 62.0.0.0-master [5614c274189241c6aa9d5682211c682680bcb141] 
[2021-11-22 23:31:29.5520] [I] [Core] Runtime .NET 6.0.0-rtm.21522.10 on Linux 4.15.0-162-generic #170-Ubuntu SMP Mon Oct 18 11:38:05 UTC 2021 [X64] 
[2021-11-22 23:31:29.5761] [I] [Core] Prometheus Metrics 0.0.0.0:4000/metrics 
[2021-11-22 23:31:29.5761] [I] [Core] WebSocket notifications streaming 0.0.0.0:4000/notifications 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Miningcore.Program.<>c.<ConfigurePostgres>b__29_0(Type t) in /home/user/miningcore/src/Miningcore/Program.cs:line 746
   at Autofac.Features.Scanning.ScanningRegistrationExtensions.<>c__DisplayClass4_1`2.<CanBeRegistered>b__1(Func`2 p)
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
   at Autofac.Features.Scanning.ScanningRegistrationExtensions.<>c__DisplayClass4_0`2.<CanBeRegistered>b__0(Type t)
   at System.Linq.Utilities.<>c__DisplayClass1_0`1.<CombinePredicates>b__0(TSource x)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Autofac.Features.Scanning.ScanningRegistrationExtensions.ScanTypesTemplate[TActivatorData,TScanStyle,TRegistrationBuilderStyle](IEnumerable`1 types, IComponentRegistryBuilder cr, IRegistrationBuilder`3 rb, Func`2 scannedConstructorFunc, Action`2 register)
   at Autofac.Features.Scanning.ScanningRegistrationExtensions.ScanTypes(IEnumerable`1 types, IComponentRegistryBuilder cr, IRegistrationBuilder`3 rb)
   at Autofac.Features.Scanning.ScanningRegistrationExtensions.ScanAssemblies(IEnumerable`1 assemblies, IComponentRegistryBuilder cr, IRegistrationBuilder`3 rb)
   at Autofac.Features.Scanning.ScanningRegistrationExtensions.<>c__DisplayClass11_0.<RegisterAssemblyTypes>b__0(IComponentRegistryBuilder cr)
   at Autofac.ContainerBuilder.Build(IComponentRegistryBuilder componentRegistry, Boolean excludeDefaultModules)
   at Autofac.ContainerBuilder.Build(ContainerBuildOptions options)
   at Autofac.Extensions.DependencyInjection.AutofacServiceProviderFactory.CreateServiceProvider(ContainerBuilder containerBuilder)
   at Microsoft.Extensions.Hosting.Internal.ServiceFactoryAdapter`1.CreateServiceProvider(Object containerBuilder)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Miningcore.Program.Main(String[] args) in /home/user/miningcore/src/Miningcore/Program.cs:line 203
Cluster cannot start. Good Bye!
```
The wallet daemon is running, the RPC is configured, the Postgres is installed and configured.

**Comment by oliverw** [comment]
Hmm. Does changing line 746 of Program.cs to this make a difference?

`t?.Namespace?.StartsWith(typeof(ShareRepository).Namespace) == true)`

**Comment by riabikov** [comment]
Yes, it's working! Thx!

**Comment by oliverw** [comment]
Reopening for association with a commit.

**Comment by BitWizJason** [comment]
@riabikov  Would you mind doing a pull request and share your changes please? I am also interested in Raptoreum.

**Comment by riabikov** [comment]
> @riabikov Would you mind doing a pull request and share your changes please? I am also interested in Raptoreum.

I have nothing to publish yet. I managed to start the pool, but after two minutes it crashes with an error:
```
dotnet: symbol lookup error: /home/user/miningcore/build/libmultihash.so: undefined symbol: _Z7gr_hashPKcPcj
```
