### ISSUE TITLE
ergo - pool will not start

### ISSUE THREAD

**Issue by synergy-promotions** [coinfoundry/miningcore#1006]
Hi team,

Getting this error with ERGO node - I'm suspecting a missing config setting but cannot locate any examples of ergo anywhere.

--- End of stack trace from previous location ---
   at Miningcore.Program.ExecuteAsync(CancellationToken ct) in /opt/miningcore/miningcore/src/Miningcore/Program.cs:line 333
   at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
Miningcore.Mining.PoolStartupAbortException: Daemon reports: An error occurred while sending the request.

the multithread task is throwing an exception.
            await Task.WhenAll(clusterConfig.Pools
                .Where(config => config.Enabled)
                .Select(config=> RunPool(config, coinTemplates, ct)));
       
this RunPool function appears to want a cluster config - but I am just using the simple createdb version...

Should I be running the advanced script? or is it just a missing block in config.json?

**** attempted [config.json] *****
{
    "logging": {
        "level": "debug",
        "enableConsoleLog": true,
        "enableConsoleColors": true,
        "logFile": "pool.log",
        "logBaseDirectory": "/opt/miningcore/logs",
        "perPoolLogFile": false
    },
    "banning": {
        "manager": "integrated",
        "banOnJunkReceive": true,
        "banOnInvalidShares": false
    },
    "api": {
        "enabled": true,
        "listenAddress": "127.0.0.1",
        "port": 4000,
        "adminPort": 4001
    },
    "notifications": {
        "enabled": false,
        "email": {
            "host": "xxxxx",
            "port": xxx,
            "user": "xxxx",
            "password": "xxxxxxx",
            "fromAddress": "info@yourpool.org",
            "fromName": "support"
        },
        "admin": {
            "enabled": false,
            "emailAddress": "xxxxxxxxxx",
            "notifyBlockFound": true
        }
    },
    "persistence": {
        "postgres": {
            "host": "127.0.0.1",
            "port": 5432,
            "user": "xxxxxxxxxx",
            "password": "xxxxxxxxxx",
            "database": "miningcore"
        }
    },
    "paymentProcessing": {
        "enabled": true,
        "interval": 600,
        "shareRecoveryFile": "recovered-shares.txt"
    },
    "pools": [{
      "id": "ergo",
      "enabled": true,
      "coin": "ergo",
      "address": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      "rewardRecipients": [
        {
          "address": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
          "percentage": 1
        }
      ],
      "blockRefreshInterval": 500,
      "clientConnectionTimeout": 600,
      "banning": {
        "enabled": true,
        "time": 600,
        "invalidPercent": 50,
        "checkThreshold": 50
      },
      "ports": {
        "3032": {
          "listenAddress": "0.0.0.0",
          "difficulty": 7500,
          "name": "CPU Mining",
          "varDiff": {
            "minDiff": 1000,
            "maxDiff": null,
            "targetTime": 15,
            "retargetTime": 90,
            "variancePercent": 30
          }
        },
        "3033": {
          "listenAddress": "0.0.0.0",
          "difficulty": 25000,
          "name": "GPU Mining",
          "varDiff": {
            "minDiff": 10000,
            "maxDiff": null,
            "targetTime": 15,
            "retargetTime": 90,
            "variancePercent": 30
          }
        },
        "3034": {
          "listenAddress": "0.0.0.0",
          "difficulty": 200000,
          "name": "High-End Multi GPU Mining",
          "varDiff": {
            "minDiff": 200000,
            "maxDiff": null,
            "targetTime": 15,
            "retargetTime": 120,
            "variancePercent": 30
          }
        }
      },
      "daemons": [
        {
          "host": "127.0.0.1",
          "port": 9030,
          "apiKey": "xxxxxxxxxxxxxxxxxxxxxxxxxx"
       },
      ],
      "paymentProcessing": {
        "enabled": true,
        "minimumPayment": 0.25,
        "minimumPaymentToPaymentId": 1.0,
        "payoutScheme": "PPLNS",
        "payoutSchemeConfig": {
          "factor": 2.0
        }
      }
    }]
}

**Comment by synergy-promotions** [comment]
should have mentioned it errors straight after this checkpoint in the log (debug log).
100% sure this is just something to do with config.json.

[2021-11-24 16:42:04.7354] [I] [StatsRecorder] Stats GC complete
[2021-11-24 16:42:19.2387] [E] [ergo] Daemon reports: An error occurred while sending the request.
[2021-11-24 16:42:19.2482] [E] [Host] BackgroundService failed Miningcore.Mining.PoolStartupAbortException: Daemon reports: An error occurred while sending the request.
   at Miningcore.Util.LogUtil.ThrowLogPoolStartupException(ILogger logger, String msg, String category) in /opt/miningcore/miningcore/src/Miningcore/Util/LogUtil.cs:line 26
   at Miningcore.Blockchain.Ergo.ErgoJobManager.<>c__DisplayClass35_0.<AreDaemonsHealthyAsync>b__1(Exception ex) in /opt/miningcore/miningcore/src/Miningcore/Blockchain/Ergo/ErgoJ>
   at Miningcore.Util.ActionUtils.Guard[T](Func`1 func, Action`1 errorHandler) in /opt/miningcore/miningcore/src/Miningcore/Util/ActionUtils.cs:line 43
   at Miningcore.Blockchain.Ergo.ErgoJobManager.AreDaemonsHealthyAsync(CancellationToken ct) in /opt/miningcore/miningcore/src/Miningcore/Blockchain/Ergo/ErgoJobManager.cs:line 437
   at Miningcore.Blockchain.JobManagerBase`1.StartDaemonAsync(CancellationToken ct) in /opt/miningcore/miningcore/src/Miningcore/Blockchain/JobManagerBase.cs:line 45
   at Miningcore.Blockchain.JobManagerBase`1.StartAsync(CancellationToken ct) in /opt/miningcore/miningcore/src/Miningcore/Blockchain/JobManagerBase.cs:line 111
   at Miningcore.Blockchain.Ergo.ErgoPool.SetupJobManager(CancellationToken ct) in /opt/miningcore/miningcore/src/Miningcore/Blockchain/Ergo/ErgoPool.cs:line 295
   at Miningcore.Mining.PoolBase.RunAsync(CancellationToken ct) in /opt/miningcore/miningcore/src/Miningcore/Mining/PoolBase.cs:line 379
   at Miningcore.Program.<>c__DisplayClass15_0.<<RunPool>b__0>d.MoveNext() in /opt/miningcore/miningcore/src/Miningcore/Program.cs:line 358

**Comment by synergy-promotions** [comment]
any help will be greatly appreciated - will keep playing in the meantime. Many thanks. Dan

**Comment by synergy-promotions** [comment]
sorry - moving to discussion board.
