### ISSUE TITLE
Win10 dagdir in config.json not working

### ISSUE THREAD

**Issue by Raspimann** [coinfoundry/miningcore#1022]
machine windows 10 / i7-8 core with 32 GB ram + 32 virtuell memory + 2tb ssd (over 500gb free)

when i starten "miningcore -c config.json"

with
        "dagDir": "C:\Users\me\AppData\Local\Ethash",

this error shows:

Using configuration file config.json
Error: Bad JSON escape sequence: \U. Path 'pools[0].dagDir', line 102, position 23.

....

When i started without any ("dagDir": "") the dagfile was generate new in the geth dag directory ... but then with many error messages

[2021-12-03 12:31:03.1784] [I] [Core] Version 63.0.1.0-master [0075cb7666a7f9a6c5b9e48fef5adb2b09df869a]
[2021-12-03 12:31:03.1893] [I] [Core] Runtime .NET 6.0.0-rtm.21522.10 on Microsoft Windows 10.0.19043 [X64]
[2021-12-03 12:31:03.1974] [I] [Core] Prometheus Metrics 0.0.0.0:4000/metrics
[2021-12-03 12:31:03.1974] [I] [Core] WebSocket notifications streaming 0.0.0.0:4000/notifications
[2021-12-03 12:31:03.5831] [I] [XmlKeyManager] User profile is available. Using 'C:\Users\me\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
[2021-12-03 12:31:03.6065] [I] [ShareRecorder] Online
[2021-12-03 12:31:03.6354] [I] [PayoutManager] Online
[2021-12-03 12:31:03.6378] [I] [StatsRecorder] Online
[2021-12-03 12:31:03.7344] [I] [Core] 53 coins loaded from C:\Users\me\miningcore\build\coins.json
[2021-12-03 12:31:03.7492] [I] [eth1] Starting Pool ...
[2021-12-03 12:31:03.7492] [I] [eth1] ExtraNonceProvider using 4 bits for instance id, 12 bits for 4095 values, instance id = 0x5
[2021-12-03 12:31:03.7492] [I] [Core] API Access to /api/admin restricted to 127.0.0.1,::1,::ffff:127.0.0.1
[2021-12-03 12:31:03.7492] [I] [Core] API Access to /metrics restricted to 127.0.0.1,::1,::ffff:127.0.0.1
[2021-12-03 12:31:03.7492] [I] [eth1] Starting Job Manager ...
[2021-12-03 12:31:03.8045] [I] [Lifetime] Now listening on: http://0.0.0.0:4000
[2021-12-03 12:31:03.8045] [I] [Lifetime] Application started. Press Ctrl+C to shut down.
[2021-12-03 12:31:03.8045] [I] [Lifetime] Hosting environment: Production
[2021-12-03 12:31:03.8045] [I] [Lifetime] Content root path: C:\Users\me\miningcore\build\
[2021-12-03 12:31:03.8455] [I] [eth1] All daemons online
[2021-12-03 12:31:03.8520] [I] [eth1] All daemons synched with blockchain
[2021-12-03 12:31:03.9715] [I] [eth1] Loading current DAG ...
[2021-12-03 12:31:03.9715] [I] [eth1] No pre-generated DAG available, creating new for epoch 457
[2021-12-03 12:31:03.9768] [I] [eth1] Generating DAG for epoch 457
[2021-12-03 12:31:18.6754] [I] [StatsRecorder] Performing Stats GC
[2021-12-03 12:31:19.0213] [I] [StatsRecorder] Stats GC complete
[2021-12-03 12:32:12.2221] [E] [eth1] System.OutOfMemoryException: ethash_full_new IO or memory error
   at Miningcore.Crypto.Hashing.Ethash.Dag.<>c__DisplayClass14_0.<GenerateAsync>b__0() in C:\Users\me\Miningcore\miningcore\src\Miningcore\Crypto\Hashing\Ethash\Dag.cs:line 99
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__271_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Miningcore.Crypto.Hashing.Ethash.Dag.GenerateAsync(String dagDir, ILogger logger, CancellationToken ct) in C:\Users\me\Miningcore\miningcore\src\Miningcore\Crypto\Hashing\Ethash\Dag.cs:line 70

and so on

**Comment by oliverw** [comment]
Try using double backslashes as for the path: c:\\

**Comment by Raspimann** [comment]
ok the dagdir problem is solved ...

the config.json:
"dagDir": "C:\\Users\\me\\AppData\\Local\\Ethash",

but the next bug is ... i make a new issue ...

**Comment by oliverw** [comment]
>  but the next bug is ... i make a new issue ...

This was not a bug.
