### ISSUE TITLE
VarDiff with low retargetTime throw System.NullReferenceException

### ISSUE THREAD

**Issue by shtse8** [coinfoundry/miningcore#12]
Updating VarDiff if there is no shares submitted will throw Exception. I suggest we should consider updating diff at least one share even with low retargetTime and high start Diff.

```shell
[2017-09-24 13:47:00.4122] [E] [dash] Error handling request: mining.submit System.NullReferenceException: Object reference not set to an instance of an object.
   at MiningCore.VarDiff.VarDiffManager.Update(VarDiffContext ctx, Double difficulty, Double networkDifficulty) in /root/miningcore/src/MiningCore/VarDiff/VarDiffManager.cs:line 64
   at MiningCore.Mining.PoolBase`1.UpdateVarDiff(StratumClient`1 client, Double networkDifficulty) in /root/miningcore/src/MiningCore/Mining/PoolBase.cs:line 187
   at MiningCore.Blockchain.Bitcoin.BitcoinPoolBase`2.<OnSubmitAsync>d__6.MoveNext() in /root/miningcore/src/MiningCore/Blockchain/Bitcoin/BitcoinPoolBase.cs:line 148
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Bitcoin.BitcoinPoolBase`2.<OnRequestAsync>d__10.MoveNext() in /root/miningcore/src/MiningCore/Blockchain/Bitcoin/BitcoinPoolBase.cs:line 281
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Stratum.StratumServer`1.<>c__DisplayClass11_0.<<OnClientConnected>b__2>d.MoveNext() in /root/miningcore/src/MiningCore/Stratum/StratumServer.cs:line 160    at MiningCore.VarDiff.VarDiffManager.Update(VarDiffContext ctx, Double difficulty, Double networkDifficulty) in /root/miningcore/src/MiningCore/VarDiff/VarDiffManager.cs:line 64
   at MiningCore.Mining.PoolBase`1.UpdateVarDiff(StratumClient`1 client, Double networkDifficulty) in /root/miningcore/src/MiningCore/Mining/PoolBase.cs:line 187
   at MiningCore.Blockchain.Bitcoin.BitcoinPoolBase`2.<OnSubmitAsync>d__6.MoveNext() in /root/miningcore/src/MiningCore/Blockchain/Bitcoin/BitcoinPoolBase.cs:line 148
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Bitcoin.BitcoinPoolBase`2.<OnRequestAsync>d__10.MoveNext() in /root/miningcore/src/MiningCore/Blockchain/Bitcoin/BitcoinPoolBase.cs:line 281
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Stratum.StratumServer`1.<>c__DisplayClass11_0.<<OnClientConnected>b__2>d.MoveNext() in /root/miningcore/src/MiningCore/Stratum/StratumServer.cs:line 160
```

**Comment by oliverw** [comment]
If you want to fix that one along with the other vardiff related bug I can assign it to you.

**Comment by shtse8** [comment]
Yes, please assign it to me. Thanks.
I think the out-of-band vardiff updates is a good decision. But I would prefer to do it when idle checking.
somethings like: 60s(retargetTime) no shares submitted. Update VarDiff. add this 60s to the calculation for average Adjust the diff. wait for new share. 

But I would suggest short `retargetTime` like 5s for pool farm.
