### ISSUE TITLE
Running MiningCore on localhost, port isn't open

### ISSUE THREAD

**Issue by SergeySypalo** [coinfoundry/miningcore#122]
Hi there, can't get MiningCore to work,
Compiled using Visual Studio 2017 Community (15.5)
Installed and configured Postgres
Specified valid miningcore user password in the config file
When run an engine using following command:
`dotnet MiningCore.dll -c config.json`
I'm not able to connect miner to port configured in config file, also when tried to telnet:
`telnet` localhost 3092
Got connection refused
In the CLI I see that messages:

```
[2017-12-17 21:40:46.0922] [I] [ShareRecorder] Online
[2017-12-17 21:40:46.1225] [I] [ApiServer] Launching ...
[2017-12-17 21:40:46.2346] [I] [ApiServer] Online @ 127.0.0.1:4000
[2017-12-17 21:40:46.2346] [I] [PayoutManager] Online
[2017-12-17 21:40:46.2488] [I] [PayoutManager] Processing payments for pool zec1
[2017-12-17 21:40:46.3411] [I] [zec1] [Pool] Launching ...
[2017-12-17 21:40:46.3725] [I] [zec1] [Bitcoin Job Manager] Launching ...
[2017-12-17 21:40:46.8625] [I] [PayoutManager] No updated blocks for zec1
[2017-12-17 21:40:46.8793] [I] [PayoutManager] No balances over configured minimum payout for pool zec1
[2017-12-17 21:40:47.4549] [I] [zec1] [Bitcoin Job Manager] Waiting for daemons to come online ...
[2017-12-17 21:40:58.4718] [I] [zec1] [Bitcoin Job Manager] Waiting for daemons to come online ...
```

**Comment by calvintam236** [comment]
`Waiting for daemons to come online ..` suggests it cannot connect to coin daemon. Make sure you have it running.

**Comment by SergeySypalo** [comment]
How to run coin daemon? I guessed it's running as part of MiningCore.

**Comment by pfeiflelukas** [comment]
@SergeySypalo Each coin you use needs to have a daemon and in some cases a rpc-wallet

**Comment by Konstantin35** [comment]
Покажи файл конфигурации

**Comment by SergeySypalo** [comment]
```
{
    "logging": {
        "level": "info",
        "enableConsoleLog": true,
        "enableConsoleColors": true,
        "logFile": "",
        "logBaseDirectory": "",
        "perPoolLogFile": false
    },
    "banning": {
        "manager": "integrated",
        "banOnJunkReceive": true,
        "banOnInvalidShares": false
    },
    "notifications": {
        "enabled": false,
        "email": {
            "host": "smtp.example.com",
            "port": 587,
            "user": "user",
            "password": "password",
            "fromAddress": "info@yourpool.org",
            "fromName": "support"
        },
        "admin": {
            "enabled": false,
            "emailAddress": "user@example.com",
            "notifyBlockFound": true
        }
    },
    "persistence": {
        "postgres": {
            "host": "127.0.0.1",
            "port": 5432,
            "user": "miningcore",
            "password": "AiZ1d5bFm3usfB2NB38E",
            "database": "miningcore"
        }
    },
    "equihashMaxThreads": 4,
    "paymentProcessing": {
        "enabled": true,
        "interval": 600,
        "shareRecoveryFile": "recovered-shares.txt"
    },
    "pools": [{
        "id": "zec1",
        "enabled": true,
        "coin": {
            "type": "ZEC"
        },
        "address": "t1YHZHz2DGVMJiggD2P4fBQ2TAPgtL3UwZ8",
        "z-address": "zca7tCyUqn6axyZTWfiFTufI28sJNOnC2p3PHV4txH1XdDGsAjw1AKM8qiHznMTSw5GXUbWqS7P7Qc1sDw93CQePCLuPXXr",
        "rewardRecipients": [
            {
                "type": "op",
                "address": "t1YHZHz2DGVMJiggD2P4fBQ2TAPgtL3UwZ8",
                "percentage": 1.5
            }
        ],
        "blockRefreshInterval": 1000,
        "jobRebroadcastTimeout": 55,
        "clientConnectionTimeout": 600,
        "banning": {
            "enabled": true,
            "time": 600,
            "invalidPercent": 50,
            "checkThreshold": 50
        },
        "ports": {
            "3092": {
                "difficulty": 0.1,
                "varDiff": {
                    "minDiff": 0.01,
                    "maxDiff": null,
                    "targetTime": 15,
                    "retargetTime": 90,
                    "variancePercent": 30,
                    "maxDelta": 1
                }
            },
            "3093": {
                "difficulty": 1
            }
        },
        "daemons": [
            {
                "host": "127.0.0.1",
                "port": 8232,
                "user": "user",
                "password": "pass"
            }
        ],
        "paymentProcessing": {
            "enabled": true,
            "minimumPayment": 0.01,
            "payoutScheme": "PPLNS",
            "payoutSchemeConfig": {
                "factor": 2.0
            }
        }
    }]
}
```

**Comment by Konstantin35** [comment]
Попробуй добавить параметр  `"listenAddress": "0.0.0.0", ип сервера`

```
 "ports": {
            "3092": {
                "difficulty": 0.1,
                "listenAddress": "0.0.0.0", ип сервера
                "varDiff": {
                    "minDiff": 0.01,
                    "maxDiff": null,
                    "targetTime": 15,
                    "retargetTime": 90,
                    "variancePercent": 30,
                    "maxDelta": 1
                }
            },
            "3093": {
                "difficulty": 1
                "listenAddress": "0.0.0.0",
            }
        }
```

**Comment by SergeySypalo** [comment]
Поставил ZCash4Win, он вроде нормально отсинхронизировал блокчейн, теперь не может запуститься, выдает daemon ... take longer than expected to start
Решил попробовать с Монеро, скачал, поставил и отсинхронизировал их кошелек, взял пример конфигурации для монеро, вписал туда свой кошелек локальный который у меня сгенерировался, подправил пароль от пользователя Postgres, в listen address вписал 127.0.0.1, теперь выдает вот такое:
```
[2017-12-22 01:09:33.4691] [I] [ShareRecorder] Online
[2017-12-22 01:09:33.4933] [I] [ApiServer] Launching ...
[2017-12-22 01:09:33.5785] [I] [ApiServer] Online @ 127.0.0.1:4000
[2017-12-22 01:09:33.5785] [I] [PayoutManager] Online
[2017-12-22 01:09:33.5909] [I] [PayoutManager] Processing payments for pool xmr1
[2017-12-22 01:09:33.6158] [I] [xmr1] [Pool] Launching ...
[2017-12-22 01:09:33.6339] [I] [xmr1] [Monero Job Manager] Launching ...
[2017-12-22 01:09:34.9997] [E] [PayoutManager] [xmr1] Payment processing failed System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: Не удается установить соединение с сервером
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
```

**Comment by oliverw** [comment]
Closing for inactivity. Please reopen if necessary.
