### ISSUE TITLE
testing pool..dev 145 pull.. and error ethereum pool

### ISSUE THREAD

**Issue by coreinfo77** [coinfoundry/miningcore#146]
ubuntu 16.04 4.4.0-104-generic

[2018-01-03 18:31:50.1722] [E] [StatsRecorder] System.NullReferenceException: Object reference not set to an instance of an object.
   at MiningCore.Mining.StatsRecorder.UpdateHashrates() in /home/ubuntu/miningcore/src/MiningCore/Mining/StatsRecorder.cs:line 164
   at MiningCore.Mining.StatsRecorder.<<Start>b__17_0>d.MoveNext() in /home/ubuntu/miningcore/src/MiningCore/Mining/StatsRecorder.cs:line 91 System.NullReferenceException: Object reference not set to an instance of an object.
   at MiningCore.Mining.StatsRecorder.UpdateHashrates() in /home/ubuntu/miningcore/src/MiningCore/Mining/StatsRecorder.cs:line 164
   at MiningCore.Mining.StatsRecorder.<<Start>b__17_0>d.MoveNext() in /home/ubuntu/miningcore/src/MiningCore/Mining/StatsRecorder.cs:line 91    at MiningCore.Mining.StatsRecorder.UpdateHashrates() in /home/ubuntu/miningcore/src/MiningCore/Mining/StatsRecorder.cs:line 164
   at MiningCore.Mining.StatsRecorder.<<Start>b__17_0>d.MoveNext() in /home/ubuntu/miningcore/src/MiningCore/Mining/StatsRecorder.cs:line 91

**Comment by oliverw** [comment]
Could you post the contents of line /home/ubuntu/miningcore/src/MiningCore/Mining/StatsRecorder.cs:line 164

**Comment by coreinfo77** [comment]
163                 // update^M
164                 pool.PoolStats.ConnectedMiners = byMiner.Length;^M
165                 pool.PoolStats.PoolHashRate = poolHashrate;^M
166                 pool.PoolStats.ValidSharesPerSecond = (int) (poolHashesCountAccumulated / windowActual);^M
167 ^M

**Comment by oliverw** [comment]
Fixed by #7a808d6ce643e4d46184e534d050d5703b4442df
