### ISSUE TITLE
Payment processing failed 

### ISSUE THREAD

**Issue by epicmario7133** [coinfoundry/miningcore#1615]
Hello i'm trying to use this pool for my eth private network made with geth but i'm having problems:
Payment processing failed System.Exception: Unable to determine block reward: Unsupported chain type
   at Miningcore.Blockchain.Ethereum.EthereumPayoutHandler.GetBaseBlockReward
   
   here the geth startup line:
   
   geth --networkid 171 --datadir BlockChainData/ --http --http.addr [0.0.0.0](https://0.0.0.0/) --http.api admin,eth,miner,net,txpool,personal,web3 --allow-insecure-unlock --http.corsdomain "*" --http.vhosts "*" --http.port 8545 --unlock *private*--password pass.txt --allow-insecure-unlock --mine --cache 1024
   
Any help is welcome

**Comment by papagruz** [comment]
Hello. Change "chainTypeOverride" in config.json to "Main"

**Comment by epicmario7133** [comment]
> Hello. Change "chainTypeOverride" in config.json to "Main"

Thanks but now have this problem:
Payment processing failed System.InvalidOperationException: This NpgsqlTransaction has completed; it is no longer usable.
   at Npgsql.NpgsqlTransaction.CheckReady()
   at Npgsql.NpgsqlTransaction.Rollback(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlTransaction.Rollback()

**Comment by epicmario7133** [comment]
Thx but now i have this error:
Payment processing failed System.InvalidOperationException: Sequence contains more than one element
   at System.Linq.ThrowHelper.ThrowMoreThanOneElementException()
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.ThrowMultipleRows(Row row) in /_/Dapper/SqlMapper.cs:line 1157
   at Dapper.SqlMapper.QueryRowAsync[T](IDbConnection cnn, Row row, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 482
   at Miningcore.Persistence.Postgres.Repositories.BlockRepository.GetBlockByHeightAsync(IDbConnection con, String poolId, Int64 height) in /home/mario/miningcore/src/Miningcore/Persistence/Postgres/Repositories/BlockRepository.cs:line 121
   at Miningcore.Extensions.ConnectionFactoryExtensions.Run[T](IConnectionFactory factory, Func`2 action) in /home/mario/miningcore/src/Miningcore/Extensions/ConnectionFactoryExtensions.cs:line 30
   at Miningcore.Blockchain.Ethereum.EthereumPayoutHandler.ClassifyBlocksAsync(IMiningPool pool, Block[] blocks, CancellationToken ct) in /home/mario/miningcore/src/Miningcore/Blockchain/Ethereum/EthereumPayoutHandler.cs:line 197
   at Miningcore.Payments.PayoutManager.UpdatePoolBalancesAsync(IMiningPool pool, PoolConfig poolConfig, IPayoutHandler handler, IPayoutScheme scheme, CancellationToken ct) in /home/mario/miningcore/src/Miningcore/Payments/PayoutManager.cs:line 156
   at Miningcore.Payments.PayoutManager.ProcessPoolsAsync(CancellationToken ct) in /home/mario/miningcore/src/Miningcore/Payments/PayoutManager.cs:line 104    at System.Linq.ThrowHelper.ThrowMoreThanOneElementException()
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.ThrowMultipleRows(Row row) in /_/Dapper/SqlMapper.cs:line 1157
   at Dapper.SqlMapper.QueryRowAsync[T](IDbConnection cnn, Row row, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 482
   at Miningcore.Persistence.Postgres.Repositories.BlockRepository.GetBlockByHeightAsync(IDbConnection con, String poolId, Int64 height) in /home/mario/miningcore/src/Miningcore/Persistence/Postgres/Repositories/BlockRepository.cs:line 121
   at Miningcore.Extensions.ConnectionFactoryExtensions.Run[T](IConnectionFactory factory, Func`2 action) in /home/mario/miningcore/src/Miningcore/Extensions/ConnectionFactoryExtensions.cs:line 30
   at Miningcore.Blockchain.Ethereum.EthereumPayoutHandler.ClassifyBlocksAsync(IMiningPool pool, Block[] blocks, CancellationToken ct) in /home/mario/miningcore/src/Miningcore/Blockchain/Ethereum/EthereumPayoutHandler.cs:line 197
   at Miningcore.Payments.PayoutManager.UpdatePoolBalancesAsync(IMiningPool pool, PoolConfig poolConfig, IPayoutHandler handler, IPayoutScheme scheme, CancellationToken ct) in /home/mario/miningcore/src/Miningcore/Payments/PayoutManager.cs:line 156
   at Miningcore.Payments.PayoutManager.ProcessPoolsAsync(CancellationToken ct) in /home/mario/miningcore/src/Miningcore/Payments/PayoutManager.cs:line 104
