### ISSUE TITLE
[Bitcoin] Invalid base58 data error on a legacy-type wallet

### ISSUE THREAD

**Issue by npmain** [coinfoundry/miningcore#1651]
OS: Uduntu-22.0.4 TLS
Bitcoinnode1 - regtest mode
Bitcoinnode2 - regtest mode
Both nodes are connected.
First 101 blocks are generated by bitcoin-cli
If I start mining by cpuminer in solo mode - all works properly.

Pools section from config.json:

 ```
  "pools": [
         {
             "id": "bitcoin1",
             "enabled": true,
             "coin": "bitcoin",
             "address": "bcrt1q3vxjg7pe9gu2skmq5w5v2hr5dn0r60nnaspgqv",
             "rewardRecipients": [
                 {
                     "address": "bcrt1q3vxjg7pe9gu2skmq5w5v2hr5dn0r60nnaspgqv",
                     "percentage": 1.5
                 }
 ```

Addresses was retrieved by run 
```
bitcoin-cli -regtest getnewaddress -legacy
```

After pool start I got the error:
```
[2023-03-09 20:34:34.9179] [I] [bitcoin1] All daemons synched with blockchain
[2023-03-09 20:34:34.9997] [E] [bitcoin1] System.FormatException: Invalid base58 data System.FormatException: Invalid base58 data
   at NBitcoin.DataEncoders.Base58Encoder.DecodeData(String encoded)
   at NBitcoin.DataEncoders.Base58CheckEncoder.DecodeData(String encoded)
   at Miningcore.Blockchain.Bitcoin.BitcoinUtils.AddressToDestination(String address, Network expectedNetwork) in /home/md0/miningcore/src/Miningcore/Blockchain/Bitcoin/BitcoinUtils.cs:line 20
   at Miningcore.Blockchain.Bitcoin.BitcoinJobManagerBase`1.AddressToDestination(String address, Nullable`1 addressType) in /home/md0/miningcore/src/Miningcore/Blockchain/Bitcoin/BitcoinJobManagerBase.cs:line 527
   at Miningcore.Blockchain.Bitcoin.BitcoinJobManagerBase`1.PostStartInitAsync(CancellationToken ct) in /home/md0/miningcore/src/Miningcore/Blockchain/Bitcoin/BitcoinJobManagerBase.cs:line 481
   at Miningcore.Blockchain.JobManagerBase`1.StartAsync(CancellationToken ct) in /home/md0/miningcore/src/Miningcore/Blockchain/JobManagerBase.cs:line 112
   at Miningcore.Blockchain.Bitcoin.BitcoinPool.SetupJobManager(CancellationToken ct) in /home/md0/miningcore/src/Miningcore/Blockchain/Bitcoin/BitcoinPool.cs:line 368
   at Miningcore.Mining.PoolBase.RunAsync(CancellationToken ct) in /home/md0/miningcore/src/Miningcore/Mining/PoolBase.cs:line 392    at NBitcoin.DataEncoders.Base58Encoder.DecodeData(String encoded)
   at NBitcoin.DataEncoders.Base58CheckEncoder.DecodeData(String encoded)
   at Miningcore.Blockchain.Bitcoin.BitcoinUtils.AddressToDestination(String address, Network expectedNetwork) in /home/md0/miningcore/src/Miningcore/Blockchain/Bitcoin/BitcoinUtils.cs:line 20
   at Miningcore.Blockchain.Bitcoin.BitcoinJobManagerBase`1.AddressToDestination(String address, Nullable`1 addressType) in /home/md0/miningcore/src/Miningcore/Blockchain/Bitcoin/BitcoinJobManagerBase.cs:line 527
   at Miningcore.Blockchain.Bitcoin.BitcoinJobManagerBase`1.PostStartInitAsync(CancellationToken ct) in /home/md0/miningcore/src/Miningcore/Blockchain/Bitcoin/BitcoinJobManagerBase.cs:line 481
   at Miningcore.Blockchain.JobManagerBase`1.StartAsync(CancellationToken ct) in /home/md0/miningcore/src/Miningcore/Blockchain/JobManagerBase.cs:line 112
   at Miningcore.Blockchain.Bitcoin.BitcoinPool.SetupJobManager(CancellationToken ct) in /home/md0/miningcore/src/Miningcore/Blockchain/Bitcoin/BitcoinPool.cs:line 368
   at Miningcore.Mining.PoolBase.RunAsync(CancellationToken ct) in /home/md0/miningcore/src/Miningcore/Mining/PoolBase.cs:line 392
```

But if I will check Base58 with online base58 decode service I'll got error.
Ok, makes "-bech32" address and got same error from pool, but all correct with base58services.

In production mode (with main blockchain) I get pool work only with bech32 address, not with Legacy.

**Comment by jon4hz** [comment]
You can add `"addressType": "BechSegwit"` to your pool config and use bech32 addresses.

**Comment by Spollock2020** [comment]
As per closed ticket on same issue...   This worked for me... 
./bitcoin-cli getnewaddress "" "legacy"    

Pool up and running now.

**Comment by npmain** [comment]
> 



> As per closed ticket on same issue... This worked for me... ./bitcoin-cli getnewaddress "" "legacy"
> 
> Pool up and running now.

Not for regtest network.
