### ISSUE TITLE
GETH WALLET LOCKED - how to pass unlock password 

### ISSUE THREAD

**Issue by ghost** [coinfoundry/miningcore#1664]
I have a question that i could not find solution to 

How do i pass the account unlock password in the config file

**Comment by ghost** [comment]
I have the beloe config for 

"paymentProcessing": {
          "enabled": true,
          "minimumPayment": 1,
          "payoutScheme": "PPLNS",
          "coinbasePassword": "password",
          "payoutSchemeConfig": {
            "factor": 0.8
          },

Netowrk is callisto  Mining Works fine

**Comment by ghost** [comment]
[2023-04-18 05:22:26.6940] [E] [clo1] System.Exception: eth_sendTransaction returned error: authentication needed: password or unlock code -32000 System.Exception: eth_sendTransaction returned error: authentication needed: password or unlock code -32000
   at Miningcore.Blockchain.Ethereum.EthereumPayoutHandler.PayoutAsync(Balance balance, CancellationToken ct) in /home/miningcore/src/Miningcore/Blockchain/Ethereum/EthereumPayoutHandler.cs:line 440
   at Miningcore.Blockchain.Ethereum.EthereumPayoutHandler.PayoutAsync(IMiningPool pool, Balance[] balances, CancellationToken ct) in /home/miningcore/src/Miningcore/Blockchain/Ethereum/EthereumPayoutHandler.cs:line 267    at Miningcore.Blockchain.Ethereum.EthereumPayoutHandler.PayoutAsync(Balance balance, CancellationToken ct) in /home/miningcore/src/Miningcore/Blockchain/Ethereum/EthereumPayoutHandler.cs:line 440
   at Miningcore.Blockchain.Ethereum.EthereumPayoutHandler.PayoutAsync(IMiningPool pool, Balance[] balances, CancellationToken ct) in /home/miningcore/src/Miningcore/Blockchain/Ethereum/EthereumPayoutHandler.cs:line 267

**Comment by ghost** [comment]
Okay i fixed this error

Unlocked account while opening  geth with flags 

./geth-linux-amd64 --http --http.addr 192.168.100.3 --http.port 8546 --mine --miner.etherbase 0x8A4b79aB5D910a217b2E75fB8fd4e5546fg0907894 --unlock 0x8A4b79aB5D910a217b2E75fB8fd4e5546fg090789 --allow-insecure-unlock --password /home/callisto/password.txt
