### ISSUE TITLE
eth_sendTransaction returned error: invalid sender code -32000

### ISSUE THREAD

**Issue by Pollycraft42** [coinfoundry/miningcore#1690]
I tried setting up an Elhereum mining pool.
Everytime the payoutmanager runs through I get this error

[2023-05-27 21:08:12.1757] [I] [Elhereum] [Ethereum Payout Handler] Sending 6,36186 ELH to 0xf34fa63cb9522379d2f2b23f6098a50cc2071316
[2023-05-27 21:08:12.1806] [E] [Elhereum] System.Exception: eth_sendTransaction returned error: invalid sender code -32000 System.Exception: eth_sendTransaction returned error: invalid sender code -32000
   at Miningcore.Blockchain.Ethereum.EthereumPayoutHandler.PayoutAsync(Balance balance, CancellationToken ct) in /home/exory/miningcore/src/Miningcore/Blockchain/Ethereum/EthereumPayoutHandler.cs:line 458
   at Miningcore.Blockchain.Ethereum.EthereumPayoutHandler.PayoutAsync(IMiningPool pool, Balance[] balances, CancellationToken ct) in /home/exory/miningcore/src/Miningcore/Blockchain/Ethereum/EthereumPayoutHandler.cs:line 267    at Miningcore.Blockchain.Ethereum.EthereumPayoutHandler.PayoutAsync(Balance balance, CancellationToken ct) in /home/exory/miningcore/src/Miningcore/Blockchain/Ethereum/EthereumPayoutHandler.cs:line 458
   at Miningcore.Blockchain.Ethereum.EthereumPayoutHandler.PayoutAsync(IMiningPool pool, Balance[] balances, CancellationToken ct) in /home/exory/miningcore/src/Miningcore/Blockchain/Ethereum/EthereumPayoutHandler.cs:line 267

Here is the output I get using the trace debug option.
![WhatsApp Bild 2023-05-27 um 00 21 41](https://github.com/oliverw/miningcore/assets/92719524/33060d7a-6731-44cb-a96d-ba82c033d574)

Is there any know solution for that issue?

**Comment by Miguel974** [comment]
hello pollycraft42

**Comment by ghost** [comment]
It appears to be a repo. It was incorrectly integrated by the creator of the repo. Some mods are missing from the EthereumPayout files. Ask the creator of the repo.
