### ISSUE TITLE
Unknown error.

### ISSUE THREAD

**Issue by says112** [coinfoundry/miningcore#1706]
Hello! Can you please tell me what is the error at startup?

[2023-07-10 01:06:52.1648] [E] [MAZA] Unable to convert suggested difficulty [
  16384
] System.InvalidCastException: Object must implement IConvertible.
   at System.Convert.ChangeType(Object value, TypeCode typeCode, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, TypeCode typeCode)
   at Miningcore.Blockchain.Bitcoin.BitcoinPool.OnSuggestDifficultyAsync(StratumConnection connection, Timestamped1 tsRequest) in /home/sansanych/miningcore/src/Miningcore/Blockchain/Bitcoin/BitcoinPool.cs:line 231    at System.Convert.ChangeType(Object value, TypeCode typeCode, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, TypeCode typeCode)
   at Miningcore.Blockchain.Bitcoin.BitcoinPool.OnSuggestDifficultyAsync(StratumConnection connection, Timestamped1 tsRequest) in /home/sansanych/miningcore/src/Miningcore/Blockchain/Bitcoin/BitcoinPool.cs:line 231

**Comment by ghost** [comment]
Can you share your config file? @says112 
Are the nodes up and running? Fully synced?

What are you trying to achieve? Please use the GitHub template for issue's
