### ISSUE TITLE
sha3-256d Invalid hash of the base 58 string

### ISSUE THREAD

**Issue by VaporumCoin** [coinfoundry/miningcore#1715]
Wondering if its a setup issue on my end or a code issue.  When setting up a pool for a sha3d coin, when running the build im getting the following error. 

[2023-09-07 20:02:47.5245] [I] [redb] All daemons synched with blockchain
[2023-09-07 20:02:47.5775] [E] [redb] System.FormatException: Invalid hash of the base 58 string System.FormatException: Invalid hash of the base 58 string
   at NBitcoin.DataEncoders.Base58CheckEncoder.DecodeData(String encoded)
   at Miningcore.Blockchain.Bitcoin.BitcoinUtils.AddressToDestination(String address, Network expectedNetwork) in /home/pool/miningcore/src/Miningcore/Blockchain/Bitcoin/BitcoinUtils.cs:line 20
   at Miningcore.Blockchain.Bitcoin.BitcoinJobManagerBase`1.AddressToDestination(String address, Nullable`1 addressType) in /home/pool/miningcore/src/Miningcore/Blockchain/Bitcoin/BitcoinJobManagerBase.cs:line 532
   at Miningcore.Blockchain.Bitcoin.BitcoinJobManagerBase`1.PostStartInitAsync(CancellationToken ct) in /home/pool/miningcore/src/Miningcore/Blockchain/Bitcoin/BitcoinJobManagerBase.cs:line 486
   at Miningcore.Blockchain.JobManagerBase`1.StartAsync(CancellationToken ct) in /home/pool/miningcore/src/Miningcore/Blockchain/JobManagerBase.cs:line 112
   at Miningcore.Blockchain.Bitcoin.BitcoinPool.SetupJobManager(CancellationToken ct) in /home/pool/miningcore/src/Miningcore/Blockchain/Bitcoin/BitcoinPool.cs:line 368
   at Miningcore.Mining.PoolBase.RunAsync(CancellationToken ct) in /home/pool/miningcore/src/Miningcore/Mining/PoolBase.cs:line 392    at NBitcoin.DataEncoders.Base58CheckEncoder.DecodeData(String encoded)
   at Miningcore.Blockchain.Bitcoin.BitcoinUtils.AddressToDestination(String address, Network expectedNetwork) in /home/pool/miningcore/src/Miningcore/Blockchain/Bitcoin/BitcoinUtils.cs:line 20
   at Miningcore.Blockchain.Bitcoin.BitcoinJobManagerBase`1.AddressToDestination(String address, Nullable`1 addressType) in /home/pool/miningcore/src/Miningcore/Blockchain/Bitcoin/BitcoinJobManagerBase.cs:line 532
   at Miningcore.Blockchain.Bitcoin.BitcoinJobManagerBase`1.PostStartInitAsync(CancellationToken ct) in /home/pool/miningcore/src/Miningcore/Blockchain/Bitcoin/BitcoinJobManagerBase.cs:line 486
   at Miningcore.Blockchain.JobManagerBase`1.StartAsync(CancellationToken ct) in /home/pool/miningcore/src/Miningcore/Blockchain/JobManagerBase.cs:line 112
   at Miningcore.Blockchain.Bitcoin.BitcoinPool.SetupJobManager(CancellationToken ct) in /home/pool/miningcore/src/Miningcore/Blockchain/Bitcoin/BitcoinPool.cs:line 368
   at Miningcore.Mining.PoolBase.RunAsync(CancellationToken ct) in /home/pool/miningcore/src/Miningcore/Mining/PoolBase.cs:line 392
[2023-09-07 20:02:47.6089] [I] [Lifetime] Application is shutting down...

Building appears to have went without issue, getting this when starting the pool. Any ideas?

Thank you for your time!

**Comment by xiaolin1579** [comment]
used legacy address for pool address
