### ISSUE TITLE
nexa error

### ISSUE THREAD

**Issue by seoseo29** [coinfoundry/miningcore#1721]
`[2023-10-13 09:17:15.7557] [E] [nexa] System.DllNotFoundException: Unable to load shared library 'libnexapow' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibnexapow: cannot open shared object file: No such file or directory System.DllNotFoundException: Unable to load shared library 'libnexapow' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibnexapow: cannot open shared object file: No such file or directory
   at Miningcore.Native.NexaPow.schnorr_init()
   at Miningcore.Crypto.Hashing.Algorithms.NexaPow.DigestInit(PoolConfig poolConfig) in /home/pool/1/miningcore/src/Miningcore/Crypto/Hashing/Algorithms/NexaPow.cs:line 75
   at Miningcore.Blockchain.Nexa.NexaJobManager.PostChainIdentifyConfigure() in /home/pool/1/miningcore/src/Miningcore/Blockchain/Nexa/NexaJobManager.cs:line 80
   at Miningcore.Blockchain.Bitcoin.BitcoinJobManagerBase`1.PostStartInitAsync(CancellationToken ct) in /home/pool/1/miningcore/src/Miningcore/Blockchain/Bitcoin/BitcoinJobManagerBase.cs:line 474
   at Miningcore.Blockchain.JobManagerBase`1.StartAsync(CancellationToken ct) in /home/pool/1/miningcore/src/Miningcore/Blockchain/JobManagerBase.cs:line 112
   at Miningcore.Blockchain.Nexa.NexaPool.SetupJobManager(CancellationToken ct) in /home/pool/1/miningcore/src/Miningcore/Blockchain/Nexa/NexaPool.cs:line 297
   at Miningcore.Mining.PoolBase.RunAsync(CancellationToken ct) in /home/pool/1/miningcore/src/Miningcore/Mining/PoolBase.cs:line 392    at Miningcore.Native.NexaPow.schnorr_init()
   at Miningcore.Crypto.Hashing.Algorithms.NexaPow.DigestInit(PoolConfig poolConfig) in /home/pool/1/miningcore/src/Miningcore/Crypto/Hashing/Algorithms/NexaPow.cs:line 75
   at Miningcore.Blockchain.Nexa.NexaJobManager.PostChainIdentifyConfigure() in /home/pool/1/miningcore/src/Miningcore/Blockchain/Nexa/NexaJobManager.cs:line 80
   at Miningcore.Blockchain.Bitcoin.BitcoinJobManagerBase`1.PostStartInitAsync(CancellationToken ct) in /home/pool/1/miningcore/src/Miningcore/Blockchain/Bitcoin/BitcoinJobManagerBase.cs:line 474
   at Miningcore.Blockchain.JobManagerBase`1.StartAsync(CancellationToken ct) in /home/pool/1/miningcore/src/Miningcore/Blockchain/JobManagerBase.cs:line 112
   at Miningcore.Blockchain.Nexa.NexaPool.SetupJobManager(CancellationToken ct) in /home/pool/1/miningcore/src/Miningcore/Blockchain/Nexa/NexaPool.cs:line 297
   at Miningcore.Mining.PoolBase.RunAsync(CancellationToken ct) in /home/pool/1/miningcore/src/Miningcore/Mining/PoolBase.cs:line 392
`

**Comment by xiaolin1579** [comment]
Perhaps there is a problem compiling "libnexapow".

**Comment by MiningCryptoLive** [comment]
Nexa is not supported. You would have to add the required libraries and changes needed

**Comment by Reggerriee** [comment]
> `[2023-10-13 09:17:15.7557] [E] [nexa] System.DllNotFoundException: Unable to load shared library 'libnexapow' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibnexapow: cannot open shared object file: No such file or directory System.DllNotFoundException: Unable to load shared library 'libnexapow' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibnexapow: cannot open shared object file: No such file or directory at Miningcore.Native.NexaPow.schnorr_init() at Miningcore.Crypto.Hashing.Algorithms.NexaPow.DigestInit(PoolConfig poolConfig) in /home/pool/1/miningcore/src/Miningcore/Crypto/Hashing/Algorithms/NexaPow.cs:line 75 at Miningcore.Blockchain.Nexa.NexaJobManager.PostChainIdentifyConfigure() in /home/pool/1/miningcore/src/Miningcore/Blockchain/Nexa/NexaJobManager.cs:line 80 at Miningcore.Blockchain.Bitcoin.BitcoinJobManagerBase`1.PostStartInitAsync(CancellationToken ct) in /home/pool/1/miningcore/src/Miningcore/Blockchain/Bitcoin/BitcoinJobManagerBase.cs:line 474 at Miningcore.Blockchain.JobManagerBase`1.StartAsync(CancellationToken ct) in /home/pool/1/miningcore/src/Miningcore/Blockchain/JobManagerBase.cs:line 112 at Miningcore.Blockchain.Nexa.NexaPool.SetupJobManager(CancellationToken ct) in /home/pool/1/miningcore/src/Miningcore/Blockchain/Nexa/NexaPool.cs:line 297 at Miningcore.Mining.PoolBase.RunAsync(CancellationToken ct) in /home/pool/1/miningcore/src/Miningcore/Mining/PoolBase.cs:line 392 at Miningcore.Native.NexaPow.schnorr_init() at Miningcore.Crypto.Hashing.Algorithms.NexaPow.DigestInit(PoolConfig poolConfig) in /home/pool/1/miningcore/src/Miningcore/Crypto/Hashing/Algorithms/NexaPow.cs:line 75 at Miningcore.Blockchain.Nexa.NexaJobManager.PostChainIdentifyConfigure() in /home/pool/1/miningcore/src/Miningcore/Blockchain/Nexa/NexaJobManager.cs:line 80 at Miningcore.Blockchain.Bitcoin.BitcoinJobManagerBase`1.PostStartInitAsync(CancellationToken ct) in /home/pool/1/miningcore/src/Miningcore/Blockchain/Bitcoin/BitcoinJobManagerBase.cs:line 474 at Miningcore.Blockchain.JobManagerBase`1.StartAsync(CancellationToken ct) in /home/pool/1/miningcore/src/Miningcore/Blockchain/JobManagerBase.cs:line 112 at Miningcore.Blockchain.Nexa.NexaPool.SetupJobManager(CancellationToken ct) in /home/pool/1/miningcore/src/Miningcore/Blockchain/Nexa/NexaPool.cs:line 297 at Miningcore.Mining.PoolBase.RunAsync(CancellationToken ct) in /home/pool/1/miningcore/src/Miningcore/Mining/PoolBase.cs:line 392 `

You added the following to the build launcher: libgmp-dev ?
(build-ubuntu-20.04.sh:
#install dev-dependencies
sudo apt-get update; \
  sudo apt-get -y install dotnet-sdk-6.0 git cmake build-essential libssl-dev pkg-config libboost-all-dev libsodium-dev libzmq5 libgmp-dev)
  
AND build-libs-linux.sh line:
(cd ../Native/libnexapow && make clean && make) && mv ../Native/libnexapow/libnexapow.so "$OutDir"

**Comment by xiaolin1579** [comment]
Hopefully this commit will fix this problem.
https://github.com/xiaolin1579/miningcore/commit/5a3b63ad703c83bd4cc0582f2a829437d9baa6d1

**Comment by jon4hz** [comment]
Adding libgmp-dev should fix it. I never updated the linux build scripts but take a look at the changes in the Dockerfile. The dependencies should be correct in there.

**Comment by blackmennewstyle** [comment]
It would be probably also a god idea to open the bug in the right repository since that one does not support NEXA :)
