### ISSUE TITLE
client connection to stratum problem

### ISSUE THREAD

**Issue by Talangor** [coinfoundry/miningcore#221]
everything is fine until i connect to my server to mine then this happens
i have installed miningcore in ubuntu 16.4 64bit

im no programmer but i think its related to 64bit and 32bit compatibility
can anyone help me with this?
it does it in litecoin and bitcoin

```
[2018-02-24 12:44:21.5918] [E] [btc1] [Pool] Unable to convert suggested difficulty [
  "0000000a"
] System.NotSupportedException: Memory stream is not expandable.
   at System.IO.__Error.MemoryStreamNotExpandable()
   at System.IO.MemoryStream.set_Capacity(Int32 value)
   at System.IO.MemoryStream.EnsureCapacity(Int32 value)
   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Write(String value)
   at Newtonsoft.Json.Utilities.JavaScriptUtils.WriteEscapedJavaScriptString(TextWriter writer, String s, Char delimiter, Boolean appendDelimiters, Boolean[] charEscapeFlags, StringEscapeHandling stringEscapeHandling, IArrayPool`1 bufferPool, Char[]& writeBuffer)
   at Newtonsoft.Json.JsonTextWriter.WriteEscapedString(String value, Boolean quote)
   at Newtonsoft.Json.JsonWriter.WriteValue(JsonWriter writer, PrimitiveTypeCode typeCode, Object value)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at MiningCore.Stratum.StratumClient.Send[T](T payload) in /home/litecoin/miningcore/src/MiningCore/Stratum/StratumClient.cs:line 187
   at MiningCore.Blockchain.Bitcoin.BitcoinPoolBase`2.OnGetTransactions(StratumClient client, Timestamped`1 tsRequest) in /home/litecoin/miningcore/src/MiningCore/Blockchain/Bitcoin/BitcoinPoolBase.cs:line 229    at System.IO.__Error.MemoryStreamNotExpandable()
   at System.IO.MemoryStream.set_Capacity(Int32 value)
   at System.IO.MemoryStream.EnsureCapacity(Int32 value)
   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Write(String value)
   at Newtonsoft.Json.Utilities.JavaScriptUtils.WriteEscapedJavaScriptString(TextWriter writer, String s, Char delimiter, Boolean appendDelimiters, Boolean[] charEscapeFlags, StringEscapeHandling stringEscapeHandling, IArrayPool`1 bufferPool, Char[]& writeBuffer)
   at Newtonsoft.Json.JsonTextWriter.WriteEscapedString(String value, Boolean quote)
   at Newtonsoft.Json.JsonWriter.WriteValue(JsonWriter writer, PrimitiveTypeCode typeCode, Object value)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at MiningCore.Stratum.StratumClient.Send[T](T payload) in /home/litecoin/miningcore/src/MiningCore/Stratum/StratumClient.cs:line 187
   at MiningCore.Blockchain.Bitcoin.BitcoinPoolBase`2.OnGetTransactions(StratumClient client, Timestamped`1 tsRequest) in /home/litecoin/miningcore/src/MiningCore/Blockchain/Bitcoin/BitcoinPoolBase.cs:line 229
```

**Comment by Talangor** [comment]
hi peeps
is this too elementary?
if so please point me in right direction
thanks in advance

**Comment by oliverw** [comment]
Which release are you using?

**Comment by Talangor** [comment]
hi
thanks for the reply
i have removed the Ubuntu 16.4 lts
i decided to move to Windows 2008R2
the problem have been solved 
another problem still remains


[2018-02-27 09:32:51.5433] [E] [ltc1] [Pool] [0HLBTKUU4M68J] Connection json error state: Unexpected character encountered while parsing value: ?. Path '', line 0, position 0.
[2018-02-27 09:32:51.5433] [E] [ltc1] [Pool] [0HLBTKUU4M68J] Connection json error state: Unexpected character encountered while parsing value: ☺. Path '', line 0, position 0.
[2018-02-27 09:32:51.5433] [E] [ltc1] [Pool] [0HLBTKUU4M68J] Connection json error state: Unexpected character encountered while parsing value: ▬. Path '', line 0, position 0.

i suspect client this time any coment on this?

**Comment by oliverw** [comment]
@Talangor We have those on coinfoundry.org as well. I suspect they web-scrape bots attempting to access the pool using HTTP.
