### ISSUE TITLE
Client socket is not connected

### ISSUE THREAD

**Issue by rymdluo** [coinfoundry/miningcore#250]
### Description

I'm not particularly sure if this is an issue, since I can perceive no meaningful effect on my pool.

### Steps to Reproduce

Unknown, no major changes (if any at all were made). 
 - Added 'check' to haproxy load balancer (no change when removed)

It just popped up this afternoon when I was checking my logs. It is possible that a user is doing something unauthorized? Or dropped off after the initial connection?

### Expected behavior

Normal mining activity.

### Actual behavior

Appears to still be normal mining activity, but with this accompanying log a few times a second.

```
[2018-03-09 12:24:06.0552] [E] [electroneum] [Pool] [0HLC5MPT4AOVH] Connection json error state: Unexpected character encountered while parsing value: P. Path '', line 0, position 0.
[2018-03-09 12:24:06.0552] [E] [electroneum] [Pool] [0HLC5MPT4AOVH] Connection json error state: MiningCore.Buffers.PooledArraySegment`1[System.Byte]
[2018-03-09 12:24:06.1769] [E] [electroneum] OnClientConnected NetUV.Core.Native.OperationException: ENOTCONN (ENOTCONN) : ENOTCONN : socket is not connected
   at NetUV.Core.Native.NativeMethods.ThrowOperationException(uv_err_code error)
   at NetUV.Core.Native.NativeMethods.TcpGetPeerName(IntPtr handle)
   at NetUV.Core.Handles.Tcp.GetPeerEndPoint()
   at MiningCore.Stratum.StratumServer.OnClientConnected(Tcp con, IPEndPoint endpointConfig, Loop loop)    at NetUV.Core.Native.NativeMethods.ThrowOperationException(uv_err_code error)
   at NetUV.Core.Native.NativeMethods.TcpGetPeerName(IntPtr handle)
   at NetUV.Core.Handles.Tcp.GetPeerEndPoint()
   at MiningCore.Stratum.StratumServer.OnClientConnected(Tcp con, IPEndPoint endpointConfig, Loop loop)
[2018-03-09 12:24:06.7688] [E] [electroneum] OnClientConnected NetUV.Core.Native.OperationException: ENOTCONN (ENOTCONN) : ENOTCONN : socket is not connected
   at NetUV.Core.Native.NativeMethods.ThrowOperationException(uv_err_code error)
   at NetUV.Core.Native.NativeMethods.TcpGetPeerName(IntPtr handle)
   at NetUV.Core.Handles.Tcp.GetPeerEndPoint()
   at MiningCore.Stratum.StratumServer.OnClientConnected(Tcp con, IPEndPoint endpointConfig, Loop loop)    at NetUV.Core.Native.NativeMethods.ThrowOperationException(uv_err_code error)
   at NetUV.Core.Native.NativeMethods.TcpGetPeerName(IntPtr handle)
   at NetUV.Core.Handles.Tcp.GetPeerEndPoint()
   at MiningCore.Stratum.StratumServer.OnClientConnected(Tcp con, IPEndPoint endpointConfig, Loop loop)
```

### Reproduces how often

A few times every second. It appears to happen whenever a client connects.

### Version

Release 0.19, Ubuntu 16.04

### Additional Information

None

**Comment by oliverw** [comment]
It means a client disconnected right when the stratum handled the connect.

**Comment by zheng9980419** [comment]
Is the problem solved？
