### ISSUE TITLE
[Ethereum Job Manager] Daemon does not own pool-address

### ISSUE THREAD

**Issue by itsmylife44** [coinfoundry/miningcore#256]
if i start miningcore  cannot start the pool ..

```console
 [eth1] [Ethereum Job Manager] Daemon does not own pool-address
```

here is my config 

```javascript
{
    "logging": {
        "level": "info",
        "enableConsoleLog": true,
        "enableConsoleColors": true,
        "logFile": "",
        "logBaseDirectory": "",
        "perPoolLogFile": false
    },
    "banning": {
        "manager": "integrated",
        "banOnJunkReceive": true,
        "banOnInvalidShares": false
    },
    "notifications": {
        "enabled": true,
        "email": {
            "host": "smtp.example.com",
            "port": 587,
            "user": "user",
            "password": "password",
            "fromAddress": "info@yourpool.org",
            "fromName": "support"
        },
        "admin": {
            "enabled": false,
            "emailAddress": "user@example.com",
            "notifyBlockFound": true
        }
    },
    "persistence": {
        "postgres": {
            "host": "127.0.0.1",
            "port": 5432,
            "user": "miningcore",
            "password": "password",
            "database": "miningcore"
        }
    },
    "paymentProcessing": {
        "enabled": true,
        "interval": 600,
        "shareRecoveryFile": "recovered-shares.txt"
    },
    "pools": [{
        "id": "eth1",
        "enabled": true,
        "coin": {
            "type": "ETH"
        },
        "address": "0x00D3a6B28727411a853b3daf50D327E340B44932",
        "rewardRecipients": [{
                "type": "op",
                "address": "0x00D3a6B28727411a853b3daf50D327E340B44932",
                "percentage": 0
        }],
        "blockRefreshInterval": 500,
        "clientConnectionTimeout": 600,
        "banning": {
            "enabled": true,
            "time": 600,
            "invalidPercent": 50,
            "checkThreshold": 50
        },
        "ports": {
            "3072": {
                "difficulty": 0.1,
                "varDiff": {
                    "minDiff": 0.05,
                    "maxDiff": null,
                    "targetTime": 15,
                    "retargetTime": 90,
                    "variancePercent": 30
                }
            },
            "3073": {
                "difficulty": 5000
            }
        },
        "daemons": [
            {
                "host": "127.0.0.1",
                "port": 8545,
                "user": "pool",
                "password": "password of parity wallet"
            }
        ],
        "paymentProcessing": {
            "enabled": true,
            "minimumPayment": 0.01,
            "minimumPaymentToPaymentId": 5.0,
            "payoutScheme": "PPLNS",
            "payoutSchemeConfig": {
                "factor": 2.0
            },
            "coinbasePassword": "password of parity wallet",
            "keepUncles": false,
            "keepTransactionFees": false
        }
    }]
}
```

**Comment by bitspill** [comment]
FYI you included your password in that config and should probably change it.

As for the issue at hand... is the address `0x00D3a6B28727411a853b3daf50D327E340B44932` from the same daemon the pool is connecting to? The pool can't send payouts if it doesn't have control of the private keys.

**Comment by itsmylife44** [comment]
the deamon is on the same server  .. parity and miningcore are on the same server right now ..  
i have exported the private keys from parity and copied in the folder ..

**Comment by ravensorb** [comment]
I am having he same issue.  I have generated a key with parity so I am 100% sure the pool owns the key.  I then add that key to the config for miningcore and start it up.  As soon as it starts up I get the same error.  What are we missing?

**Comment by calvintam236** [comment]
@itsmylife44 you don't need user/pass for parity daemons in `config.json`. however, did you set `"portWs"`?

Currently, more detail for config wiki at #274. (waiting for @oliverw to catch up and fill in the blanks)

**Comment by calvintam236** [comment]
@ravensorb what is your parity arguments right now? did you use the examples here: https://github.com/coinfoundry/miningcore/wiki/Coin-Daemon-&-Wallet-RPC

**Comment by ravensorb** [comment]
I am running it via docker right now so the params look like this (overkill right now -- I'll restrict it down once I get it all working)

```
docker run -ti --name parity-nightly --restart unless-stopped --net=bridge -v /opt/parity/nightly:/opt/parity -p 8180:8180 -p 8545:8545 -p 8546:8546 -p 30303:30303 -p 30303:30303/udp parit
y/parity:nightly --ui-interface all --jsonrpc-interface all --jsonrpc-apis all --jsonrpc-hosts all --ui-hosts=all --ws-interface all --ui-no-validation --config
/opt/parity/config-musicoin.toml --no-ancient-blocks --no-serve-light --max-peers 250 --snapshot-peers 50 --min-peers 50 --mode active --pruning fast --cache-size 4096 --force-ui
```

Also in my config.toml file I have set the author to be the wallet I created it parity 

```
[mining]
# Account address to receive reward when block is mined.
author = "0x00Fbbe86be911AeC5Fbce79501AFE47B5430D8D4"
```

I then used that same wallet address in the miningcore config file in the pool config for my "coin" for both the address and the rewardReceipients

```
 "address": "0x00Fbbe86be911AeC5Fbce79501AFE47B5430D8D4",
 "rewardRecipients": [{
                "type": "op",
                "address": "0x00Fbbe86be911AeC5Fbce79501AFE47B5430D8D4",
                "percentage": 0.01
 }],
```

I also set the "coinbasePassword" to be the same password used to generate the wallet.

Quetion -- shouldn't that be called "walletPassword"?

Note: I am able to mine directly against the daemon without issue using ethminer and claymore.  Its just getting the pool to talk to the daemon that I am having an issue with.

**Comment by calvintam236** [comment]
@ravensorb Since you are running inside docker, I would suggest not to use UI. You can use `docker exec`, and wallet is going split from parity core. You should also use stable channel - nightly is not for production/ compatibility at miningcore is not tested on nightly.

I suggest trying `portWs` in your miningcore `config.json`. #274 should have more info to look at.

you need to ask @oliverw why he named it `coinbasePassword`.

**Comment by ravensorb** [comment]
Hmm, I have tried it in and out of docker.  I also tried generated a wallet from inside the container, then doing a ```parity accounts list``` just to confirm that it showed up.  Still nothing.

In regards to the stable vs nightly -- I am using the nightly due to an issue with the stable branch syncing the blockchain for a new node.  

As for #274 - can you be more specific on what I should be looking for?  That config is for dash which is a bit different from eth so there seems to be a lot of settings that are not needed.  

Note: I did set the portWs in the config.json and also in the command line for parity and it doesn't seem to help at all.  Same error...

**Comment by calvintam236** [comment]
#274 shows all parameters I know available for config.json. It does not just for dash. You should look for `portWs`.

**Comment by ravensorb** [comment]
Yep, I tried that and it didn't seem to have any impact at all.

**Comment by ravensorb** [comment]
Note: After fixing the "case" issue, I am now getting a different error

```
 System.NullReferenceException: Object reference not set to an instance of an object.
   at MiningCore.Blockchain.Ethereum.EthereumJobManager.<GetBlockTemplateAsync>d__15.MoveNext() in /tmp/miningcore/src/MiningCore/Blockchain/Ethereum/EthereumJobManager.cs:line
182
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Ethereum.EthereumJobManager.<PostStartInitAsync>d__39.MoveNext() in /tmp/miningcore/src/MiningCore/Blockchain/Ethereum/EthereumJobManager.cs:line 557
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.JobManagerBase`1.<StartAsync>d__21.MoveNext() in /tmp/miningcore/src/MiningCore/Blockchain/JobManagerBase.cs:line 120
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Ethereum.EthereumPool.<SetupJobManager>d__8.MoveNext() in /tmp/miningcore/src/MiningCore/Blockchain/Ethereum/EthereumPool.cs:line 264
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Mining.PoolBase.<StartAsync>d__40.MoveNext() in /tmp/miningcore/src/MiningCore/Mining/PoolBase.cs:line 325 System.NullReferenceException: Object reference not set to an instance of an object.
   at MiningCore.Blockchain.Ethereum.EthereumJobManager.<GetBlockTemplateAsync>d__15.MoveNext() in /tmp/miningcore/src/MiningCore/Blockchain/Ethereum/EthereumJobManager.cs:line
182
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Ethereum.EthereumJobManager.<PostStartInitAsync>d__39.MoveNext() in /tmp/miningcore/src/MiningCore/Blockchain/Ethereum/EthereumJobManager.cs:line 557
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.JobManagerBase`1.<StartAsync>d__21.MoveNext() in /tmp/miningcore/src/MiningCore/Blockchain/JobManagerBase.cs:line 120
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Ethereum.EthereumPool.<SetupJobManager>d__8.MoveNext() in /tmp/miningcore/src/MiningCore/Blockchain/Ethereum/EthereumPool.cs:line 264
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Mining.PoolBase.<StartAsync>d__40.MoveNext() in /tmp/miningcore/src/MiningCore/Mining/PoolBase.cs:line 325    at MiningCore.Blockchain.Ethereum.EthereumJobManager.<GetBlockTemplateAsync>d__15.MoveNext() in /tmp/miningcore/src/MiningCore/Blockchain/Ethereum/EthereumJobManager.cs:line 182
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Ethereum.EthereumJobManager.<PostStartInitAsync>d__39.MoveNext() in /tmp/miningcore/src/MiningCore/Blockchain/Ethereum/EthereumJobManager.cs:line 557
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.JobManagerBase`1.<StartAsync>d__21.MoveNext() in /tmp/miningcore/src/MiningCore/Blockchain/JobManagerBase.cs:line 120
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Ethereum.EthereumPool.<SetupJobManager>d__8.MoveNext() in /tmp/miningcore/src/MiningCore/Blockchain/Ethereum/EthereumPool.cs:line 264
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Mining.PoolBase.<StartAsync>d__40.MoveNext() in /tmp/miningcore/src/MiningCore/Mining/PoolBase.cs:line 325
System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.) ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at MiningCore.Blockchain.Ethereum.EthereumJobManager.<GetBlockTemplateAsync>d__15.MoveNext() in /tmp/miningcore/src/MiningCore/Blockchain/Ethereum/EthereumJobManager.cs:line
182
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Ethereum.EthereumJobManager.<PostStartInitAsync>d__39.MoveNext() in /tmp/miningcore/src/MiningCore/Blockchain/Ethereum/EthereumJobManager.cs:line 557
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.JobManagerBase`1.<StartAsync>d__21.MoveNext() in /tmp/miningcore/src/MiningCore/Blockchain/JobManagerBase.cs:line 120
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Ethereum.EthereumPool.<SetupJobManager>d__8.MoveNext() in /tmp/miningcore/src/MiningCore/Blockchain/Ethereum/EthereumPool.cs:line 264
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Mining.PoolBase.<StartAsync>d__40.MoveNext() in /tmp/miningcore/src/MiningCore/Mining/PoolBase.cs:line 349
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Program.<>c.<<Start>b__30_2>d.MoveNext() in /tmp/miningcore/src/MiningCore/Program.cs:line 618
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Program.<Start>d__30.MoveNext() in /tmp/miningcore/src/MiningCore/Program.cs:line 603
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at MiningCore.Program.Main(String[] args) in /tmp/miningcore/src/MiningCore/Program.cs:line 118
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at MiningCore.Blockchain.Ethereum.EthereumJobManager.<GetBlockTemplateAsync>d__15.MoveNext() in /tmp/miningcore/src/MiningCore/Blockchain/Ethereum/EthereumJobManager.cs:line
182
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Ethereum.EthereumJobManager.<PostStartInitAsync>d__39.MoveNext() in /tmp/miningcore/src/MiningCore/Blockchain/Ethereum/EthereumJobManager.cs:line 557
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.JobManagerBase`1.<StartAsync>d__21.MoveNext() in /tmp/miningcore/src/MiningCore/Blockchain/JobManagerBase.cs:line 120
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Ethereum.EthereumPool.<SetupJobManager>d__8.MoveNext() in /tmp/miningcore/src/MiningCore/Blockchain/Ethereum/EthereumPool.cs:line 264
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Mining.PoolBase.<StartAsync>d__40.MoveNext() in /tmp/miningcore/src/MiningCore/Mining/PoolBase.cs:line 349
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Program.<>c.<<Start>b__30_2>d.MoveNext() in /tmp/miningcore/src/MiningCore/Program.cs:line 618
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Program.<Start>d__30.MoveNext() in /tmp/miningcore/src/MiningCore/Program.cs:line 603
```

**Comment by ravensorb** [comment]
So it looks like my specific issue was caused by running a very very new nightly build -- apparently parity has made some pretty big changes to the json objects being returned.
