### ISSUE TITLE
Cannot Connect to Remote XMR Daemon

### ISSUE THREAD

**Issue by shtse8** [coinfoundry/miningcore#26]
```
[2017-09-26 21:04:32.7317] [I] [xmr] [Pool] Launching ...
[2017-09-26 21:04:32.7456] [E] [xmr] System.ArgumentException: endPoints must not be empty
   at MiningCore.Contracts.Contract.Requires[TException](Boolean predicate, String message) in /root/miningcore/src/MiningCore/Contracts/Contract.cs:line 38
   at MiningCore.DaemonInterface.DaemonClient.Configure(DaemonEndpointConfig[] endPoints, String rpcLocation, String digestAuthRealm) in /root/miningcore/src/MiningCore/DaemonInterface/DaemonClient.cs:line 72
   at MiningCore.Blockchain.Monero.MoneroPool.<SetupJobManager>d__10.MoveNext() in /root/miningcore/src/MiningCore/Blockchain/Monero/MoneroPool.cs:line 300
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Mining.PoolBase`1.<StartAsync>d__49.MoveNext() in /root/miningcore/src/MiningCore/Mining/PoolBase.cs:line 488 System.ArgumentException: endPoints must not be empty
   at MiningCore.Contracts.Contract.Requires[TException](Boolean predicate, String message) in /root/miningcore/src/MiningCore/Contracts/Contract.cs:line 38
   at MiningCore.DaemonInterface.DaemonClient.Configure(DaemonEndpointConfig[] endPoints, String rpcLocation, String digestAuthRealm) in /root/miningcore/src/MiningCore/DaemonInterface/DaemonClient.cs:line 72
   at MiningCore.Blockchain.Monero.MoneroPool.<SetupJobManager>d__10.MoveNext() in /root/miningcore/src/MiningCore/Blockchain/Monero/MoneroPool.cs:line 300
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Mining.PoolBase`1.<StartAsync>d__49.MoveNext() in /root/miningcore/src/MiningCore/Mining/PoolBase.cs:line 488    at MiningCore.Contracts.Contract.Requires[TException](Boolean predicate, String message) in /root/miningcore/src/MiningCore/Contracts/Contract.cs:line 38
   at MiningCore.DaemonInterface.DaemonClient.Configure(DaemonEndpointConfig[] endPoints, String rpcLocation, String digestAuthRealm) in /root/miningcore/src/MiningCore/DaemonInterface/DaemonClient.cs:line 72
   at MiningCore.Blockchain.Monero.MoneroPool.<SetupJobManager>d__10.MoveNext() in /root/miningcore/src/MiningCore/Blockchain/Monero/MoneroPool.cs:line 300
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Mining.PoolBase`1.<StartAsync>d__49.MoveNext() in /root/miningcore/src/MiningCore/Mining/PoolBase.cs:line 488
[2017-09-26 21:04:32.7764] [I] [dgb-scrypt] [Bitcoin Job Manager] All daemons online
[2017-09-26 21:04:32.7764] [I] [dash] [Bitcoin Job Manager] All daemons online
```

I have tried curl, it works:
```
curl \
	-u username:passowrd --digest \
    -X POST http://10.138.0.5:13301/json_rpc \
    -d '{"jsonrpc":"2.0","id":"0","method":"get_info"}' \
    -H 'Content-Type: application/json'
```

I guess it should be the authentication problem.

**Comment by oliverw** [comment]
Hmm, looks like a configuration problem to me. Did you check your config? Did you compare to the 
[example](https://github.com/coinfoundry/miningcore/blob/master/examples/monero_pool.json)?

**Comment by shtse8** [comment]
Yes, I believe the config shouldn't have any problem. Just daemon host, port, username, password, very simple configs. I have set dash, dgb, both works fine.
I have also tested with json-rpc. the proxy can also response properly.

**Comment by oliverw** [comment]
@shtse8 I'd like to invite you to a slack channel for discussing topics a bit quicker than solely relying on the github ticket system. Please email me at info@coinfoundry.org.

**Comment by oliverw** [comment]
@shtse8 You realize that Monero needs two discrete daemons? One is the <code>monerod</code> and the other is <code>monero-wallet-rpc</code> which needs to be configured to connect to the former.

**Comment by shtse8** [comment]
Let me check. I just started the monerod daemon and tried with curl json-rpc, which works fine.

**Comment by oliverw** [comment]
Like I said, you need a wallet-daemon too.
