### ISSUE TITLE
Ethereum Job Manager should stop when SIGINT received (failed to stop)

### ISSUE THREAD

**Issue by calvintam236** [coinfoundry/miningcore#260]
### Description

When miningcore tried to connect to pdsql and failed at the beginning, it gives error but ethereum job manager will continue to load, and Ctrl+C would not stop the software even "SIGINT received".

### Steps to Reproduce

1. `miningcore -c config.json`
2. cannot connect to postgres with error "Payment processing failed System.Net.Sockets.SocketException (0x80004005): Connection refused"
3. Ctrl+C

### Expected behavior

It should stop the software completely.

### Actual behavior

It doesn't stop, keep trying to connect to Ethereum Job Manager.

### Version

Release 0.19 on Debian Stretch.
Edit: Release 0.20 as well.

### Additional Information

Better error message needed for database connection error.

```console

 ███╗   ███╗██╗███╗   ██╗██╗███╗   ██╗ ██████╗  ██████╗ ██████╗ ██████╗ ███████╗
 ████╗ ████║██║████╗  ██║██║████╗  ██║██╔════╝ ██╔════╝██╔═══██╗██╔══██╗██╔════╝
 ██╔████╔██║██║██╔██╗ ██║██║██╔██╗ ██║██║  ███╗██║     ██║   ██║██████╔╝█████╗
 ██║╚██╔╝██║██║██║╚██╗██║██║██║╚██╗██║██║   ██║██║     ██║   ██║██╔══██╗██╔══╝
 ██║ ╚═╝ ██║██║██║ ╚████║██║██║ ╚████║╚██████╔╝╚██████╗╚██████╔╝██║  ██║███████╗

 https://github.com/coinfoundry/miningcore

 Please contribute to the development of the project by donating:

 BTC  - 17QnVor1B6oK1rWnVVBrdX9gFzVkZZbhDm
 LTC  - LTK6CWastkmBzGxgQhTTtCUjkjDA14kxzC
 DASH - XqpBAV9QCaoLnz42uF5frSSfrJTrqHoxjp
 ZEC  - t1YHZHz2DGVMJiggD2P4fBQ2TAPgtLSUwZ7
 ZCL  - t1MFU1vD3YKgsK6Uh8hW7UTY8mKAV2xVqBr
 ETH  - 0xcb55abBfe361B12323eb952110cE33d5F28BeeE1
 ETC  - 0xF8cCE9CE143C68d3d4A7e6bf47006f21Cfcf93c0
 XMR  - 475YVJbPHPedudkhrcNp1wDcLMTGYusGPF5fqE7XjnragVLPdqbCHBdZg3dF4dN9hXMjjvGbykS6a77dTAQvGrpiQqHp2eH

Using configuration file /miningcore/config.json

[2018-03-12 02:33:21.1395] [W] [Program] Running as root is discouraged! 
[2018-03-12 02:33:21.4416] [I] [Program] Running on .NET Core 4.6.0.0 under Linux 4.13.0-36-generic #40~16.04.1-Ubuntu SMP Fri Feb 16 23:25:58 UTC 2018 [X64 - X64] 
[2018-03-12 02:33:22.8523] [I] [ShareRecorder] Online 
[2018-03-12 02:33:22.9863] [I] [ApiServer] Launching ... 
[2018-03-12 02:33:24.8380] [I] [ApiServer] Online @ 0.0.0.0:80 
[2018-03-12 02:33:24.8722] [I] [PayoutManager] Online 
[2018-03-12 02:33:24.8783] [I] [StatsRecorder] Online 
[2018-03-12 02:33:24.9126] [I] [PayoutManager] Processing payments for pool etc-testnet 
[2018-03-12 02:33:25.3437] [I] [etc-testnet] [Pool] Launching ... 
[2018-03-12 02:33:26.1793] [I] [etc-testnet] [Ethereum Job Manager] Launching ... 
[2018-03-12 02:33:26.6023] [E] [PayoutManager] [etc-testnet] Payment processing failed System.Net.Sockets.SocketException (0x80004005): Connection refused
   at Npgsql.NpgsqlConnector.Connect(NpgsqlTimeout timeout)
   at Npgsql.NpgsqlConnector.<RawOpen>d__146.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlConnector.<Open>d__143.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.ConnectorPool.<AllocateLong>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Npgsql.NpgsqlConnection.<Open>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlConnection.Open()
   at MiningCore.Persistence.Postgres.ConnectionFactory.OpenConnection() in /tmp/miningcore-0.19/src/MiningCore/Persistence/Postgres/ConnectionFactory.cs:line 43
   at MiningCore.Extensions.ConnectionFactoryExtensions.Run[T](IConnectionFactory factory, Func`2 action) in /tmp/miningcore-0.19/src/MiningCore/Extensions/ConnectionFactoryExtensions.cs:line 49
   at MiningCore.Payments.PayoutManager.<UpdatePoolBalancesAsync>d__12.MoveNext() in /tmp/miningcore-0.19/src/MiningCore/Payments/PayoutManager.cs:line 114
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Payments.PayoutManager.<ProcessPoolsAsync>d__11.MoveNext() in /tmp/miningcore-0.19/src/MiningCore/Payments/PayoutManager.cs:line 95    at Npgsql.NpgsqlConnector.Connect(NpgsqlTimeout timeout)
   at Npgsql.NpgsqlConnector.<RawOpen>d__146.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlConnector.<Open>d__143.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.ConnectorPool.<AllocateLong>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Npgsql.NpgsqlConnection.<Open>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlConnection.Open()
   at MiningCore.Persistence.Postgres.ConnectionFactory.OpenConnection() in /tmp/miningcore-0.19/src/MiningCore/Persistence/Postgres/ConnectionFactory.cs:line 43
   at MiningCore.Extensions.ConnectionFactoryExtensions.Run[T](IConnectionFactory factory, Func`2 action) in /tmp/miningcore-0.19/src/MiningCore/Extensions/ConnectionFactoryExtensions.cs:line 49
   at MiningCore.Payments.PayoutManager.<UpdatePoolBalancesAsync>d__12.MoveNext() in /tmp/miningcore-0.19/src/MiningCore/Payments/PayoutManager.cs:line 114
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Payments.PayoutManager.<ProcessPoolsAsync>d__11.MoveNext() in /tmp/miningcore-0.19/src/MiningCore/Payments/PayoutManager.cs:line 95
[2018-03-12 02:33:26.8238] [I] [etc-testnet] [Ethereum Job Manager] Waiting for daemons to come online ... 
[2018-03-12 02:33:34.9066] [I] [StatsRecorder] Updating hashrates for pool etc-testnet 
[2018-03-12 02:33:34.9681] [W] [StatsRecorder] Retry 1 due to Npgsql: SocketException (Connection refused) 
[2018-03-12 02:33:34.9812] [W] [StatsRecorder] Retry 2 due to Npgsql: SocketException (Connection refused) 
[2018-03-12 02:33:34.9949] [W] [StatsRecorder] Retry 3 due to Npgsql: SocketException (Connection refused) 
[2018-03-12 02:33:35.0042] [W] [StatsRecorder] Retry 4 due to Npgsql: SocketException (Connection refused) 
[2018-03-12 02:33:35.0170] [E] [StatsRecorder] System.Net.Sockets.SocketException (0x80004005): Connection refused
   at Npgsql.NpgsqlConnector.Connect(NpgsqlTimeout timeout)
   at Npgsql.NpgsqlConnector.<RawOpen>d__146.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlConnector.<Open>d__143.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.ConnectorPool.<AllocateLong>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Npgsql.NpgsqlConnection.<Open>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlConnection.Open()
   at MiningCore.Persistence.Postgres.ConnectionFactory.OpenConnection() in /tmp/miningcore-0.19/src/MiningCore/Persistence/Postgres/ConnectionFactory.cs:line 43
   at MiningCore.Extensions.ConnectionFactoryExtensions.Run[T](IConnectionFactory factory, Func`2 action) in /tmp/miningcore-0.19/src/MiningCore/Extensions/ConnectionFactoryExtensions.cs:line 49
   at Polly.Policy.<>c__DisplayClass67_0`1.<Execute>b__0(Context ctx, CancellationToken ct)
   at Polly.Policy.<>c__DisplayClass77_0`1.<ExecuteInternal>b__0(Context ctx, CancellationToken ct)
   at Polly.RetrySyntax.<>c__DisplayClass5_0.<Retry>b__1(Context ctx, CancellationToken ct)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, IEnumerable`1 shouldRetryExceptionPredicates, IEnumerable`1 shouldRetryResultPredicates, Func`1 policyStateFactory)
   at Polly.RetrySyntax.<>c__DisplayClass5_1.<Retry>b__0(Action`2 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.ExecuteInternal[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`1 action)
   at MiningCore.Mining.StatsRecorder.UpdatePoolHashrates()
   at MiningCore.Mining.StatsRecorder.<Start>b__19_1() in /tmp/miningcore-0.19/src/MiningCore/Mining/StatsRecorder.cs:line 92 System.Net.Sockets.SocketException (0x80004005): Connection refused
   at Npgsql.NpgsqlConnector.Connect(NpgsqlTimeout timeout)
   at Npgsql.NpgsqlConnector.<RawOpen>d__146.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlConnector.<Open>d__143.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.ConnectorPool.<AllocateLong>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Npgsql.NpgsqlConnection.<Open>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlConnection.Open()
   at MiningCore.Persistence.Postgres.ConnectionFactory.OpenConnection() in /tmp/miningcore-0.19/src/MiningCore/Persistence/Postgres/ConnectionFactory.cs:line 43
   at MiningCore.Extensions.ConnectionFactoryExtensions.Run[T](IConnectionFactory factory, Func`2 action) in /tmp/miningcore-0.19/src/MiningCore/Extensions/ConnectionFactoryExtensions.cs:line 49
   at Polly.Policy.<>c__DisplayClass67_0`1.<Execute>b__0(Context ctx, CancellationToken ct)
   at Polly.Policy.<>c__DisplayClass77_0`1.<ExecuteInternal>b__0(Context ctx, CancellationToken ct)
   at Polly.RetrySyntax.<>c__DisplayClass5_0.<Retry>b__1(Context ctx, CancellationToken ct)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, IEnumerable`1 shouldRetryExceptionPredicates, IEnumerable`1 shouldRetryResultPredicates, Func`1 policyStateFactory)
   at Polly.RetrySyntax.<>c__DisplayClass5_1.<Retry>b__0(Action`2 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.ExecuteInternal[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`1 action)
   at MiningCore.Mining.StatsRecorder.UpdatePoolHashrates()
   at MiningCore.Mining.StatsRecorder.<Start>b__19_1() in /tmp/miningcore-0.19/src/MiningCore/Mining/StatsRecorder.cs:line 92    at Npgsql.NpgsqlConnector.Connect(NpgsqlTimeout timeout)
   at Npgsql.NpgsqlConnector.<RawOpen>d__146.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlConnector.<Open>d__143.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.ConnectorPool.<AllocateLong>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Npgsql.NpgsqlConnection.<Open>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlConnection.Open()
   at MiningCore.Persistence.Postgres.ConnectionFactory.OpenConnection() in /tmp/miningcore-0.19/src/MiningCore/Persistence/Postgres/ConnectionFactory.cs:line 43
   at MiningCore.Extensions.ConnectionFactoryExtensions.Run[T](IConnectionFactory factory, Func`2 action) in /tmp/miningcore-0.19/src/MiningCore/Extensions/ConnectionFactoryExtensions.cs:line 49
   at Polly.Policy.<>c__DisplayClass67_0`1.<Execute>b__0(Context ctx, CancellationToken ct)
   at Polly.Policy.<>c__DisplayClass77_0`1.<ExecuteInternal>b__0(Context ctx, CancellationToken ct)
   at Polly.RetrySyntax.<>c__DisplayClass5_0.<Retry>b__1(Context ctx, CancellationToken ct)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, IEnumerable`1 shouldRetryExceptionPredicates, IEnumerable`1 shouldRetryResultPredicates, Func`1 policyStateFactory)
   at Polly.RetrySyntax.<>c__DisplayClass5_1.<Retry>b__0(Action`2 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.ExecuteInternal[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`1 action)
   at MiningCore.Mining.StatsRecorder.UpdatePoolHashrates()
   at MiningCore.Mining.StatsRecorder.<Start>b__19_1() in /tmp/miningcore-0.19/src/MiningCore/Mining/StatsRecorder.cs:line 92
[2018-03-12 02:33:36.8307] [I] [etc-testnet] [Ethereum Job Manager] Waiting for daemons to come online ... 
[2018-03-12 02:33:46.8354] [I] [etc-testnet] [Ethereum Job Manager] Waiting for daemons to come online ... 
[2018-03-12 02:33:56.8393] [I] [etc-testnet] [Ethereum Job Manager] Waiting for daemons to come online ... 
[2018-03-12 02:34:06.8420] [I] [etc-testnet] [Ethereum Job Manager] Waiting for daemons to come online ... 
[2018-03-12 02:34:16.8458] [I] [etc-testnet] [Ethereum Job Manager] Waiting for daemons to come online ... 
[2018-03-12 02:34:26.8494] [I] [etc-testnet] [Ethereum Job Manager] Waiting for daemons to come online ... 
[2018-03-12 02:34:36.8583] [I] [etc-testnet] [Ethereum Job Manager] Waiting for daemons to come online ... 
[2018-03-12 02:34:46.8617] [I] [etc-testnet] [Ethereum Job Manager] Waiting for daemons to come online ... 
[2018-03-12 02:34:56.8655] [I] [etc-testnet] [Ethereum Job Manager] Waiting for daemons to come online ... 
[2018-03-12 02:35:06.8686] [I] [etc-testnet] [Ethereum Job Manager] Waiting for daemons to come online ... 
[2018-03-12 02:35:16.8750] [I] [etc-testnet] [Ethereum Job Manager] Waiting for daemons to come online ... 
^C[2018-03-12 02:35:25.5593] [I] [Program] SIGINT received. Exiting. 
[2018-03-12 02:35:26.8778] [I] [etc-testnet] [Ethereum Job Manager] Waiting for daemons to come online ... 
[2018-03-12 02:35:36.8832] [I] [etc-testnet] [Ethereum Job Manager] Waiting for daemons to come online ... 
^C[2018-03-12 02:35:46.8851] [I] [etc-testnet] [Ethereum Job Manager] Waiting for daemons to come online ... 
[2018-03-12 02:35:56.8880] [I] [etc-testnet] [Ethereum Job Manager] Waiting for daemons to come online ... 
[2018-03-12 02:36:06.8925] [I] [etc-testnet] [Ethereum Job Manager] Waiting for daemons to come online ... 
[2018-03-12 02:36:16.8964] [I] [etc-testnet] [Ethereum Job Manager] Waiting for daemons to come online ... 
[2018-03-12 02:36:26.9006] [I] [etc-testnet] [Ethereum Job Manager] Waiting for daemons to come online ... 
[2018-03-12 02:36:36.9040] [I] [etc-testnet] [Ethereum Job Manager] Waiting for daemons to come online ... 
[2018-03-12 02:36:46.9071] [I] [etc-testnet] [Ethereum Job Manager] Waiting for daemons to come online ... 
[2018-03-12 02:36:56.9117] [I] [etc-testnet] [Ethereum Job Manager] Waiting for daemons to come online ... 
[2018-03-12 02:37:06.9161] [I] [etc-testnet] [Ethereum Job Manager] Waiting for daemons to come online ... 
[2018-03-12 02:37:16.9215] [I] [etc-testnet] [Ethereum Job Manager] Waiting for daemons to come online ... 
```

**Comment by rymdluo** [comment]
I believe the "fail to stop" issue is not related to payment processing error, which is the result of payments attempting to connect to the wallet when a daemon isn't connected.

Running a successfully connected daemon still results in the same "fail to stop" behavior for me. In the meantime, a PID kill works well enough.

It's also worth noting that I did not notice this bug in Release 0.22 and prior though, while @calvintam236 has it on Release 0.20 and 0.19.
