### ISSUE TITLE
Error processing request mining.submit [4] System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by calvintam236** [coinfoundry/miningcore#268]
### Description

Error processing request mining.submit [4] System.NullReferenceException: Object reference not set to an instance of an object.

### Steps to Reproduce

1. Mine a block on the testnet
2. Get paid

### Reproduces how often

100%

### Version

Release 20.

### Additional Information

```console
[2018-03-15 01:08:44.4743] [I] [PayoutManager] Processing payments for pool etc-testnet 
[2018-03-15 01:08:44.9869] [I] [PayoutManager] Processing payments for pool etc-testnet, block 2129880 
[2018-03-15 01:08:45.4613] [I] [PayoutManager] Processing payments for pool etc-testnet, block 2129881 
[2018-03-15 01:08:45.6246] [I] [PayoutManager] Processing payments for pool etc-testnet, block 2129882 
[2018-03-15 01:08:45.7660] [I] [PayoutManager] Processing payments for pool etc-testnet, block 2129884 
[2018-03-15 01:08:45.8608] [I] [PayoutManager] No balances over configured minimum payout for pool etc-testnet 
[2018-03-15 01:08:52.4329] [I] [StatsRecorder] Updating hashrates for pool etc-testnet 
[2018-03-15 01:09:04.5310] [I] [etc-testnet] [Ethereum Job Manager] Submitting block 2129884 
[2018-03-15 01:09:04.6999] [I] [etc-testnet] [Ethereum Job Manager] Daemon accepted block 2129884 submitted by 0xFaBA3be3b3De5469C3F6C6185150928F3773C7b4 
[2018-03-15 01:09:04.7010] [I] [etc-testnet] [Pool] [0HLCA24DBD618] Share accepted: D=0.5 
[2018-03-15 01:09:07.1834] [I] [etc-testnet] [Ethereum Job Manager] New block 2129886 detected 
[2018-03-15 01:09:07.1841] [I] [etc-testnet] [Pool] Broadcasting job 
[2018-03-15 01:09:07.7972] [I] [etc-testnet] [Pool] [0HLCA24DBD618] Share rejected: MinusOne 
[2018-03-15 01:09:07.9377] [E] [etc-testnet] [Pool] [0HLCA24DBD618] Error processing request mining.submit [4] System.NullReferenceException: Object reference not set to an instance of an object.
   at MiningCore.Mining.PoolBase`1.ConsiderBan(StratumClient client, WorkerContextBase context, PoolShareBasedBanningConfig config) in /tmp/miningcore-0.20/src/MiningCore/Mining/PoolBase.cs:line 350
   at MiningCore.Blockchain.Ethereum.EthereumPool.<OnSubmitAsync>d__5.MoveNext() in /tmp/miningcore-0.20/src/MiningCore/Blockchain/Ethereum/EthereumPool.cs:line 201
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Ethereum.EthereumPool.<OnRequestAsync>d__11.MoveNext() in /tmp/miningcore-0.20/src/MiningCore/Blockchain/Ethereum/EthereumPool.cs:line 301
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Stratum.StratumServer.<>c__DisplayClass14_0.<<OnReceive>b__0>d.MoveNext() in /tmp/miningcore-0.20/src/MiningCore/Stratum/StratumServer.cs:line 210    at MiningCore.Mining.PoolBase`1.ConsiderBan(StratumClient client, WorkerContextBase context, PoolShareBasedBanningConfig config) in /tmp/miningcore-0.20/src/MiningCore/Mining/PoolBase.cs:line 350
   at MiningCore.Blockchain.Ethereum.EthereumPool.<OnSubmitAsync>d__5.MoveNext() in /tmp/miningcore-0.20/src/MiningCore/Blockchain/Ethereum/EthereumPool.cs:line 201
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Ethereum.EthereumPool.<OnRequestAsync>d__11.MoveNext() in /tmp/miningcore-0.20/src/MiningCore/Blockchain/Ethereum/EthereumPool.cs:line 301
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Stratum.StratumServer.<>c__DisplayClass14_0.<<OnReceive>b__0>d.MoveNext() in /tmp/miningcore-0.20/src/MiningCore/Stratum/StratumServer.cs:line 210
[2018-03-15 01:09:08.5571] [I] [etc-testnet] [Ethereum Job Manager] Submitting block 2129884 
[2018-03-15 01:09:08.5741] [I] [etc-testnet] [Ethereum Job Manager] Daemon accepted block 2129884 submitted by 0xFaBA3be3b3De5469C3F6C6185150928F3773C7b4 
[2018-03-15 01:09:08.5741] [I] [etc-testnet] [Pool] [0HLCA24DBD618] Share accepted: D=0.5 
[2018-03-15 01:09:53.5850] [I] [etc-testnet] [Pool] [0HLCA24DBD618] VarDiff update to 0.38 
[2018-03-15 01:09:59.5855] [I] [etc-testnet] [Ethereum Job Manager] New block 2129887 detected 
[2018-03-15 01:09:59.5855] [I] [etc-testnet] [Pool] Broadcasting job 
[2018-03-15 01:10:28.7856] [I] [etc-testnet] [Ethereum Job Manager] New block 2129888 detected 
[2018-03-15 01:10:28.7856] [I] [etc-testnet] [Pool] Broadcasting job 
[2018-03-15 01:10:35.3218] [I] [etc-testnet] [Pool] [0HLCA24DBD618] Share rejected: MinusOne 
[2018-03-15 01:10:35.3218] [I] [etc-testnet] [Pool] [0HLCA24DBD618] Share rejected: MinusOne 
[2018-03-15 01:10:35.3218] [I] [etc-testnet] [Pool] [0HLCA24DBD618] Share rejected: MinusOne 
[2018-03-15 01:10:35.3249] [E] [etc-testnet] [Pool] [0HLCA24DBD618] Error processing request mining.submit [4] System.NullReferenceException: Object reference not set to an instance of an object.
   at MiningCore.Mining.PoolBase`1.ConsiderBan(StratumClient client, WorkerContextBase context, PoolShareBasedBanningConfig config) in /tmp/miningcore-0.20/src/MiningCore/Mining/PoolBase.cs:line 350
   at MiningCore.Blockchain.Ethereum.EthereumPool.<OnSubmitAsync>d__5.MoveNext() in /tmp/miningcore-0.20/src/MiningCore/Blockchain/Ethereum/EthereumPool.cs:line 201
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Ethereum.EthereumPool.<OnRequestAsync>d__11.MoveNext() in /tmp/miningcore-0.20/src/MiningCore/Blockchain/Ethereum/EthereumPool.cs:line 301
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Stratum.StratumServer.<>c__DisplayClass14_0.<<OnReceive>b__0>d.MoveNext() in /tmp/miningcore-0.20/src/MiningCore/Stratum/StratumServer.cs:line 210    at MiningCore.Mining.PoolBase`1.ConsiderBan(StratumClient client, WorkerContextBase context, PoolShareBasedBanningConfig config) in /tmp/miningcore-0.20/src/MiningCore/Mining/PoolBase.cs:line 350
   at MiningCore.Blockchain.Ethereum.EthereumPool.<OnSubmitAsync>d__5.MoveNext() in /tmp/miningcore-0.20/src/MiningCore/Blockchain/Ethereum/EthereumPool.cs:line 201
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Ethereum.EthereumPool.<OnRequestAsync>d__11.MoveNext() in /tmp/miningcore-0.20/src/MiningCore/Blockchain/Ethereum/EthereumPool.cs:line 301
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Stratum.StratumServer.<>c__DisplayClass14_0.<<OnReceive>b__0>d.MoveNext() in /tmp/miningcore-0.20/src/MiningCore/Stratum/StratumServer.cs:line 210
[2018-03-15 01:10:35.3249] [E] [etc-testnet] [Pool] [0HLCA24DBD618] Error processing request mining.submit [4] System.NullReferenceException: Object reference not set to an instance of an object.
   at MiningCore.Mining.PoolBase`1.ConsiderBan(StratumClient client, WorkerContextBase context, PoolShareBasedBanningConfig config) in /tmp/miningcore-0.20/src/MiningCore/Mining/PoolBase.cs:line 350
   at MiningCore.Blockchain.Ethereum.EthereumPool.<OnSubmitAsync>d__5.MoveNext() in /tmp/miningcore-0.20/src/MiningCore/Blockchain/Ethereum/EthereumPool.cs:line 201
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Ethereum.EthereumPool.<OnRequestAsync>d__11.MoveNext() in /tmp/miningcore-0.20/src/MiningCore/Blockchain/Ethereum/EthereumPool.cs:line 301
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Stratum.StratumServer.<>c__DisplayClass14_0.<<OnReceive>b__0>d.MoveNext() in /tmp/miningcore-0.20/src/MiningCore/Stratum/StratumServer.cs:line 210    at MiningCore.Mining.PoolBase`1.ConsiderBan(StratumClient client, WorkerContextBase context, PoolShareBasedBanningConfig config) in /tmp/miningcore-0.20/src/MiningCore/Mining/PoolBase.cs:line 350
   at MiningCore.Blockchain.Ethereum.EthereumPool.<OnSubmitAsync>d__5.MoveNext() in /tmp/miningcore-0.20/src/MiningCore/Blockchain/Ethereum/EthereumPool.cs:line 201
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Ethereum.EthereumPool.<OnRequestAsync>d__11.MoveNext() in /tmp/miningcore-0.20/src/MiningCore/Blockchain/Ethereum/EthereumPool.cs:line 301
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Stratum.StratumServer.<>c__DisplayClass14_0.<<OnReceive>b__0>d.MoveNext() in /tmp/miningcore-0.20/src/MiningCore/Stratum/StratumServer.cs:line 210
[2018-03-15 01:10:35.3249] [E] [etc-testnet] [Pool] [0HLCA24DBD618] Error processing request mining.submit [4] System.NullReferenceException: Object reference not set to an instance of an object.
   at MiningCore.Mining.PoolBase`1.ConsiderBan(StratumClient client, WorkerContextBase context, PoolShareBasedBanningConfig config) in /tmp/miningcore-0.20/src/MiningCore/Mining/PoolBase.cs:line 350
   at MiningCore.Blockchain.Ethereum.EthereumPool.<OnSubmitAsync>d__5.MoveNext() in /tmp/miningcore-0.20/src/MiningCore/Blockchain/Ethereum/EthereumPool.cs:line 201
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Ethereum.EthereumPool.<OnRequestAsync>d__11.MoveNext() in /tmp/miningcore-0.20/src/MiningCore/Blockchain/Ethereum/EthereumPool.cs:line 301
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Stratum.StratumServer.<>c__DisplayClass14_0.<<OnReceive>b__0>d.MoveNext() in /tmp/miningcore-0.20/src/MiningCore/Stratum/StratumServer.cs:line 210    at MiningCore.Mining.PoolBase`1.ConsiderBan(StratumClient client, WorkerContextBase context, PoolShareBasedBanningConfig config) in /tmp/miningcore-0.20/src/MiningCore/Mining/PoolBase.cs:line 350
   at MiningCore.Blockchain.Ethereum.EthereumPool.<OnSubmitAsync>d__5.MoveNext() in /tmp/miningcore-0.20/src/MiningCore/Blockchain/Ethereum/EthereumPool.cs:line 201
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Ethereum.EthereumPool.<OnRequestAsync>d__11.MoveNext() in /tmp/miningcore-0.20/src/MiningCore/Blockchain/Ethereum/EthereumPool.cs:line 301
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Stratum.StratumServer.<>c__DisplayClass14_0.<<OnReceive>b__0>d.MoveNext() in /tmp/miningcore-0.20/src/MiningCore/Stratum/StratumServer.cs:line 210

```

**Comment by 21void** [comment]
check your config, do you have following config under your pool configuration?
```
            "banning": {
                "enabled": true,
                "time": 600,
                "invalidPercent": 50,
                "checkThreshold": 50
            },
```

**Comment by calvintam236** [comment]
Yes, of course. By the config wiki, `banning` has renamed.

```javascript
"shareBasedBanning": {
            "enabled": true,
            "time": 600,
            "invalidPercent": 50,
            "checkThreshold": 50
        },
```

**Comment by oliverw** [comment]
```
"banning": {
                "enabled": true,
                "time": 600,
                "invalidPercent": 50,
                "checkThreshold": 50
            },
```

This is the correct config.

**Comment by calvintam236** [comment]
Ok, I will test this config. Meanwhile, PLEASE update the [config wiki](https://github.com/coinfoundry/miningcore/wiki/Configuration) - it says `shareBasedBanning` there.

**Comment by OleksandrBlack** [comment]
`"banning": {

    // "integrated" or "iptables" (linux only - not yet implemented)
    "manager": "integrated",

    "banOnJunkReceive": true,

    "banOnInvalidShares": false
  },`
`
"shareBasedBanning": {

      "enabled": true,

      // How many seconds to ban worker for
      "time": 600,

      // What percent of invalid shares triggers ban
      "invalidPercent": 50,

      // Check invalid percent when this many shares have been submitted
      "checkThreshold": 50
    },
`
in  [config wiki](url=https://github.com/coinfoundry/miningcore/wiki/Configuration)

**Comment by calvintam236** [comment]
I'm still waiting @oliverw to update on #274, which will solve most problems you have

**Comment by oliverw** [comment]
Closing due to inactivity.
