### ISSUE TITLE
Help needed - StatsRecorder Error 

### ISSUE THREAD

**Issue by RepoBike** [coinfoundry/miningcore#287]
Hello everyone.

Needing help to fix the errors. Used Linux-build.sh file that was in the src folder. and it did not fix any of the errors.

```console
[2018-03-25 14:39:13.3434] [I] [StatsRecorder] Updating hashrates for pool Zcash
[2018-03-25 14:39:13.3434] [W] [StatsRecorder] Retry 1 due to Npgsql: SocketException (Connection refused)
[2018-03-25 14:39:13.3434] [W] [StatsRecorder] Retry 2 due to Npgsql: SocketException (Connection refused)
[2018-03-25 14:39:13.3434] [W] [StatsRecorder] Retry 3 due to Npgsql: SocketException (Connection refused)
[2018-03-25 14:39:13.3516] [W] [StatsRecorder] Retry 4 due to Npgsql: SocketException (Connection refused)
[2018-03-25 14:39:13.3516] [E] [StatsRecorder] System.Net.Sockets.SocketException (0x80004005): Connection refused
   at Npgsql.NpgsqlConnector.Connect(NpgsqlTimeout timeout)
   at Npgsql.NpgsqlConnector.<RawOpen>d__148.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlConnector.<Open>d__145.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.ConnectorPool.<AllocateLong>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Npgsql.NpgsqlConnection.<Open>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlConnection.Open()
   at MiningCore.Persistence.Postgres.PgConnectionFactory.OpenConnection() in /home/ultrapool/miningcore/src/MiningCore/Persistence/Postgres/PgConnectionFactory.cs:line 43
   at MiningCore.Extensions.ConnectionFactoryExtensions.Run[T](IConnectionFactory factory, Func`2 action) in /home/ultrapool/miningcore/src/MiningCore/Extensions/ConnectionFactoryExtensions.cs:line 49
   at Polly.Policy.<>c__DisplayClass119_0`1.<Execute>b__0(Context ctx, CancellationToken ct)
   at Polly.Policy.<>c__DisplayClass129_0`1.<ExecuteInternal>b__0(Context ctx, CancellationToken ct)
   at Polly.RetrySyntax.<>c__DisplayClass5_1.<Retry>b__1(Context ctx, CancellationToken ct)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, IEnumerable`1 shouldRetryExceptionPredicates, IEnumerable`1 shouldRetryResultPredicates, Func`1 policyStateFactory)
   at Polly.RetrySyntax.<>c__DisplayClass5_0.<Retry>b__0(Action`2 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.ExecuteInternal[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`1 action)
   at MiningCore.Mining.StatsRecorder.UpdatePoolHashrates()
   at MiningCore.Mining.StatsRecorder.<Start>b__19_1() in /home/ultrapool/miningcore/src/MiningCore/Mining/StatsRecorder.cs:line 92 System.Net.Sockets.SocketException (0x80004005): Connection refused
   at Npgsql.NpgsqlConnector.Connect(NpgsqlTimeout timeout)
   at Npgsql.NpgsqlConnector.<RawOpen>d__148.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlConnector.<Open>d__145.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.ConnectorPool.<AllocateLong>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Npgsql.NpgsqlConnection.<Open>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlConnection.Open()
   at MiningCore.Persistence.Postgres.PgConnectionFactory.OpenConnection() in /home/ultrapool/miningcore/src/MiningCore/Persistence/Postgres/PgConnectionFactory.cs:line 43
   at MiningCore.Extensions.ConnectionFactoryExtensions.Run[T](IConnectionFactory factory, Func`2 action) in /home/ultrapool/miningcore/src/MiningCore/Extensions/ConnectionFactoryExtensions.cs:line 49
   at Polly.Policy.<>c__DisplayClass119_0`1.<Execute>b__0(Context ctx, CancellationToken ct)
   at Polly.Policy.<>c__DisplayClass129_0`1.<ExecuteInternal>b__0(Context ctx, CancellationToken ct)
   at Polly.RetrySyntax.<>c__DisplayClass5_1.<Retry>b__1(Context ctx, CancellationToken ct)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, IEnumerable`1 shouldRetryExceptionPredicates, IEnumerable`1 shouldRetryResultPredicates, Func`1 policyStateFactory)
   at Polly.RetrySyntax.<>c__DisplayClass5_0.<Retry>b__0(Action`2 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.ExecuteInternal[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`1 action)
   at MiningCore.Mining.StatsRecorder.UpdatePoolHashrates()
   at MiningCore.Mining.StatsRecorder.<Start>b__19_1() in /home/ultrapool/miningcore/src/MiningCore/Mining/StatsRecorder.cs:line 92    at Npgsql.NpgsqlConnector.Connect(NpgsqlTimeout timeout)
   at Npgsql.NpgsqlConnector.<RawOpen>d__148.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlConnector.<Open>d__145.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.ConnectorPool.<AllocateLong>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Npgsql.NpgsqlConnection.<Open>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlConnection.Open()
   at MiningCore.Persistence.Postgres.PgConnectionFactory.OpenConnection() in /home/ultrapool/miningcore/src/MiningCore/Persistence/Postgres/PgConnectionFactory.cs:line 43
   at MiningCore.Extensions.ConnectionFactoryExtensions.Run[T](IConnectionFactory factory, Func`2 action) in /home/ultrapool/miningcore/src/MiningCore/Extensions/ConnectionFactoryExtensions.cs:line 49
   at Polly.Policy.<>c__DisplayClass119_0`1.<Execute>b__0(Context ctx, CancellationToken ct)
   at Polly.Policy.<>c__DisplayClass129_0`1.<ExecuteInternal>b__0(Context ctx, CancellationToken ct)
   at Polly.RetrySyntax.<>c__DisplayClass5_1.<Retry>b__1(Context ctx, CancellationToken ct)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, IEnumerable`1 shouldRetryExceptionPredicates, IEnumerable`1 shouldRetryResultPredicates, Func`1 policyStateFactory)
   at Polly.RetrySyntax.<>c__DisplayClass5_0.<Retry>b__0(Action`2 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.ExecuteInternal[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`1 action)
   at MiningCore.Mining.StatsRecorder.UpdatePoolHashrates()
   at MiningCore.Mining.StatsRecorder.<Start>b__19_1() in /home/ultrapool/miningcore/src/MiningCore/Mining/StatsRecorder.cs:line 92
```

**Comment by RepoBike** [comment]
Anything? 
Anyone?

**Comment by oliverw** [comment]
@RepoBike There's something wrong with your database connection. Is your PostgreSQL instance running on the same host as the pool itself or a different one?

**Comment by 21void** [comment]
@RepoBike you need to check you postgres connection. 
Postgres on same host should use 127.0.0.1 as ip with default port 5432. 
Meanwhile on API part, default and example config is listening on 127.0.0.1. To make it available to different host, it need to listen to external IP. Also make sure you firewall to allow in-bound connection to API port

**Comment by RepoBike** [comment]
Thank you @Oliverw & @21void

I will double check the settings and let y'all know.

**Comment by RepoBike** [comment]
Check all settings and redone everything going by how-to. Still have the same errors. 

Is this there a way to use MySQL?

**Comment by RepoBike** [comment]
@oliverw & @21void
Check all settings and redone everything going by how-to. Still have the same errors.
Is this there a way to use MySQL?
