### ISSUE TITLE
[ETH] parity Configuration problem

### ISSUE THREAD

**Issue by lucas556** [coinfoundry/miningcore#301]
### Description
Use parity configuration problems.
If you use the following parity to start, an error will be reported.
`parity --chain testnet --base-path /nodes/parity --db-path /nodes/parity/chains --mode active --no-ui --no-dapps --no-ipc --jsonrpc-hosts "all" --jsonrpc-interface "all" --jsonrpc-threads 4 --jsonrpc-port 8545 --no-discovery --jsonrpc-apis "eth,net,web3,personal,parity,parity_pubsub,rpc" --author 0x4ba760ef2a2e94784956d9f5b94130817c32fc0a --cache-size 512 --logging info --ws-port 8546 --ws-interface all`

The error is: 
```console
[2018-04-08 13:30:50.7902] [E] [eth1] System.FormatException: One of the identified items was in an invalid format.
   at MiningCore.Extensions.StringExtensions.IntegralFromHex[T](String value) in /pool/miningcore-0.22/src/MiningCore/Extensions/StringExtensions.cs:line 102
   at MiningCore.Blockchain.Ethereum.EthereumJobManager.<UpdateNetworkStatsAsync>d__18.MoveNext() in /pool/miningcore-0.22/src/MiningCore/Blockchain/Ethereum/EthereumJobManager.cs:line 286
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Ethereum.EthereumJobManager.<PostStartInitAsync>d__39.MoveNext() in /pool/miningcore-0.22/src/MiningCore/Blockchain/Ethereum/EthereumJobManager.cs:line 552
--- End of stack trace from previous location where exception was thrown ---
```
Use this configuration normally.
`parity --testnet --jsonrpc-interface all --jsonrpc-hosts all`

### Version

miningcore Release 22

**Comment by calvintam236** [comment]
What is your parity version?

**Comment by lucas556** [comment]
@calvintam236 parity version is1.9.5

**Comment by lucas556** [comment]
yes

> 
[2018-04-08 13:30:50.0958] [W] [Program] Running as root is discouraged! 
[2018-04-08 13:30:50.1426] [I] [Program] Running on .NET Core 4.6.0.0 under Linux 4.4.0-105-generic #128-Ubuntu SMP Thu Dec 14 12:42:11 UTC 2017 [X64 - X64] 
[2018-04-08 13:30:50.2371] [I] [ShareRecorder] Online 
[2018-04-08 13:30:50.2466] [I] [ApiServer] Launching ... 
[2018-04-08 13:30:50.4687] [I] [ApiServer] Online @ 127.0.0.1:4000 
[2018-04-08 13:30:50.4749] [I] [PayoutManager] Online 
[2018-04-08 13:30:50.4749] [I] [StatsRecorder] Online 
[2018-04-08 13:30:50.4810] [I] [PayoutManager] Processing payments for pool eth1 
[2018-04-08 13:30:50.5433] [I] [eth1] [Pool] Launching ... 
[2018-04-08 13:30:50.5656] [I] [eth1] [Ethereum Job Manager] Launching ... 
[2018-04-08 13:30:50.6881] [I] [eth1] [Ethereum Job Manager] All daemons online 
[2018-04-08 13:30:50.7165] [I] [eth1] [Ethereum Job Manager] All daemons synched with blockchain 
[2018-04-08 13:30:50.7902] [E] [eth1] System.FormatException: One of the identified items was in an invalid format.
   at MiningCore.Extensions.StringExtensions.IntegralFromHex[T](String value) in /pool/miningcore-0.22/src/MiningCore/Extensions/StringExtensions.cs:line 102
   at MiningCore.Blockchain.Ethereum.EthereumJobManager.<UpdateNetworkStatsAsync>d__18.MoveNext() in /pool/miningcore-0.22/src/MiningCore/Blockchain/Ethereum/EthereumJobManager.cs:line 286
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Ethereum.EthereumJobManager.<PostStartInitAsync>d__39.MoveNext() in /pool/miningcore-0.22/src/MiningCore/Blockchain/Ethereum/EthereumJobManager.cs:line 552
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.JobManagerBase`1.<StartAsync>d__21.MoveNext() in /pool/miningcore-0.22/src/MiningCore/Blockchain/JobManagerBase.cs:line 120
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Ethereum.EthereumPool.<SetupJobManager>d__8.MoveNext() in /pool/miningcore-0.22/src/MiningCore/Blockchain/Ethereum/EthereumPool.cs:line 264
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Mining.PoolBase.<StartAsync>d__40.MoveNext() in /pool/miningcore-0.22/src/MiningCore/Mining/PoolBase.cs:line 325 System.FormatException: One of the identified items was in an invalid format.
   at MiningCore.Extensions.StringExtensions.IntegralFromHex[T](String value) in /pool/miningcore-0.22/src/MiningCore/Extensions/StringExtensions.cs:line 102
   at MiningCore.Blockchain.Ethereum.EthereumJobManager.<UpdateNetworkStatsAsync>d__18.MoveNext() in /pool/miningcore-0.22/src/MiningCore/Blockchain/Ethereum/EthereumJobManager.cs:line 286
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Ethereum.EthereumJobManager.<PostStartInitAsync>d__39.MoveNext() in /pool/miningcore-0.22/src/MiningCore/Blockchain/Ethereum/EthereumJobManager.cs:line 552
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.JobManagerBase`1.<StartAsync>d__21.MoveNext() in /pool/miningcore-0.22/src/MiningCore/Blockchain/JobManagerBase.cs:line 120
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Ethereum.EthereumPool.<SetupJobManager>d__8.MoveNext() in /pool/miningcore-0.22/src/MiningCore/Blockchain/Ethereum/EthereumPool.cs:line 264
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Mining.PoolBase.<StartAsync>d__40.MoveNext() in /pool/miningcore-0.22/src/MiningCore/Mining/PoolBase.cs:line 325    at MiningCore.Extensions.StringExtensions.IntegralFromHex[T](String value) in /pool/miningcore-0.22/src/MiningCore/Extensions/StringExtensions.cs:line 102
   at MiningCore.Blockchain.Ethereum.EthereumJobManager.<UpdateNetworkStatsAsync>d__18.MoveNext() in /pool/miningcore-0.22/src/MiningCore/Blockchain/Ethereum/EthereumJobManager.cs:line 286
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Ethereum.EthereumJobManager.<PostStartInitAsync>d__39.MoveNext() in /pool/miningcore-0.22/src/MiningCore/Blockchain/Ethereum/EthereumJobManager.cs:line 552
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.JobManagerBase`1.<StartAsync>d__21.MoveNext() in /pool/miningcore-0.22/src/MiningCore/Blockchain/JobManagerBase.cs:line 120
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Ethereum.EthereumPool.<SetupJobManager>d__8.MoveNext() in /pool/miningcore-0.22/src/MiningCore/Blockchain/Ethereum/EthereumPool.cs:line 264
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Mining.PoolBase.<StartAsync>d__40.MoveNext() in /pool/miningcore-0.22/src/MiningCore/Mining/PoolBase.cs:line 325
System.AggregateException: One or more errors occurred. (One of the identified items was in an invalid format.) ---> System.FormatException: One of the identified items was in an invalid format.
   at MiningCore.Extensions.StringExtensions.IntegralFromHex[T](String value) in /pool/miningcore-0.22/src/MiningCore/Extensions/StringExtensions.cs:line 102
   at MiningCore.Blockchain.Ethereum.EthereumJobManager.<UpdateNetworkStatsAsync>d__18.MoveNext() in /pool/miningcore-0.22/src/MiningCore/Blockchain/Ethereum/EthereumJobManager.cs:line 286
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Ethereum.EthereumJobManager.<PostStartInitAsync>d__39.MoveNext() in /pool/miningcore-0.22/src/MiningCore/Blockchain/Ethereum/EthereumJobManager.cs:line 552
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.JobManagerBase`1.<StartAsync>d__21.MoveNext() in /pool/miningcore-0.22/src/MiningCore/Blockchain/JobManagerBase.cs:line 120
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Ethereum.EthereumPool.<SetupJobManager>d__8.MoveNext() in /pool/miningcore-0.22/src/MiningCore/Blockchain/Ethereum/EthereumPool.cs:line 264
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Mining.PoolBase.<StartAsync>d__40.MoveNext() in /pool/miningcore-0.22/src/MiningCore/Mining/PoolBase.cs:line 349
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Program.<>c.<<Start>b__30_2>d.MoveNext() in /pool/miningcore-0.22/src/MiningCore/Program.cs:line 618
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Program.<Start>d__30.MoveNext() in /pool/miningcore-0.22/src/MiningCore/Program.cs:line 603
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at MiningCore.Program.Main(String[] args) in /pool/miningcore-0.22/src/MiningCore/Program.cs:line 118
---> (Inner Exception #0) System.FormatException: One of the identified items was in an invalid format.
   at MiningCore.Extensions.StringExtensions.IntegralFromHex[T](String value) in /pool/miningcore-0.22/src/MiningCore/Extensions/StringExtensions.cs:line 102
   at MiningCore.Blockchain.Ethereum.EthereumJobManager.<UpdateNetworkStatsAsync>d__18.MoveNext() in /pool/miningcore-0.22/src/MiningCore/Blockchain/Ethereum/EthereumJobManager.cs:line 286
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Ethereum.EthereumJobManager.<PostStartInitAsync>d__39.MoveNext() in /pool/miningcore-0.22/src/MiningCore/Blockchain/Ethereum/EthereumJobManager.cs:line 552
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.JobManagerBase`1.<StartAsync>d__21.MoveNext() in /pool/miningcore-0.22/src/MiningCore/Blockchain/JobManagerBase.cs:line 120
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Ethereum.EthereumPool.<SetupJobManager>d__8.MoveNext() in /pool/miningcore-0.22/src/MiningCore/Blockchain/Ethereum/EthereumPool.cs:line 264
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Mining.PoolBase.<StartAsync>d__40.MoveNext() in /pool/miningcore-0.22/src/MiningCore/Mining/PoolBase.cs:line 349
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Program.<>c.<<Start>b__30_2>d.MoveNext() in /pool/miningcore-0.22/src/MiningCore/Program.cs:line 618
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Program.<Start>d__30.MoveNext() in /pool/miningcore-0.22/src/MiningCore/Program.cs:line 603<---

Cluster cannot start. Good Bye!
[2018-04-08 13:30:51.0390] [I] [PayoutManager] No updated blocks for pool eth1 
[2018-04-08 13:30:51.0558] [I] [PayoutManager] No balances over configured minimum payout for pool eth1 
^C[2018-04-08 13:30:51.6621] [I] [Program] SIGINT received. Exiting.

**Comment by lucas556** [comment]
I also found this error after synchronizing data using the `parity --testnet --jsonrpc -interface all --jsonrpc-hosts all` node.

**Comment by lucas556** [comment]
this error is ` System.FormatException: One of the identified items was in an invalid format.`

**Comment by lucas556** [comment]
eth testnet  Kovan
