### ISSUE TITLE
Add Support For Ravencoin (x16r)

### ISSUE THREAD

**Issue by Dradden** [coinfoundry/miningcore#309]
Would be great to see this, one of the fastest growing POW coins out there right now.

https://github.com/RavenProject/Ravencoin

**Comment by Dradden** [comment]
`Using configuration file config.json

Error: Coin 'RVN' is not (yet) supported (line 84, column 20)
** AppDomain unhandled exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at MiningCore.Program.OnProcessExit(Object sender, EventArgs e) in C:\Users\Administrator\Desktop\git staging\pool\miningcore\src\MiningC                                        ore\Program.cs:line 654

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at MiningCore.Program.OnProcessExit(Object sender, EventArgs e) in C:\Users\Administrator\Desktop\git staging\pool\miningcore\src\MiningC                                        ore\Program.cs:line 654
Segmentation fault`

Hoping to see this working soon.
