### ISSUE TITLE
Segmentation Fault (RVN Coin Not Supported)

### ISSUE THREAD

**Issue by Dradden** [coinfoundry/miningcore#314]
This is using dev branch.

Using configuration file config.json

Error: Coin 'RVN' is not (yet) supported (line 84, column 20)
** AppDomain unhandled exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at MiningCore.Program.OnProcessExit(Object sender, EventArgs e) in C:\Users\Administrator\Desktop\Miningcore_dev_branch\miningcore\src\MiningCore\Program.cs:line 654

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at MiningCore.Program.OnProcessExit(Object sender, EventArgs e) in C:\Users\Administrator\Desktop\Miningcore_dev_branch\miningcore\src\MiningCore\Program.cs:line 654
Segmentation fault

**Comment by Hamrex** [comment]
Looks like you didn't add the coin to the source.
