### ISSUE TITLE
OnClientConnected System.NullReferenceException

### ISSUE THREAD

**Issue by Dradden** [coinfoundry/miningcore#320]
### Description

When connecting with miner the following error is thrown:

`OnClientConnected System.NullReferenceException: Object reference not set to an instance of an object.
   at MiningCore.Stratum.StratumClient.Init(Loop loop, Tcp tcp, IComponentContext ctx, IMasterClock clock, ValueTuple`2 endpointConfig, String connectionId, Action`1 onNext, Action onCompleted, Action`1 onError) in C:\Users\Administrator\Desktop\Miningcore_dev_branch\miningcore\src\MiningCore\Stratum\StratumClient.cs:line 74
   at MiningCore.Stratum.StratumServer.OnClientConnected(Tcp con, ValueTuple`2 endpointConfig, Loop loop) in C:\Users\Administrator\Desktop\Miningcore_dev_branch\miningcore\src\MiningCore\Stratum\StratumServer.cs:line 163    at MiningCore.Stratum.StratumClient.Init(Loop loop, Tcp tcp, IComponentContext ctx, IMasterClock clock, ValueTuple`2 endpointConfig, String connectionId, Action`1 onNext, Action onCompleted, Action`1 onError) in C:\Users\Administrator\Desktop\Miningcore_dev_branch\miningcore\src\MiningCore\Stratum\StratumClient.cs:line 74
   at MiningCore.Stratum.StratumServer.OnClientConnected(Tcp con, ValueTuple`2 endpointConfig, Loop loop) in C:\Users\Administrator\Desktop\Miningcore_dev_branch\miningcore\src\MiningCore\Stratum\StratumServer.cs:line 163`

### Steps to Reproduce

1. Setup for Ravencoin
2. Connect with miner

### Reproduces how often

100%

### Version

Latest dev, pulled an hour ago. Running on windows server 2016.

### Additional Information

NA

**Comment by Dradden** [comment]
Resolved

**Comment by zheng9980419** [comment]
How?
