### ISSUE TITLE
zcash: Waiting for daemon to connect to peers

### ISSUE THREAD

**Issue by Heraisu** [coinfoundry/miningcore#344]
### Description

MiningCore connects to Zcash node daemon, but does not allow miners to connect as it claims it is still "Waiting for daemons to connect to peers..."   The node is certainly connected to many peers and is synced up to current block, but for some reason MiningCore believes otherwise.

### Steps to Reproduce

1. Install Zcash Node on Ubuntu
2. Wait for Zcash node to sync up.
3. Configure MiningCore pool with rpc info.
4. Connect to zcash node (successful)
5. See MiningCore hanging, believing the node is not connected to peers.

### Expected behavior

I expect MiningCore to let me mine zcash on it.

### Actual behavior

MiningCore waits forever even though nothing else is reporting a problem.

### Reproduces how often

100%

### Version

0.2.4 Release
Windows 10 x64

### Additional Information

I ran with debug logging, but only got the same loop as the console:

```console
[2018-05-23 00:50:10.0373] [I] [zec1] [Bitcoin Job Manager] Waiting for daemons to connect to peers ... 
[2018-05-23 00:50:20.0503] [D] [DaemonClient] ExecuteCmdAnyAsync(getnetworkinfo) 
[2018-05-23 00:50:20.5595] [I] [zec1] [Bitcoin Job Manager] Waiting for daemons to connect to peers ... 
[2018-05-23 00:50:30.5749] [D] [DaemonClient] ExecuteCmdAnyAsync(getnetworkinfo) 
[2018-05-23 00:50:31.0818] [I] [zec1] [Bitcoin Job Manager] Waiting for daemons to connect to peers ... 
[2018-05-23 00:50:41.1017] [D] [DaemonClient] ExecuteCmdAnyAsync(getnetworkinfo) 
[2018-05-23 00:50:41.6127] [I] [zec1] [Bitcoin Job Manager] Waiting for daemons to connect to peers ... 
[2018-05-23 00:50:51.6320] [D] [DaemonClient] ExecuteCmdAnyAsync(getnetworkinfo) 
[2018-05-23 00:50:52.1403] [I] [zec1] [Bitcoin Job Manager] Waiting for daemons to connect to peers ... 
[2018-05-23 00:51:02.1588] [D] [DaemonClient] ExecuteCmdAnyAsync(getnetworkinfo)
```

It can definitely tell when the daemon is offline vs online, so I'm not sure what else to expect from it... is it parsing the daemon's status incorrectly?
I just ran the daemon with -gen=1 to check, and yes the daemon itself will even start mining and complete Equihash solver runs, so it's definitely synced up and networked.

**Comment by Heraisu** [comment]
root@TestMachineName:~# zcash-cli getnetworkinfo
{
  "version": 1010050,
  "subversion": "/MagicBean:1.1.0/",
  "protocolversion": 170005,
  "localservices": "0000000000000005",
  "timeoffset": 0,
  "connections": 1,
  "networks": [
    {
      "name": "ipv4",
      "limited": false,
      "reachable": true,
      "proxy": "",
      "proxy_randomize_credentials": false
    },
    {
      "name": "ipv6",
      "limited": false,
      "reachable": true,
      "proxy": "",
      "proxy_randomize_credentials": false
    },
    {
      "name": "onion",
      "limited": true,
      "reachable": false,
      "proxy": "",
      "proxy_randomize_credentials": false
    }
  ],
  "relayfee": 0.00000100,
  "localaddresses": [
  ],
  "warnings": ""
}

**Comment by Heraisu** [comment]
Additionally, not sure if it's related, but if I set paymentProcessing to true, I get this exception as well:

```
[2018-05-23 01:35:25.4836] [I] [zec2] [Bitcoin Job Manager] All daemons online
[2018-05-23 01:35:25.4836] [E] [PayoutManager] [zec2] Payment processing failed System.NullReferenceException: Object reference not set to an instance of an object.
   at MiningCore.Blockchain.ZCash.ZCashPayoutHandler.<ConfigureAsync>d__9.MoveNext() in C:\Users\Ryan\Documents\GitHub\miningcore\src\MiningCore\Blockchain\ZCash\ZCashPayoutHandler.cs:line 79
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Payments.PayoutManager.<ProcessPoolsAsync>d__11.MoveNext() in C:\Users\Ryan\Documents\GitHub\miningcore\src\MiningCore\Payments\PayoutManager.cs:line 93    at MiningCore.Blockchain.ZCash.ZCashPayoutHandler.<ConfigureAsync>d__9.MoveNext() in C:\Users\Ryan\Documents\GitHub\miningcore\src\MiningCore\Blockchain\ZCash\ZCashPayoutHandler.cs:line 79
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Payments.PayoutManager.<ProcessPoolsAsync>d__11.MoveNext() in C:\Users\Ryan\Documents\GitHub\miningcore\src\MiningCore\Payments\PayoutManager.cs:line 93
[2018-05-23 01:35:25.4957] [D] [DaemonClient] ExecuteCmdAnyAsync(getnetworkinfo)

```

This is specific to ZCash (tried with LTC) and I am using a completely fresh database to test with, same issues.

**Comment by marzhall** [comment]
Had this issue with a litecoin daemon, and ended up tracking this down to not having an `rpcallowip` in the litecoin.conf file for the IP address of the machine I was connecting from. In order to fix it, I figured out what the IP was that the daemon saw me as coming in on*, then added the appropraite `-rpcallowip=<ip address>` line to the daemon's config file in `./litecoin/litecoin.conf`.

 \* I had a weird network setup, so I tried to `ssh` to the daemon's machine with an intentionally faulty password, then checked `/var/log/auth.log/` to see what IP was logged as failing to authenticate.

**Comment by ghost** [comment]
For future references and it seems to issue is never resolved

The info log says that the application can't connect to the daemon. Usually, this means that you've setup wrong ports. Double check your zcash config and the daemon & rpc

I've got the same issue, and resolved this by double-checking all the ports.
