### ISSUE TITLE
API view via HTTP 

### ISSUE THREAD

**Issue by Heraisu** [coinfoundry/miningcore#345]
### Description

As of executing a clean build of release 0.24, I can no longer view the HTTP API pages. I saw some changes were made to make some pages on port 4000 and some (admin) API on 4001, maybe it is related to that?

### Steps to Reproduce

1. Have MiningCore running with one or more pools connected.
2. Browse to any URL.
3. [and so on...]

### Expected behavior

JSON results for API request.

### Actual behavior

Page fails to load and an exception occurs in MiningCore. Exception trace pasted below.

### Reproduces how often

100% of the time, if the configuration is bad, it will remain bad. Using two pools definitely causes this. Using a LTC pool alone for some reason did not.

### Version

Release 24
Windows 10 x64
Chrome browser

### Additional Information

Stack Trace:
```
Mapping types:
PoolConfig -> PoolInfo
MiningCore.Configuration.PoolConfig -> MiningCore.Api.Responses.PoolInfo

Type Map configuration:
PoolConfig -> PoolInfo
MiningCore.Configuration.PoolConfig -> MiningCore.Api.Responses.PoolInfo

Property:
PaymentProcessing ---> AutoMapper.AutoMapperMappingException: Error mapping types.

Mapping types:
PoolPaymentProcessingConfig -> ApiPoolPaymentProcessingConfig
MiningCore.Configuration.PoolPaymentProcessingConfig -> MiningCore.Api.Responses.ApiPoolPaymentProcessingConfig

Type Map configuration:
PoolPaymentProcessingConfig -> ApiPoolPaymentProcessingConfig
MiningCore.Configuration.PoolPaymentProcessingConfig -> MiningCore.Api.Responses.ApiPoolPaymentProcessingConfig

Property:
PayoutSchemeConfig ---> System.ArgumentException: Cannot create an instance of abstract type Newtonsoft.Json.Linq.JToken.
Parameter name: type
   at lambda_method(Closure , PoolConfig , PoolInfo , ResolutionContext )
   --- End of inner exception stack trace ---
   at lambda_method(Closure , PoolConfig , PoolInfo , ResolutionContext )
   --- End of inner exception stack trace ---
   at lambda_method(Closure , PoolConfig , PoolInfo , ResolutionContext )
   at lambda_method(Closure , Object , Object , ResolutionContext )
   at AutoMapper.Mapper.AutoMapper.IMapper.Map[TDestination](Object source)
   at MiningCore.Api.Extensions.MiningPoolExtensions.ToPoolInfo(PoolConfig pool, IMapper mapper, PoolStats stats) in C:\Users\username\Documents\GitHub\miningcore\src\MiningCore\Api\Extensions\MiningPoolExtensions.cs:line 16
   at MiningCore.Api.ApiServer.<GetPoolInfoAsync>d__21.MoveNext() in C:\Users\username\Documents\GitHub\miningcore\src\MiningCore\Api\ApiServer.cs:line 281
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Api.ApiServer.<HandleRequest>d__18.MoveNext() in C:\Users\username\Documents\GitHub\miningcore\src\MiningCore\Api\ApiServer.cs:line 187 AutoMapper.AutoMapperMappingException: Error mapping types.

Mapping types:
PoolConfig -> PoolInfo
MiningCore.Configuration.PoolConfig -> MiningCore.Api.Responses.PoolInfo

Type Map configuration:
PoolConfig -> PoolInfo
MiningCore.Configuration.PoolConfig -> MiningCore.Api.Responses.PoolInfo

Property:
PaymentProcessing ---> AutoMapper.AutoMapperMappingException: Error mapping types.

Mapping types:
PoolPaymentProcessingConfig -> ApiPoolPaymentProcessingConfig
MiningCore.Configuration.PoolPaymentProcessingConfig -> MiningCore.Api.Responses.ApiPoolPaymentProcessingConfig

Type Map configuration:
PoolPaymentProcessingConfig -> ApiPoolPaymentProcessingConfig
MiningCore.Configuration.PoolPaymentProcessingConfig -> MiningCore.Api.Responses.ApiPoolPaymentProcessingConfig

Property:
PayoutSchemeConfig ---> System.ArgumentException: Cannot create an instance of abstract type Newtonsoft.Json.Linq.JToken.
Parameter name: type
   at lambda_method(Closure , PoolConfig , PoolInfo , ResolutionContext )
   --- End of inner exception stack trace ---
   at lambda_method(Closure , PoolConfig , PoolInfo , ResolutionContext )
   --- End of inner exception stack trace ---
   at lambda_method(Closure , PoolConfig , PoolInfo , ResolutionContext )
   at lambda_method(Closure , Object , Object , ResolutionContext )
   at AutoMapper.Mapper.AutoMapper.IMapper.Map[TDestination](Object source)
   at MiningCore.Api.Extensions.MiningPoolExtensions.ToPoolInfo(PoolConfig pool, IMapper mapper, PoolStats stats) in C:\Users\username\Documents\GitHub\miningcore\src\MiningCore\Api\Extensions\MiningPoolExtensions.cs:line 16
   at MiningCore.Api.ApiServer.<GetPoolInfoAsync>d__21.MoveNext() in C:\Users\username\Documents\GitHub\miningcore\src\MiningCore\Api\ApiServer.cs:line 281
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Api.ApiServer.<HandleRequest>d__18.MoveNext() in C:\Users\username\Documents\GitHub\miningcore\src\MiningCore\Api\ApiServer.cs:line 187    at lambda_method(Closure , PoolConfig , PoolInfo , ResolutionContext )
   at lambda_method(Closure , Object , Object , ResolutionContext )
   at MiningCore.Api.Extensions.MiningPoolExtensions.ToPoolInfo(PoolConfig pool, IMapper mapper, PoolStats stats) in C:\Users\username\Documents\GitHub\miningcore\src\MiningCore\Api\Extensions\MiningPoolExtensions.cs:line 16
   at MiningCore.Api.ApiServer.<GetPoolInfoAsync>d__21.MoveNext() in C:\Users\username\Documents\GitHub\miningcore\src\MiningCore\Api\ApiServer.cs:line 281
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Api.ApiServer.<HandleRequest>d__18.MoveNext() in C:\Users\username\Documents\GitHub\miningcore\src\MiningCore\Api\ApiServer.cs:line 187
```

**Comment by oliverw** [comment]
Unable to reproduce.
