### ISSUE TITLE
Slave node in MC Cluster dies once/twice a week

### ISSUE THREAD

**Issue by rymdluo** [coinfoundry/miningcore#348]
### Description

Every 3-4 days a week the "slave" end of the MC cluster dies with the following error message. It appears to be at random and only surety is that it will happen at some point within a week.

### Expected behavior

To stay alive

### Actual behavior

```
6|edge     |
6|edge     | Unhandled Exception: System.InvalidOperationException: Failed to start monitoring system clock changes.
6|edge     |    at System.Reactive.PlatformServices.PeriodicTimerSystemClockMonitor.NewTimer()
6|edge     |    at System.Reactive.PlatformServices.PeriodicTimerSystemClockMonitor.TimeChanged()
6|edge     |    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
6|edge     |    at System.Threading.TimerQueueTimer.CallCallback()
6|edge     |    at System.Threading.TimerQueueTimer.Fire()
6|edge     |    at System.Threading.TimerQueue.FireNextTimers()

/home/monerize-pool/.pm2/logs/edge-out-6.log last 15 lines:
6|edge     |    at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
6|edge     |    at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
6|edge     |    at System.Net.Sockets.Socket.Bind(EndPoint localEP)
6|edge     |    at NetMQ.Core.Transports.Tcp.TcpListener.SetAddress(String addr)
6|edge     |    --- End of inner exception stack trace ---
6|edge     |    at NetMQ.Core.Transports.Tcp.TcpListener.SetAddress(String addr)
6|edge     |    at NetMQ.Core.SocketBase.Bind(String addr)
6|edge     |    at MiningCore.Mining.ShareRelay.Start(ClusterConfig clusterConfig) in /home/user/miningcore-0.24/miningcore-0.24/src/MiningCore/Mining/ShareRelay.cs:line 62
6|edge     |    at MiningCore.Program.<Start>d__31.MoveNext() in /home/user/miningcore-0.24/miningcore-0.24/src/MiningCore/Program.cs:line 579<---
6|edge     |
6|edge     | Cluster cannot start. Good Bye!
6|edge     | [2018-05-30 15:17:56.6856] [I] [Program] Shutdown ...
6|edge     | Shutdown...
6|edge     | [2018-05-30 15:17:56.6856] [I] [ShareRelay] Stopping ..
6|edge     | [2018-05-30 15:17:56.6887] [I] [ShareRelay] Stopped
```

### Reproduces how often

About once or twice a week

**Comment by oliverw** [comment]
Might disappear after the ongoing migration to .NETCore 2.1

**Comment by oliverw** [comment]
This appears to be a rather complex problem to solve: https://github.com/dotnet/reactive/issues/270

**Comment by oliverw** [comment]
Unable to reproducce with latest codebase.
