### ISSUE TITLE
Payout issue

### ISSUE THREAD

**Issue by Jlonghi** [coinfoundry/miningcore#350]
### Description

Everything is working fine on the ethereum Ropsten testnet except for payouts. The first payout worked successfully and the second one and every single one after threw this:
```
[2018-05-30 19:55:28.9574] [E] [PayoutManager] [eth1] Payment processing failed System.InvalidOperationException: This NpgsqlTransaction has completed; it is no longer usable.
   at Npgsql.NpgsqlTransaction.CheckCompleted()
   at Npgsql.NpgsqlTransaction.<Rollback>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlTransaction.Rollback()
   at MiningCore.Extensions.ConnectionFactoryExtensions.<RunTxAsync>d__8.MoveNext() in /tmp/miningcore/src/MiningCore/Extensions/ConnectionFactoryExtensions.cs:line 221
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Payments.PayoutManager.<UpdatePoolBalancesAsync>d__12.MoveNext() in /tmp/miningcore/src/MiningCore/Payments/PayoutManager.cs:line 121
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Payments.PayoutManager.<ProcessPoolsAsync>d__11.MoveNext() in /tmp/miningcore/src/MiningCore/Payments/PayoutManager.cs:line 95    at Npgsql.NpgsqlTransaction.CheckCompleted()
   at Npgsql.NpgsqlTransaction.<Rollback>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlTransaction.Rollback()
   at MiningCore.Extensions.ConnectionFactoryExtensions.<RunTxAsync>d__8.MoveNext() in /tmp/miningcore/src/MiningCore/Extensions/ConnectionFactoryExtensions.cs:line 221
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Payments.PayoutManager.<UpdatePoolBalancesAsync>d__12.MoveNext() in /tmp/miningcore/src/MiningCore/Payments/PayoutManager.cs:line 121
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Payments.PayoutManager.<ProcessPoolsAsync>d__11.MoveNext() in /tmp/miningcore/src/MiningCore/Payments/PayoutManager.cs:line 95
```

### Expected behavior

Payouts to succeed

### Actual behavior

exception pasted above is thrown

### Reproduces how often

Every payout

### Version

Master branch

**Comment by Jlonghi** [comment]
Switching to the dev branch commit 3a69f27bde7fe6f95ba9d82ec7a12128a56ee3f8 and this solved my issue.

**Comment by Jlonghi** [comment]
Failed on an uncle block. I have keep uncles: false

**Comment by Jlonghi** [comment]
Some more information:
```
[2018-06-01 15:25:34.0205] [I] [eth1] [Ethereum Payout Handler] Unlocked block 3353885 worth 3.00058 ETH 
[2018-06-01 15:25:34.1648] [I] [eth1] [Ethereum Payout Handler] Fetching 1 uncles for block 3353840 
[2018-06-01 15:25:34.1659] [I] [eth1] [Ethereum Payout Handler] Fetched 1 uncles for block 3353840 
[2018-06-01 15:25:34.1659] [I] [eth1] [Ethereum Payout Handler] Fetching 1 uncles for block 3353866 
[2018-06-01 15:25:34.1659] [I] [eth1] [Ethereum Payout Handler] Fetched 1 uncles for block 3353866 
[2018-06-01 15:25:34.1659] [I] [eth1] [Ethereum Payout Handler] Unlocked uncle for block 3353866 at height 3353863 worth 1.875 ETH 
[2018-06-01 15:25:34.1659] [I] [eth1] [Ethereum Payout Handler] Fetching 1 uncles for block 3353866 
[2018-06-01 15:25:34.1659] [I] [eth1] [Ethereum Payout Handler] Fetched 1 uncles for block 3353866 
[2018-06-01 15:25:34.1659] [I] [eth1] [Ethereum Payout Handler] Unlocked uncle for block 3353866 at height 3353863 worth 1.875 ETH 
[2018-06-01 15:25:34.1716] [I] [PayoutManager] Processing payments for pool eth1, block 3353810 
[2018-06-01 15:25:34.2483] [I] [PPLNS Payment] Fetching page 0 of shares for pool eth1, block 3353810 
[2018-06-01 15:25:34.2791] [I] [PPLNS Payment] Balance-calculation for pool eth1, block 3353810 completed with accumulated score 2 (100%) 
[2018-06-01 15:25:34.2791] [I] [PPLNS Payment] Adding 2.6225 ETH to balance of 0xb9b90cdc6a0cab4b5fb4eadc632a78710761b860 for 10.69 G (10687359694.1834) shares for block 3353810 
[2018-06-01 15:25:34.3200] [I] [PPLNS Payment] 10.69 G (10687359694.18) shares contributed to a total payout of 2.6225 ETH (100.00% of block reward) to 1 addresses 
[2018-06-01 15:25:34.3544] [E] [PayoutManager] [eth1] Payment processing failed System.InvalidOperationException: This NpgsqlTransaction has completed; it is no longer usable.
   at Npgsql.NpgsqlTransaction.CheckCompleted()
   at Npgsql.NpgsqlTransaction.Rollback(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlTransaction.Rollback()
   at MiningCore.Extensions.ConnectionFactoryExtensions.RunTxAsync(IConnectionFactory factory, Func`3 action, Boolean autoCommit, IsolationLevel isolation) in /tmp/miningcore/src/MiningCore/Extensions/ConnectionFactoryExtensions.cs:line 221
   at MiningCore.Payments.PayoutManager.UpdatePoolBalancesAsync(PoolConfig pool, IPayoutHandler handler, IPayoutScheme scheme) in /tmp/miningcore/src/MiningCore/Payments/PayoutManager.cs:line 123
   at MiningCore.Payments.PayoutManager.ProcessPoolsAsync() in /tmp/miningcore/src/MiningCore/Payments/PayoutManager.cs:line 97    at Npgsql.NpgsqlTransaction.CheckCompleted()
   at Npgsql.NpgsqlTransaction.Rollback(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlTransaction.Rollback()
   at MiningCore.Extensions.ConnectionFactoryExtensions.RunTxAsync(IConnectionFactory factory, Func`3 action, Boolean autoCommit, IsolationLevel isolation) in /tmp/miningcore/src/MiningCore/Extensions/ConnectionFactoryExtensions.cs:line 221
   at MiningCore.Payments.PayoutManager.UpdatePoolBalancesAsync(PoolConfig pool, IPayoutHandler handler, IPayoutScheme scheme) in /tmp/miningcore/src/MiningCore/Payments/PayoutManager.cs:line 123
   at MiningCore.Payments.PayoutManager.ProcessPoolsAsync() in /tmp/miningcore/src/MiningCore/Payments/PayoutManager.cs:line 97
```

**Comment by Konstantin35** [comment]
show parity settings

**Comment by Jlonghi** [comment]
Running in docker. Config file has chains=ropsten and the author address.
```
docker run -d -p 8185:8180 -p 8550:8545 -p 8551:8546 -p 30308:30303 -p 30308:30303/udp -v ~/eth-test-pass.txt:/root/pass.txt -v ~/.local/share/io.parity.ethereum/docker/:/root/.local/share/io.parity.ethereum/ --name eth-node-testnet -t parity/parity:stable --config /root/.local/share/io.parity.ethereum/config.toml --mode active --no-ui --no-dapps --no-ipc --jsonrpc-interface "0.0.0.0" --jsonrpc-threads 4 --jsonrpc-port 8545 --no-discovery --jsonrpc-apis "eth,net,web3,personal,parity,parity_pubsub,rpc" --cache-size 512 --logging info --ws-port 8546 --ws-interface all --base-path /root/.local/share/io.parity.ethereum/data --allow-ips all --jsonrpc-hosts all  --db-compaction ssd --pruning fast --tracing off --unlock "0xacdc683aff5c7ef26e0565ea719bb7ac7da4ebee"  --password /root/pass.txt
```

**Comment by Konstantin35** [comment]
remove
`--unlock "0xacdc683aff5c7ef26e0565ea719bb7ac7da4ebee" --password /root/pass.txt`

add to miningcore settings
"daemons": [
            {
                "host": "127.0.0.1",
                "port": 8550,
                "user": "",
                "password": "",
               **"portWs": 8546**
  }
]

**Comment by Jlonghi** [comment]
Thanks for the reply. Ill give that a shot

**Comment by Jlonghi** [comment]
Didn't fix it unfortunately. Still had the exception thrown on the second uncle block this time.

**Comment by Konstantin35** [comment]
Here are my settings on ELLA
`parity --chain ellaism --no-discovery --no-ui --no-dapps --no-ipc --jsonrpc-interface 127.0.0.1 --jsonrpc-threads 4 --jsonrpc-port 8545 --jsonrpc-apis eth,net,web3,personal,parity,parity_pubsub,rpc --author 0x8b51127a10cec5ee67d52bda182c3e7c7922e27b --cache-size 512 --logging info --ws-port 18545 --ws-interface all`
everything works as it should

**Comment by Jlonghi** [comment]
Must be the ropsten testnet then.. I have everything the same as you.

**Comment by Jlonghi** [comment]
@Konstantin35 One more thing.. Do you know why parity says 
```
2018-06-04 18:05:49 UTC Imported #5936022 e3f3…0f42 (17 txs, 0.43 Mgas, 5.11 ms, 2.76 KiB)
2018-06-04 18:05:51 UTC Imported #5936021 4537…17bb (3 txs, 0.06 Mgas, 1.50 ms, 0.88 KiB)
```
And other times it will say
```
2018-06-04 17:01:40 UTC Syncing #5935755 14ba…daef     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #5935756    6/100 peers   261 MiB chain 70 MiB db 0 bytes queue 14 MiB sync  RPC:  0 conn,  2 req/s, 7536 µs
```

**Comment by Jlonghi** [comment]
Actually after running ellasim for awhile i ended up running into that error. I added some debugging and narrowed down what it was doing.
On Ropsten I found this
```
[2018-06-13 17:37:39.7637] [I] [BlockRepository] block attributes: Id 4043, poolId ropst-test, BlockHeight 3429202, status Confirmed, type uncle, reward 1.5, reward 1.5, effort , Confirmationprogress 1 
[2018-06-13 17:37:39.7839] [I] [BlockRepository] block attributes: Id 4044, poolId ropst-test, BlockHeight 3429202, status Confirmed, type uncle, reward 1.5, reward 1.5, effort , Confirmationprogress 1 
```
It would update one block (id 4043) then try to update block id 4044 but the block height already exists. This would cause the exception to be throw. For some reason my parity is giving two uncle blocks?

**Comment by calvintam236** [comment]
Maybe @oliverw can give an insight?

**Comment by oliverw** [comment]
Support for this coin has been dropped a long time ago. Closing.

**Comment by Jlonghi** [comment]
Thanks
