### ISSUE TITLE
pool with zcash config cannot run.

### ISSUE THREAD

**Issue by yyyfor** [coinfoundry/miningcore#368]
### Description

cannot run pool using zcash config.

### Steps to Reproduce

1. followed all the instruction, downloaded and built the project
2. change the address in the zcash config file
3. run "dotnet MiningCore.dll -c zcash.json"

### Expected behavior

pool starts to run

### Actual behavior

error log appears

### Reproduces how often

every time

### Version
latest 
Ubuntu 16.04

### Additional Information

here is the error log:
```console
[2018-07-02 13:00:57.5894] [E] [PayoutManager] [zec1] Payment processing failed System.Net.Http.HttpRequestException: Connection refused ---> System.Net.Sockets.SocketException: Connection refused
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at MiningCore.DaemonInterface.DaemonClient.BuildRequestTask(DaemonEndpointConfig endPoint, String method, Object payload, JsonSerializerSettings payloadJsonSerializerSettings) in /home/siming/miningcore/src/MiningCore/DaemonInterface/DaemonClient.cs:line 286
   at MiningCore.DaemonInterface.DaemonClient.ExecuteCmdSingleAsync[TResponse](String method, Object payload, JsonSerializerSettings payloadJsonSerializerSettings) in /home/siming/miningcore/src/MiningCore/DaemonInterface/DaemonClient.cs:line 204
   at MiningCore.Blockchain.ZCash.ZCashPayoutHandler.ConfigureAsync(ClusterConfig clusterConfig, PoolConfig poolConfig) in /home/siming/miningcore/src/MiningCore/Blockchain/ZCash/ZCashPayoutHandler.cs:line 79
   at MiningCore.Payments.PayoutManager.ProcessPoolsAsync() in /home/siming/miningcore/src/MiningCore/Payments/PayoutManager.cs:line 93    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at MiningCore.DaemonInterface.DaemonClient.BuildRequestTask(DaemonEndpointConfig endPoint, String method, Object payload, JsonSerializerSettings payloadJsonSerializerSettings) in /home/siming/miningcore/src/MiningCore/DaemonInterface/DaemonClient.cs:line 286
   at MiningCore.DaemonInterface.DaemonClient.ExecuteCmdSingleAsync[TResponse](String method, Object payload, JsonSerializerSettings payloadJsonSerializerSettings) in /home/siming/miningcore/src/MiningCore/DaemonInterface/DaemonClient.cs:line 204
   at MiningCore.Blockchain.ZCash.ZCashPayoutHandler.ConfigureAsync(ClusterConfig clusterConfig, PoolConfig poolConfig) in /home/siming/miningcore/src/MiningCore/Blockchain/ZCash/ZCashPayoutHandler.cs:line 79
   at MiningCore.Payments.PayoutManager.ProcessPoolsAsync() in /home/siming/miningcore/src/MiningCore/Payments/PayoutManager.cs:line 93
[2018-07-02 13:00:57.8498] [I] [zec1] [Bitcoin Job Manager] Waiting for daemons to come online ...
[2018-07-02 13:01:07.8401] [I] [StatsRecorder] Updating hashrates for pool zec1
[2018-07-02 13:01:07.8508] [I] [zec1] [Bitcoin Job Manager] Waiting for daemons to come online ...
[2018-07-02 13:01:17.8558] [I] [zec1] [Bitcoin Job Manager] Waiting for daemons to come online ...
```

**Comment by yyyfor** [comment]
I believe zcash testnet daemon is running

**Comment by calvintam236** [comment]
Are you running on release 24 of miningcore? What is your version of `zcashd`?

**Comment by yyyfor** [comment]
@calvintam236 

yea, miningcore version is 0.24 and zcashd version is 1.1.1.

**Comment by oliverw** [comment]
The daemon is clearly not reachable according to the stacktrace you've posted.
