### ISSUE TITLE
No reward-recipients error

### ISSUE THREAD

**Issue by duyvu1311** [coinfoundry/miningcore#370]
Hi, guys!
Could you please tell me what caused this error:
`[2018-07-18 05:26:36.1469] [I] [PayoutManager] Processing payments for pool ella_solo, block 1891749 
[2018-07-18 05:26:36.1469] [I] [ella_solo] Adding 0.075 ELLA to balance of 0x4a2df392bbc02d5dcee2f512df8691738df29538 
[2018-07-18 05:26:36.1536] [E] [PayoutManager] [ella_solo] Payment processing failed System.Exception: No reward-recipients of type = 'solo' configured
   at MiningCore.Payments.PaymentSchemes.SoloPaymentScheme.CalculateRewards(PoolConfig poolConfig, Block block, Decimal blockReward, Dictionary'2 rewards) in /home/duyvu1311/miningcore/src/MiningCore/Payments/PaymentSchemes/SoloPaymentScheme.cs:line 116
   at MiningCore.Payments.PaymentSchemes.SoloPaymentScheme.UpdateBalancesAsync(IDbConnection con, IDbTransaction tx, PoolConfig poolConfig, IPayoutHandler payoutHandler, Block block, Decimal blockReward) in /home/duyvu1311/miningcore/src/MiningCore/Payments/PaymentSchemes/SoloPaymentScheme.cs:line 75
   at MiningCore.Payments.PayoutManager.<>c__DisplayClass12_1.<<UpdatePoolBalancesAsync>b__4>d.MoveNext() in /home/duyvu1311/miningcore/src/MiningCore/Payments/PayoutManager.cs:line 141
--- End of stack trace from previous location where exception was thrown ---
   at MiningCore.Extensions.ConnectionFactoryExtensions.RunTxAsync(IConnectionFactory factory, Func'3 action, Boolean autoCommit, IsolationLevel isolation) in /home/duyvu1311/miningcore/src/MiningCore/Extensions/ConnectionFactoryExtensions.cs:line 214
   at MiningCore.Payments.PayoutManager.UpdatePoolBalancesAsync(PoolConfig pool, IPayoutHandler handler, IPayoutScheme scheme) in /home/duyvu1311/miningcore/src/MiningCore/Payments/PayoutManager.cs:line 123
   at MiningCore.Payments.PayoutManager.ProcessPoolsAsync() in /home/duyvu1311/miningcore/src/MiningCore/Payments/PayoutManager.cs:line 97    at MiningCore.Payments.PaymentSchemes.SoloPaymentScheme.CalculateRewards(PoolConfig poolConfig, Block block, Decimal blockReward, Dictionary'2 rewards) in /home/duyvu1311/miningcore/src/MiningCore/Payments/PaymentSchemes/SoloPaymentScheme.cs:line 116
   at MiningCore.Payments.PaymentSchemes.SoloPaymentScheme.UpdateBalancesAsync(IDbConnection con, IDbTransaction tx, PoolConfig poolConfig, IPayoutHandler payoutHandler, Block block, Decimal blockReward) in /home/duyvu1311/miningcore/src/MiningCore/Payments/PaymentSchemes/SoloPaymentScheme.cs:line 75
   at MiningCore.Payments.PayoutManager.<>c__DisplayClass12_1.<<UpdatePoolBalancesAsync>b__4>d.MoveNext() in /home/duyvu1311/miningcore/src/MiningCore/Payments/PayoutManager.cs:line 141
--- End of stack trace from previous location where exception was thrown ---
   at MiningCore.Extensions.ConnectionFactoryExtensions.RunTxAsync(IConnectionFactory factory, Func'3 action, Boolean autoCommit, IsolationLevel isolation) in /home/duyvu1311/miningcore/src/MiningCore/Extensions/ConnectionFactoryExtensions.cs:line 214
   at MiningCore.Payments.PayoutManager.UpdatePoolBalancesAsync(PoolConfig pool, IPayoutHandler handler, IPayoutScheme scheme) in /home/duyvu1311/miningcore/src/MiningCore/Payments/PayoutManager.cs:line 123
   at MiningCore.Payments.PayoutManager.ProcessPoolsAsync() in /home/duyvu1311/miningcore/src/MiningCore/Payments/PayoutManager.cs:line 97
`
**This is my config.json for this pool:**
{
	      "id": "ella_solo",
	      "enabled": true,
	      "coin": {
	        "type": "ELLA"
	      },
	      "dagDir": "/home/duyvu1311/.ethash/dag/ella",
	      "address": "0xc27cc069b23c27c93b0cacbd626fc5d05ca5****",
	      "rewardRecipients": [
	        {
	          "address": "0x4a2df392bbc02d5dcee2f512df8691738df2****",
	          "percentage": 1.5
	        }
	      ],
	      "blockRefreshInterval": 400,
	      "jobRebroadcastTimeout": 10,
	      "clientConnectionTimeout": 600,
	      "banning": {
	        "enabled": true,
	        "time": 600,
	        "invalidPercent": 50,
	        "checkThreshold": 50
	      },
	      "ports": {
	        "60110": {
	          "listenAddress": "0.0.0.0",
	          "difficulty": 0.5,
	          "varDiff": {
	            "minDiff": 0.5,
	            "maxDiff": null,
	            "targetTime": 15,
	            "retargetTime": 90,
	            "variancePercent": 30,
	            "maxDelta": 500
	          }
	        }
	      },
	      "daemons": [ 
		        {
		          "host": "127.0.0.1",
		          "port": 60101,
		          "user": "",
		          "password": "",
		          "zmqBlockNotifySocket": "tcp://127.0.0.1:60102",
		          "portWs": 60103
		        }
	      ],
               ...
	    }

Thank you!

**Comment by duyvu1311** [comment]
After 2 days reading code, The error has resolved
