### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by zheng9980419** [coinfoundry/miningcore#387]
[2018-09-10 17:24:36.5098] [I] [Program] .NET Core 4.6.00001.0 on Linux 4.4.0-134-generic #160-Ubuntu SMP Wed Aug 15 14:58:00 UTC 2018 [X64]
[2018-09-10 17:24:36.6891] [I] [ShareRecorder] Online
[2018-09-10 17:24:36.6986] [I] [ApiServer] Launching ...
[2018-09-10 17:24:36.9620] [I] [ApiServer] API Online @ 127.0.0.1:4000
[2018-09-10 17:24:36.9663] [I] [ApiServer] Admin API Online @ 127.0.0.1:4001
[2018-09-10 17:24:36.9733] [I] [PayoutManager] Online
[2018-09-10 17:24:36.9733] [I] [StatsRecorder] Online
[2018-09-10 17:24:36.9802] [I] [PayoutManager] Processing payments for pool etc1
[2018-09-10 17:24:37.0536] [I] [etc1] [Pool] Launching ...
[2018-09-10 17:24:37.0766] [I] [etc1] [Ethereum Job Manager] Launching ...
[2018-09-10 17:24:37.1412] [I] [etc1] [Ethereum Job Manager] All daemons online
[2018-09-10 17:24:37.1693] [I] [etc1] [Ethereum Job Manager] All daemons synched with blockchain
[2018-09-10 17:24:37.2465] [E] [etc1] System.NullReferenceException: Object reference not set to an instance of an object.
   at MiningCore.Blockchain.Ethereum.EthereumJobManager.<GetBlockTemplateAsync>d__15.MoveNext() in /home/pool/miningcore/src/MiningCore/Blockchain/Ethereum/EthereumJobManager.cs:line 183
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Ethereum.EthereumJobManager.<PostStartInitAsync>d__39.MoveNext() in /home/pool/miningcore/src/MiningCore/Blockchain/Ethereum/EthereumJobManager.cs:line 573
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.JobManagerBase`1.<StartAsync>d__23.MoveNext() in /home/pool/miningcore/src/MiningCore/Blockchain/JobManagerBase.cs:line 210
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Ethereum.EthereumPool.<SetupJobManager>d__8.MoveNext() in /home/pool/miningcore/src/MiningCore/Blockchain/Ethereum/EthereumPool.cs:line 278
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Mining.PoolBase.<StartAsync>d__40.MoveNext() in /home/pool/miningcore/src/MiningCore/Mining/PoolBase.cs:line 352 System.NullReferenceException: Object reference not set to an instance of an object.
   at MiningCore.Blockchain.Ethereum.EthereumJobManager.<GetBlockTemplateAsync>d__15.MoveNext() in /home/pool/miningcore/src/MiningCore/Blockchain/Ethereum/EthereumJobManager.cs:line 183
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Ethereum.EthereumJobManager.<PostStartInitAsync>d__39.MoveNext() in /home/pool/miningcore/src/MiningCore/Blockchain/Ethereum/EthereumJobManager.cs:line 573
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.JobManagerBase`1.<StartAsync>d__23.MoveNext() in /home/pool/miningcore/src/MiningCore/Blockchain/JobManagerBase.cs:line 210
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Ethereum.EthereumPool.<SetupJobManager>d__8.MoveNext() in /home/pool/miningcore/src/MiningCore/Blockchain/Ethereum/EthereumPool.cs:line 278
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Mining.PoolBase.<StartAsync>d__40.MoveNext() in /home/pool/miningcore/src/MiningCore/Mining/PoolBase.cs:line 352    at MiningCore.Blockchain.Ethereum.EthereumJobManager.<GetBlockTemplateAsync>d__15.MoveNext() in /home/pool/miningcore/src/MiningCore/Blockchain/Ethereum/EthereumJobManager.cs:line 183
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Ethereum.EthereumJobManager.<PostStartInitAsync>d__39.MoveNext() in /home/pool/miningcore/src/MiningCore/Blockchain/Ethereum/EthereumJobManager.cs:line 573
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.JobManagerBase`1.<StartAsync>d__23.MoveNext() in /home/pool/miningcore/src/MiningCore/Blockchain/JobManagerBase.cs:line 210
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Ethereum.EthereumPool.<SetupJobManager>d__8.MoveNext() in /home/pool/miningcore/src/MiningCore/Blockchain/Ethereum/EthereumPool.cs:line 278
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Mining.PoolBase.<StartAsync>d__40.MoveNext() in /home/pool/miningcore/src/MiningCore/Mining/PoolBase.cs:line 352

**Comment by Konstantin35** [comment]
Use version 1.9.5 of parity 
https://github.com/paritytech/parity-ethereum/releases/tag/v1.9.5

**Comment by zheng9980419** [comment]
@Konstantin35 
0/25 peers   8 KiB chain 3 MiB db 0 bytes queue 11 KiB sync  RPC:  0 conn,  0 req/s, 200 µs
2018-09-11 07:39:02     0/25 peers   8 KiB chain 3 MiB db 0 bytes queue 11 KiB sync  RPC:  0 conn,  1 req/s, 200 µs
2018-09-11 07:39:32     0/25 peers   8 KiB chain 3 MiB db 0 bytes queue 11 KiB sync  RPC:  0 conn,  0 req/s, 200 µs
2018-09-11 07:40:02     0/25 peers   8 KiB chain 3 MiB db 0 bytes queue 11 KiB sync  RPC:  0 conn,  0 req/s, 200 µs
2018-09-11 07:40:37     0/25 peers   8 KiB chain 3 MiB db 0 bytes queue 11 KiB sync  RPC:  0 conn,  0 req/s, 200 µs
2018-09-11 07:41:07     0/25 peers   8 KiB chain 3 MiB db 0 bytes queue 11 KiB sync  RPC:  0 conn,  0 req/s, 200 µs
2018-09-11 07:41:37     0/25 peers   8 KiB chain 3 MiB db 0 bytes queue 11 KiB sync  RPC:  0 conn,  0 req/s, 200 µs
2018-09-11 07:42:07     0/25 peers   8 KiB chain 3 MiB db 0 bytes queue 11 KiB sync  RPC:  0 conn,  0 req/s, 200 µs
2018-09-11 07:42:37     0/25 peers   8 KiB chain 3 MiB db 0 bytes queue 11 KiB sync  RPC:  0 conn,  0 req/s, 200 µs
2018-09-11 07:43:07     0/25 peers   8 KiB chain 3 MiB db 0 bytes queue 11 KiB sync  RPC:  0 conn,  0 req/s, 200 µs
2018-09-11 07:43:37     0/25 peers   8 KiB chain 3 MiB db 0 bytes queue 11 KiB sync  RPC:  0 conn,  0 req/s, 200 µs
2018-09-11 07:44:07     0/25 peers   8 KiB chain 3 MiB db 0 bytes queue 11 KiB sync  RPC:  0 conn,  0 req/s, 200 µs
2018-09-11 07:44:37     0/25 peers   8 KiB chain 3 MiB db 0 bytes queue 11 KiB sync  RPC:  0 conn,  0 req/s, 200 µs
2018-09-11 07:45:07     0/25 peers   8 KiB chain 3 MiB db 0 bytes queue 11 KiB sync  RPC:  0 conn,  0 req/s, 200 µs
2018-09-11 07:45:37     0/25 peers   8 KiB chain 3 MiB db 0 bytes queue 11 KiB sync  RPC:  0 conn,  0 req/s, 200 µs
2018-09-11 07:46:07     0/25 peers   8 KiB chain 3 MiB db 0 bytes queue 11 KiB sync  RPC:  0 conn,  0 req/s, 200 µs
2018-09-11 07:46:37     0/25 peers   8 KiB chain 3 MiB db 0 bytes queue 11 KiB sync  RPC:  0 conn,  0 req/s, 200 µs
2018-09-11 07:47:07     0/25 peers   8 KiB chain 3 MiB db 0 bytes queue 11 KiB sync  RPC:  0 conn,  0 req/s, 200 µs
2018-09-11 07:47:37     0/25 peers   8 KiB chain 3 MiB db 0 bytes queue 11 KiB sync  RPC:  0 conn,  0 req/s, 200 µs
2018-09-11 07:48:07     0/25 peers   8 KiB chain 3 MiB db 0 bytes queue 11 KiB sync  RPC:  0 conn,  0 req/s, 200 µs
2018-09-11 07:48:37     0/25 peers   8 KiB chain 3 MiB db 0 bytes queue 11 KiB sync  RPC:  0 conn,  0 req/s, 200 µs
2018-09-11 07:49:07     0/25 peers   8 KiB chain 3 MiB db 0 bytes queue 11 KiB sync  RPC:  0 conn,  0 req/s, 200 µs
2018-09-11 07:49:37     0/25 peers   8 KiB chain 3 MiB db 0 bytes queue 11 KiB sync  RPC:  0 conn,  0 req/s, 200 µs
2018-09-11 07:50:07     0/25 peers   8 KiB chain 3 MiB db 0 bytes queue 11 KiB sync  RPC:  0 conn,  0 req/s, 200 µs
2018-09-11 07:50:37     0/25 peers   8 KiB chain 3 MiB db 0 bytes queue 11 KiB sync  RPC:  0 conn,  0 req/s, 200 µs
2018-09-11 07:51:07     0/25 peers   8 KiB chain 3 MiB db 0 bytes queue 11 KiB sync  RPC:  0 conn,  0 req/s, 200 µs

**Comment by calvintam236** [comment]
Please use the following format to file an issue. Thank you for your cooperation.

### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior

[What you expect to happen]

### Actual behavior

[What actually happens]

### Reproduces how often

[What percentage of the time does it reproduce?]

### Version

If you are using released version, please state your version.
If you are using clone from `dev` branch, please state commit hash of your copy.
Also, please include the OS name and version you're currently running.

### Additional Information

Any additional information, log, configuration or data that might be necessary to reproduce the issue.
