### ISSUE TITLE
[ETH] Job manager broadcast spams new blocks on mainnet

### ISSUE THREAD

**Issue by mvilera** [coinfoundry/miningcore#392]
### Description

When running an ETH pool using MiningCore version v26 and Parity 1.11.11 the daemon keeps spamming new jobs using same old blocks, running on a docker swarm.

### Steps to Reproduce

Just run the pool normally.

### Expected behavior

Jobs being broadcasted according to new blocks founds on the main net.

### Actual behavior

Jobs broadcasts is spammed using old blocks.

### Reproduces how often

100% using Parity 1.11.11 haven't tested other versions.

### Version

Ubuntu 16.04.4
Parity 1.11.11
MiningCore release v26
Docker 18.04

### Additional Information

MiningCore config
```
{
    "logging": {
        "level": "info",
        "enableConsoleLog": true,
        "enableConsoleColors": true,
        "logFile": "",
        "logBaseDirectory": "",
        "perPoolLogFile": false
    },
    "banning": {
        "manager": "integrated",
        "banOnJunkReceive": true,
        "banOnInvalidShares": false
    },
    "api": {
        "listenAddress": "0.0.0.0"
    },
    "notifications": {
        "enabled": false,
        "email": {
            "host": "smtp.example.com",
            "port": 587,
            "user": "user",
            "password": "password",
            "fromAddress": "info@yourpool.org",
            "fromName": "support"
        },
        "admin": {
            "enabled": false,
            "emailAddress": "user@example.com",
            "notifyBlockFound": true
        }
    },
    "persistence": {
        "postgres": {
            "host": "database",
            "port": 5432,
            "user": "miningcore",
            "password": "miningcore",
            "database": "miningcore"
        }
    },
    "paymentProcessing": {
        "enabled": true,
        "interval": 600,
        "shareRecoveryFile": "/pool-data/recovered-shares.txt"
    },
    "pools": [
        {
            "id": "eth1",
            "enabled": true,
            "coin": {
                "type": "ETH"
            },
            "address": "0x5deec37b4b2a427190faed24bfdb008a6c113aa8",
            "rewardRecipients": [
                {
                    "type": "op",
                    "address": "0x5deec37b4b2a427190faed24bfdb008a6c113aa8",
                    "percentage": 0
                }
            ],
            "dagDir": "/pool-data",
            "blockRefreshInterval": 120,
            "clientConnectionTimeout": 600,
            "jobRebroadcastTimeout": 0,
            "banning": {
                "enabled": true,
                "time": 600,
                "invalidPercent": 50,
                "checkThreshold": 50
            },
            "ports": {
                "8008": {
                    "difficulty": 0.1,
                    "varDiff": {
                        "minDiff": 0.05,
                        "maxDiff": null,
                        "targetTime": 15,
                        "retargetTime": 90,
                        "variancePercent": 30
                    }
                }
            },
            "daemons": [
                {
                    "host": "blockchain-master",
                    "port": 8545,
                    "user": "user",
                    "password": "pass"
                },
                {
                    "host": "blockchain-backup",
                    "port": 8545,
                    "user": "user",
                    "password": "pass"
                }
            ],
            "paymentProcessing": {
                "enabled": true,
                "minimumPayment": 0.01,
                "minimumPaymentToPaymentId": 5,
                "payoutScheme": "PPLNS",
                "payoutSchemeConfig": {
                    "factor": 2
                },
                "keepUncles": false,
                "keepTransactionFees": false
            }
        }
    ]
}
```

Parity config
```
--jsonrpc-interface all --jsonrpc-threads 4 --cache-size 512 --logging "info" --no-discovery --author "0x5deec37b4b2a427190faed24bfdb008a6c113aa8" --ws-port 18545 --ws-interface all --jsonrpc-apis "eth,net,web3,personal,parity,parity_pubsub,rpc"
```
Log
```
ethereum-pool_master-node.1.c14naso5tvgc@db-node-1    | [2018-09-16 05:20:41.1278] [I] [eth1] [Ethereum Job Manager] New block 6340462 detected 
ethereum-pool_master-node.1.c14naso5tvgc@db-node-1    | [2018-09-16 05:20:41.1278] [I] [eth1] [Pool] Broadcasting job 
ethereum-pool_master-node.1.c14naso5tvgc@db-node-1    | [2018-09-16 05:20:41.2481] [I] [eth1] [Ethereum Job Manager] New block 6340462 detected 
ethereum-pool_master-node.1.c14naso5tvgc@db-node-1    | [2018-09-16 05:20:41.2481] [I] [eth1] [Pool] Broadcasting job 
ethereum-pool_master-node.1.c14naso5tvgc@db-node-1    | [2018-09-16 05:20:41.4888] [I] [eth1] [Ethereum Job Manager] New block 6340462 detected 
ethereum-pool_master-node.1.c14naso5tvgc@db-node-1    | [2018-09-16 05:20:41.4888] [I] [eth1] [Pool] Broadcasting job 
ethereum-pool_master-node.1.c14naso5tvgc@db-node-1    | [2018-09-16 05:20:42.1813] [I] [eth1] [Ethereum Job Manager] New block 6340462 detected 
ethereum-pool_master-node.1.c14naso5tvgc@db-node-1    | [2018-09-16 05:20:42.1813] [I] [eth1] [Pool] Broadcasting job 
ethereum-pool_master-node.1.c14naso5tvgc@db-node-1    | [2018-09-16 05:20:42.9284] [I] [eth1] [Ethereum Job Manager] New block 6340462 detected 
ethereum-pool_master-node.1.c14naso5tvgc@db-node-1    | [2018-09-16 05:20:42.9284] [I] [eth1] [Pool] Broadcasting job 
ethereum-pool_master-node.1.c14naso5tvgc@db-node-1    | [2018-09-16 05:20:43.0486] [I] [eth1] [Ethereum Job Manager] New block 6340462 detected 
ethereum-pool_master-node.1.c14naso5tvgc@db-node-1    | [2018-09-16 05:20:43.0486] [I] [eth1] [Pool] Broadcasting job 
ethereum-pool_master-node.1.c14naso5tvgc@db-node-1    | [2018-09-16 05:20:43.1691] [I] [eth1] [Ethereum Job Manager] New block 6340462 detected 
ethereum-pool_master-node.1.c14naso5tvgc@db-node-1    | [2018-09-16 05:20:43.1691] [I] [eth1] [Pool] Broadcasting job 
ethereum-pool_master-node.1.c14naso5tvgc@db-node-1    | [2018-09-16 05:20:43.2896] [I] [eth1] [Ethereum Job Manager] New block 6340463 detected 
ethereum-pool_master-node.1.c14naso5tvgc@db-node-1    | [2018-09-16 05:20:43.2896] [I] [eth1] [Pool] Broadcasting job 
ethereum-pool_master-node.1.c14naso5tvgc@db-node-1    | [2018-09-16 05:20:43.8868] [I] [eth1] [Ethereum Job Manager] New block 6340463 detected 
ethereum-pool_master-node.1.c14naso5tvgc@db-node-1    | [2018-09-16 05:20:43.8868] [I] [eth1] [Pool] Broadcasting job 
ethereum-pool_master-node.1.c14naso5tvgc@db-node-1    | [2018-09-16 05:20:44.2479] [I] [eth1] [Ethereum Job Manager] New block 6340463 detected 
ethereum-pool_master-node.1.c14naso5tvgc@db-node-1    | [2018-09-16 05:20:44.2479] [I] [eth1] [Pool] Broadcasting job 
ethereum-pool_master-node.1.c14naso5tvgc@db-node-1    | [2018-09-16 05:20:45.0599] [I] [eth1] [Ethereum Job Manager] New block 6340464 detected 
ethereum-pool_master-node.1.c14naso5tvgc@db-node-1    | [2018-09-16 05:20:45.0599] [I] [eth1] [Pool] Broadcasting job 
ethereum-pool_master-node.1.c14naso5tvgc@db-node-1    | [2018-09-16 05:20:45.5674] [I] [eth1] [Ethereum Job Manager] New block 6340464 detected 
ethereum-pool_master-node.1.c14naso5tvgc@db-node-1    | [2018-09-16 05:20:45.5674] [I] [eth1] [Pool] Broadcasting job 
```

**Comment by mvilera** [comment]
Forgot to mention, if I enable the portWs option on the daemon config object, the broadcast is even faster, around 100 req/s against the parity server.

**Comment by mvilera** [comment]
Found out this error when restarting the daemon

```
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    | [2018-09-16 05:33:53.2187] [I] [eth1] [Ethereum Job Manager] All daemons online 
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    | [2018-09-16 05:33:53.2390] [I] [eth1] [Ethereum Job Manager] Daemons still syncing with network. Manager will be started once synced 
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    | [2018-09-16 05:33:53.2639] [I] [eth1] [Ethereum Job Manager] Daemons have downloaded 100.00% of blockchain from 10 peers 
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    | [2018-09-16 05:33:58.2689] [E] [eth1] System.InvalidCastException: Unable to cast object of type 'System.Boolean' to type 'Newtonsoft.Json.Linq.JToken'.
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at MiningCore.DaemonInterface.DaemonClient.MapDaemonResponse[TResponse](Int32 i, Task`1 x, Boolean throwOnError) in /tmp/miningcore/src/MiningCore/DaemonInterface/DaemonClient.cs:line 435
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at System.Linq.Enumerable.SelectIterator[TSource,TResult](IEnumerable`1 source, Func`3 selector)+MoveNext()
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at MiningCore.DaemonInterface.DaemonClient.ExecuteCmdAllAsync[TResponse](String method, Object payload, JsonSerializerSettings payloadJsonSerializerSettings)
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at MiningCore.Blockchain.Ethereum.EthereumJobManager.ShowDaemonSyncProgressAsync() in /tmp/miningcore/src/MiningCore/Blockchain/Ethereum/EthereumJobManager.cs:line 213
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at MiningCore.Blockchain.Ethereum.EthereumJobManager.EnsureDaemonsSynchedAsync(CancellationToken ct) in /tmp/miningcore/src/MiningCore/Blockchain/Ethereum/EthereumJobManager.cs:line 499
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at MiningCore.Blockchain.JobManagerBase`1.StartAsync(CancellationToken ct) in /tmp/miningcore/src/MiningCore/Blockchain/JobManagerBase.cs:line 215
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at MiningCore.Blockchain.Ethereum.EthereumPool.SetupJobManager(CancellationToken ct) in /tmp/miningcore/src/MiningCore/Blockchain/Ethereum/EthereumPool.cs:line 283
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at MiningCore.Mining.PoolBase.StartAsync(CancellationToken ct) in /tmp/miningcore/src/MiningCore/Mining/PoolBase.cs:line 354 System.InvalidCastException: Unable to cast object of type 'System.Boolean' to type 'Newtonsoft.Json.Linq.JToken'.
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at MiningCore.DaemonInterface.DaemonClient.MapDaemonResponse[TResponse](Int32 i, Task`1 x, Boolean throwOnError) in /tmp/miningcore/src/MiningCore/DaemonInterface/DaemonClient.cs:line 435
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at System.Linq.Enumerable.SelectIterator[TSource,TResult](IEnumerable`1 source, Func`3 selector)+MoveNext()
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at MiningCore.DaemonInterface.DaemonClient.ExecuteCmdAllAsync[TResponse](String method, Object payload, JsonSerializerSettings payloadJsonSerializerSettings)
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at MiningCore.Blockchain.Ethereum.EthereumJobManager.ShowDaemonSyncProgressAsync() in /tmp/miningcore/src/MiningCore/Blockchain/Ethereum/EthereumJobManager.cs:line 213
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at MiningCore.Blockchain.Ethereum.EthereumJobManager.EnsureDaemonsSynchedAsync(CancellationToken ct) in /tmp/miningcore/src/MiningCore/Blockchain/Ethereum/EthereumJobManager.cs:line 499
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at MiningCore.Blockchain.JobManagerBase`1.StartAsync(CancellationToken ct) in /tmp/miningcore/src/MiningCore/Blockchain/JobManagerBase.cs:line 215
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at MiningCore.Blockchain.Ethereum.EthereumPool.SetupJobManager(CancellationToken ct) in /tmp/miningcore/src/MiningCore/Blockchain/Ethereum/EthereumPool.cs:line 283
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at MiningCore.Mining.PoolBase.StartAsync(CancellationToken ct) in /tmp/miningcore/src/MiningCore/Mining/PoolBase.cs:line 354    at MiningCore.DaemonInterface.DaemonClient.MapDaemonResponse[TResponse](Int32 i, Task`1 x, Boolean throwOnError) in /tmp/miningcore/src/MiningCore/DaemonInterface/DaemonClient.cs:line 435
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at System.Linq.Enumerable.SelectIterator[TSource,TResult](IEnumerable`1 source, Func`3 selector)+MoveNext()
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at MiningCore.DaemonInterface.DaemonClient.ExecuteCmdAllAsync[TResponse](String method, Object payload, JsonSerializerSettings payloadJsonSerializerSettings)
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at MiningCore.Blockchain.Ethereum.EthereumJobManager.ShowDaemonSyncProgressAsync() in /tmp/miningcore/src/MiningCore/Blockchain/Ethereum/EthereumJobManager.cs:line 213
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at MiningCore.Blockchain.Ethereum.EthereumJobManager.EnsureDaemonsSynchedAsync(CancellationToken ct) in /tmp/miningcore/src/MiningCore/Blockchain/Ethereum/EthereumJobManager.cs:line 499
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at MiningCore.Blockchain.JobManagerBase`1.StartAsync(CancellationToken ct) in /tmp/miningcore/src/MiningCore/Blockchain/JobManagerBase.cs:line 215
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at MiningCore.Blockchain.Ethereum.EthereumPool.SetupJobManager(CancellationToken ct) in /tmp/miningcore/src/MiningCore/Blockchain/Ethereum/EthereumPool.cs:line 283
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at MiningCore.Mining.PoolBase.StartAsync(CancellationToken ct) in /tmp/miningcore/src/MiningCore/Mining/PoolBase.cs:line 354
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    | System.AggregateException: One or more errors occurred. (Unable to cast object of type 'System.Boolean' to type 'Newtonsoft.Json.Linq.JToken'.) ---> System.InvalidCastException: Unable to cast object of type 'System.Boolean' to type 'Newtonsoft.Json.Linq.JToken'.
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at MiningCore.DaemonInterface.DaemonClient.MapDaemonResponse[TResponse](Int32 i, Task`1 x, Boolean throwOnError) in /tmp/miningcore/src/MiningCore/DaemonInterface/DaemonClient.cs:line 435
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at System.Linq.Enumerable.SelectIterator[TSource,TResult](IEnumerable`1 source, Func`3 selector)+MoveNext()
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at MiningCore.DaemonInterface.DaemonClient.ExecuteCmdAllAsync[TResponse](String method, Object payload, JsonSerializerSettings payloadJsonSerializerSettings)
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at MiningCore.Blockchain.Ethereum.EthereumJobManager.ShowDaemonSyncProgressAsync() in /tmp/miningcore/src/MiningCore/Blockchain/Ethereum/EthereumJobManager.cs:line 213
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at MiningCore.Blockchain.Ethereum.EthereumJobManager.EnsureDaemonsSynchedAsync(CancellationToken ct) in /tmp/miningcore/src/MiningCore/Blockchain/Ethereum/EthereumJobManager.cs:line 499
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at MiningCore.Blockchain.JobManagerBase`1.StartAsync(CancellationToken ct) in /tmp/miningcore/src/MiningCore/Blockchain/JobManagerBase.cs:line 215
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at MiningCore.Blockchain.Ethereum.EthereumPool.SetupJobManager(CancellationToken ct) in /tmp/miningcore/src/MiningCore/Blockchain/Ethereum/EthereumPool.cs:line 283
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at MiningCore.Mining.PoolBase.StartAsync(CancellationToken ct) in /tmp/miningcore/src/MiningCore/Mining/PoolBase.cs:line 354
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at MiningCore.Program.<>c.<<Start>b__33_2>d.MoveNext() in /tmp/miningcore/src/MiningCore/Program.cs:line 627
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    | --- End of stack trace from previous location where exception was thrown ---
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at MiningCore.Program.Start() in /tmp/miningcore/src/MiningCore/Program.cs:line 612
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    --- End of inner exception stack trace ---
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at MiningCore.Program.Main(String[] args) in /tmp/miningcore/src/MiningCore/Program.cs:line 91
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    | ---> (Inner Exception #0) System.InvalidCastException: Unable to cast object of type 'System.Boolean' to type 'Newtonsoft.Json.Linq.JToken'.
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at MiningCore.DaemonInterface.DaemonClient.MapDaemonResponse[TResponse](Int32 i, Task`1 x, Boolean throwOnError) in /tmp/miningcore/src/MiningCore/DaemonInterface/DaemonClient.cs:line 435
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at System.Linq.Enumerable.SelectIterator[TSource,TResult](IEnumerable`1 source, Func`3 selector)+MoveNext()
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at MiningCore.DaemonInterface.DaemonClient.ExecuteCmdAllAsync[TResponse](String method, Object payload, JsonSerializerSettings payloadJsonSerializerSettings)
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at MiningCore.Blockchain.Ethereum.EthereumJobManager.ShowDaemonSyncProgressAsync() in /tmp/miningcore/src/MiningCore/Blockchain/Ethereum/EthereumJobManager.cs:line 213
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at MiningCore.Blockchain.Ethereum.EthereumJobManager.EnsureDaemonsSynchedAsync(CancellationToken ct) in /tmp/miningcore/src/MiningCore/Blockchain/Ethereum/EthereumJobManager.cs:line 499
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at MiningCore.Blockchain.JobManagerBase`1.StartAsync(CancellationToken ct) in /tmp/miningcore/src/MiningCore/Blockchain/JobManagerBase.cs:line 215
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at MiningCore.Blockchain.Ethereum.EthereumPool.SetupJobManager(CancellationToken ct) in /tmp/miningcore/src/MiningCore/Blockchain/Ethereum/EthereumPool.cs:line 283
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at MiningCore.Mining.PoolBase.StartAsync(CancellationToken ct) in /tmp/miningcore/src/MiningCore/Mining/PoolBase.cs:line 354
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at MiningCore.Program.<>c.<<Start>b__33_2>d.MoveNext() in /tmp/miningcore/src/MiningCore/Program.cs:line 627
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    | --- End of stack trace from previous location where exception was thrown ---
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at MiningCore.Program.Start() in /tmp/miningcore/src/MiningCore/Program.cs:line 612<---
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    | 
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    | Cluster cannot start. Good Bye!
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    | [2018-09-16 05:33:58.2814] [I] [Program] Shutdown ... 
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    | Shutdown...
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    | [2018-09-16 05:33:58.2845] [E] [Program] System.NullReferenceException: Object reference not set to an instance of an object.
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at MiningCore.Mining.PoolBase.Stop() in /tmp/miningcore/src/MiningCore/Mining/PoolBase.cs:line 390
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at MiningCore.Program.Shutdown() in /tmp/miningcore/src/MiningCore/Program.cs:line 686
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at MiningCore.Program.Main(String[] args) in /tmp/miningcore/src/MiningCore/Program.cs:line 162 
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    | ** AppDomain unhandled exception: System.NullReferenceException: Object reference not set to an instance of an object.
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at MiningCore.Mining.PoolBase.Stop() in /tmp/miningcore/src/MiningCore/Mining/PoolBase.cs:line 390
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at MiningCore.Program.Shutdown() in /tmp/miningcore/src/MiningCore/Program.cs:line 686
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at MiningCore.Program.Main(String[] args) in /tmp/miningcore/src/MiningCore/Program.cs:line 162
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    | 
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    | Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at MiningCore.Mining.PoolBase.Stop() in /tmp/miningcore/src/MiningCore/Mining/PoolBase.cs:line 390
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at MiningCore.Program.Shutdown() in /tmp/miningcore/src/MiningCore/Program.cs:line 686
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    |    at MiningCore.Program.Main(String[] args) in /tmp/miningcore/src/MiningCore/Program.cs:line 162
ethereum-pool_master-node.1.ry54w658xah0@db-node-1    | Aborted (core dumped)
```

**Comment by mvilera** [comment]
The problem is caused by running any parity version newer than 1.10.x
