### ISSUE TITLE
DLL error when LTC miner connected to pool

### ISSUE THREAD

**Issue by seperatis** [coinfoundry/miningcore#400]
Install is on Windows 10.
Miner is Antminer L3+

I fired up the pool after setting all the configs for LTC and correct ports, and RPC info in litecoin.conf

Everything looked fine until a miner connected, then it spit out this DLL error:

`Using configuration file litecoin.json

[2018-09-25 13:07:10.6737] [I] [Program] .NET Core 4.6.26814.03 on Microsoft Windows 10.0.15063 [X64]
[2018-09-25 13:07:10.7889] [I] [ShareRecorder] Online
[2018-09-25 13:07:10.7889] [I] [ApiServer] Launching ...
[2018-09-25 13:07:10.8590] [I] [ApiServer] API Online @ 127.0.0.1:4000
[2018-09-25 13:07:10.8633] [I] [ApiServer] Admin API Online @ 127.0.0.1:4001
[2018-09-25 13:07:10.8633] [I] [StatsRecorder] Online
[2018-09-25 13:07:10.8633] [I] [PayoutManager] Online
[2018-09-25 13:07:10.8767] [I] [PayoutManager] Processing payments for pool ltc1
[2018-09-25 13:07:10.8939] [I] [ltc1] Starting Pool ...
[2018-09-25 13:07:10.9104] [I] [ltc1] Starting Job Manager ...
[2018-09-25 13:07:11.0270] [I] [ltc1] All daemons online
[2018-09-25 13:07:11.0936] [I] [ltc1] All daemons synched with blockchain
[2018-09-25 13:07:11.2293] [I] [ltc1] Job Manager Online
[2018-09-25 13:07:11.5019] [I] [PayoutManager] No updated blocks for pool ltc1
[2018-09-25 13:07:11.5019] [I] [PayoutManager] No balances over configured minimum payout for pool ltc1
[2018-09-25 13:07:11.9182] [I] [ltc1] Detected new block 1498408 via RPC polling
[2018-09-25 13:07:11.9242] [I] [ltc1] Broadcasting job
[2018-09-25 13:07:11.9980] [I] [ltc1] Pool Online
[2018-09-25 13:07:12.0035] [I] [ltc1]

Mining Pool:            ltc1
Coin Type:              LTC
Network Connected:      Main
Detected Reward Type:   POW
Current Block Height:   1498408
Current Connect Peers:  8
Network Difficulty:     9230764.74712875
Network Hash Rate:      254 TH/s
Stratum Port(s):        3333
Pool Fee:               1.1%

[2018-09-25 13:07:12.0035] [I] [ltc1] Stratum ports 0.0.0.0:3333 online
[2018-09-25 13:07:20.8774] [I] [StatsRecorder] Updating hashrates for pool ltc1
[2018-09-25 13:07:21.2958] [I] [ltc1] Broadcasting job
[2018-09-25 13:07:31.3095] [I] [ltc1] Broadcasting job
[2018-09-25 13:07:41.3105] [I] [ltc1] Broadcasting job
[2018-09-25 13:07:51.3248] [I] [ltc1] Broadcasting job
[2018-09-25 13:07:53.7359] [I] [ltc1] [0HLH34A9TSIP1] Connection from ::ffff:10.0.0.104:55400 accepted on port 3333
[2018-09-25 13:07:53.7910] [I] [ltc1] [0HLH34A9TSIP1] Authorized worker MTfcs2kAC9ai3jazsh4J6HsojnmZSTgEmv
[2018-09-25 13:07:54.8559] [E] [ltc1] [0HLH34A9TSIP1] Error processing request mining.submit [3] System.DllNotFoundException: Unable to load DLL 'libmultihash' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at MiningCore.Native.LibMultihash.scrypt(Byte* input, Byte* output, UInt32 n, UInt32 r, UInt32 inputLength)
   at MiningCore.Crypto.Hashing.Algorithms.Scrypt.Digest(Byte[] data, Object[] extra) in C:\Users\seper\miningcore\src\MiningCore\Crypto\Hashing\Algorithms\Scrypt.cs:line 41
   at MiningCore.Blockchain.Bitcoin.BitcoinJob`1.ProcessShareInternal(StratumClient worker, String extraNonce2, UInt32 nTime, UInt32 nonce) in C:\Users\seper\miningcore\src\MiningCore\Blockchain\Bitcoin\BitcoinJob.cs:line 321
   at MiningCore.Blockchain.Bitcoin.BitcoinJob`1.ProcessShare(StratumClient worker, String extraNonce2, String nTime, String nonce) in C:\Users\seper\miningcore\src\MiningCore\Blockchain\Bitcoin\BitcoinJob.cs:line 532
   at MiningCore.Blockchain.Bitcoin.BitcoinJobManager`2.SubmitShareAsync(StratumClient worker, Object submission, Double stratumDifficultyBase) in C:\Users\seper\miningcore\src\MiningCore\Blockchain\Bitcoin\BitcoinJobManager.cs:line 532
   at MiningCore.Blockchain.Bitcoin.BitcoinPoolBase`2.OnSubmitAsync(StratumClient client, Timestamped`1 tsRequest) in C:\Users\seper\miningcore\src\MiningCore\Blockchain\Bitcoin\BitcoinPoolBase.cs:line 191
   at MiningCore.Blockchain.Bitcoin.BitcoinPoolBase`2.OnRequestAsync(StratumClient client, Timestamped`1 tsRequest) in C:\Users\seper\miningcore\src\MiningCore\Blockchain\Bitcoin\BitcoinPoolBase.cs:line 373
   at MiningCore.Stratum.StratumServer.OnRequestAsync(StratumClient client, JsonRpcRequest request) in C:\Users\seper\miningcore\src\MiningCore\Stratum\StratumServer.cs:line 232    at MiningCore.Native.LibMultihash.scrypt(Byte* input, Byte* output, UInt32 n, UInt32 r, UInt32 inputLength)
   at MiningCore.Crypto.Hashing.Algorithms.Scrypt.Digest(Byte[] data, Object[] extra) in C:\Users\seper\miningcore\src\MiningCore\Crypto\Hashing\Algorithms\Scrypt.cs:line 41
   at MiningCore.Blockchain.Bitcoin.BitcoinJob`1.ProcessShareInternal(StratumClient worker, String extraNonce2, UInt32 nTime, UInt32 nonce) in C:\Users\seper\miningcore\src\MiningCore\Blockchain\Bitcoin\BitcoinJob.cs:line 321
   at MiningCore.Blockchain.Bitcoin.BitcoinJob`1.ProcessShare(StratumClient worker, String extraNonce2, String nTime, String nonce) in C:\Users\seper\miningcore\src\MiningCore\Blockchain\Bitcoin\BitcoinJob.cs:line 532
   at MiningCore.Blockchain.Bitcoin.BitcoinJobManager`2.SubmitShareAsync(StratumClient worker, Object submission, Double stratumDifficultyBase) in C:\Users\seper\miningcore\src\MiningCore\Blockchain\Bitcoin\BitcoinJobManager.cs:line 532
   at MiningCore.Blockchain.Bitcoin.BitcoinPoolBase`2.OnSubmitAsync(StratumClient client, Timestamped`1 tsRequest) in C:\Users\seper\miningcore\src\MiningCore\Blockchain\Bitcoin\BitcoinPoolBase.cs:line 191
   at MiningCore.Blockchain.Bitcoin.BitcoinPoolBase`2.OnRequestAsync(StratumClient client, Timestamped`1 tsRequest) in C:\Users\seper\miningcore\src\MiningCore\Blockchain\Bitcoin\BitcoinPoolBase.cs:line 373
   at MiningCore.Stratum.StratumServer.OnRequestAsync(StratumClient client, JsonRpcRequest request) in C:\Users\seper\miningcore\src\MiningCore\Stratum\StratumServer.cs:line 232
[2018-09-25 13:08:01.3147] [I] [ltc1] Broadcasting job
[2018-09-25 13:08:11.3365] [I] [ltc1] Broadcasting job
[2018-09-25 13:08:21.3438] [I] [ltc1] Broadcasting job
[2018-09-25 13:08:29.1657] [I] [ltc1] Detected new block 1498409 via RPC polling
[2018-09-25 13:08:29.1657] [I] [ltc1] Broadcasting job
[2018-09-25 13:08:31.3467] [I] [ltc1] Broadcasting job
[2018-09-25 13:08:41.3543] [I] [ltc1] Broadcasting job`

My Antminer L3+ is still hashing at the correct speed, and my Bestshare keeps increasing, so I can't tell if this is actually affecting anything or not, but it seems like a big deal based on the massive error printed in Bright Red text.

This is a lot of info and I have little idea what most of it means, so I'm not sure if it's a bug or misconfiguration on my part.

Thanks to anyone who can look further into it.

**Comment by seperatis** [comment]
UPDATE:

I am also receiving this message about booting a Zombie Worker also: 

`[2018-09-25 13:18:01.7931] [I] [ltc1] [0HLH34A9TSIP1] Booting zombie-worker (idle-timeout exceeded)`

After the above error, it looks like my miner keeps disconnecting and re-connecting to the pool, best I can tell.

The following error is after the miner gets booted and reconnects:

`[2018-09-25 13:21:21.9762] [I] [ltc1] [0HLH34A9TSIP3] Connection from ::ffff:10.0.0.104:55471 accepted on port 3333
[2018-09-25 13:21:21.9762] [I] [ltc1] [0HLH34A9TSIP3] Authorized worker MTfcs2kAC9ai3jazsh4J6HsojnmZSTgEmv
[2018-09-25 13:21:23.7067] [I] [ltc1] [0HLH34A9TSIP3] Share rejected: JobNotFound`

**Comment by oliverw** [comment]
Like I said, the windows build stuff has been kind of neglected for quite some time since nobody used it. 

Regarding the DLL load failure, copying src/MiningCore/runtimes/x64/native/*.dll to your build output folder should fix it - even though this step shouldn't be necessary.

The zombie worker disconnect is a anti-DoS measure to prevent malicious actors from bogging down all available TCP ports of the server with idle connections.

**Comment by seperatis** [comment]
OK, this did fix that issue. I'm switching over to Ubuntu and closing this.
