### ISSUE TITLE
Error when calling the api

### ISSUE THREAD

**Issue by Konstantin35** [coinfoundry/miningcore#418]
This happens when you try to open the api through the browser, I may have made a mistake in the coin configuration
```
[2018-10-07 19:27:06.3374] [I] [Core] .NET Core 4.6.26919.02 on Linux 4.4.0-137-generic #163-Ubuntu SMP Mon Sep 24 13:14:43 UTC 2018 [X64]
[2018-10-07 19:27:06.5324] [I] [Core] 36 coins loaded from /home/evanto/miningcore/miningcore-34/build/coins.json
[2018-10-07 19:27:06.7706] [I] [ShareRecorder] Online
[2018-10-07 19:27:06.8058] [I] [ApiServer] Launching ...
[2018-10-07 19:27:06.9510] [I] [ApiServer] API Online @ 192.168.100.100:4000
[2018-10-07 19:27:06.9624] [I] [ApiServer] Admin API Online @ 192.168.100.100:4001
[2018-10-07 19:27:06.9798] [I] [PayoutManager] Online
[2018-10-07 19:27:06.9814] [I] [StatsRecorder] Online
[2018-10-07 19:27:06.9924] [I] [PayoutManager] Processing payments for pool tube1
[2018-10-07 19:27:07.0437] [I] [tube1] Starting Pool ...
[2018-10-07 19:27:07.0975] [I] [tube1] Starting Job Manager ...
[2018-10-07 19:27:07.4689] [I] [tube1] All daemons online
[2018-10-07 19:27:08.2680] [I] [tube1] All daemons synched with blockchain
[2018-10-07 19:27:08.5359] [I] [tube1] Job Manager Online
[2018-10-07 19:27:09.1521] [I] [PayoutManager] No updated blocks for pool tube1
[2018-10-07 19:27:09.1759] [I] [PayoutManager] No balances over configured minimum payout for pool tube1
[2018-10-07 19:27:10.2651] [I] [tube1] Detected new block 179831 via Initial template
[2018-10-07 19:27:10.2811] [I] [tube1] Broadcasting job
[2018-10-07 19:27:10.4818] [I] [tube1] Pool Online
[2018-10-07 19:27:10.4919] [I] [tube1]

Mining Pool:            tube1
Coin Type:              TUBE [TUBE]
Network Connected:      Main
Detected Reward Type:   POW
Current Block Height:   179831
Current Connect Peers:  100
Network Difficulty:     2948718683
Network Hash Rate:      23 MH/s
Stratum Port(s):        3032, 3033, 3034
Pool Fee:               1%

[2018-10-07 19:27:10.5039] [I] [tube1] Stratum ports 192.168.100.100:3032, 192.168.100.100:3033, 192.168.100.100:3034 online
[2018-10-07 19:27:16.9953] [I] [StatsRecorder] Updating hashrates for pool tube1
[2018-10-07 19:27:19.8830] [E] [ApiServer] AutoMapper.AutoMapperMappingException: Error mapping types.

Mapping types:
PoolConfig -> PoolInfo
Miningcore.Configuration.PoolConfig -> Miningcore.Api.Responses.PoolInfo

Type Map configuration:
PoolConfig -> PoolInfo
Miningcore.Configuration.PoolConfig -> Miningcore.Api.Responses.PoolInfo

Property:
Coin ---> AutoMapper.AutoMapperConfigurationException:
Unmapped members were found. Review the types and members below.
Add a custom mapping expression, ignore, add a custom resolver, or modify the source/destination type
For no matching constructor, add a no-arg ctor, add optional arguments, or map all of the constructor parameters
========================================================
AutoMapper created this type map for you, but your types cannot be mapped using the current configuration.
String -> ApiCoinConfig (Destination member list)
System.String -> Miningcore.Api.Responses.ApiCoinConfig (Destination member list)

Unmapped properties:
Type
Algorithm

   at AutoMapper.ConfigurationValidator.AssertConfigurationIsValid(IEnumerable`1 typeMaps)
   at lambda_method(Closure , PoolConfig , PoolInfo , ResolutionContext )
   --- End of inner exception stack trace ---
   at lambda_method(Closure , PoolConfig , PoolInfo , ResolutionContext )
   at lambda_method(Closure , Object , Object , ResolutionContext )
   at AutoMapper.Mapper.AutoMapper.IMapper.Map[TDestination](Object source)
   at Miningcore.Api.Extensions.MiningPoolExtensions.ToPoolInfo(PoolConfig poolConfig, IComponentContext ctx, IMapper mapper, PoolStats stats, IMiningPool pool) in /home/evanto/miningcore/miningcore-34/src/Miningcore/Api/Extensions/MiningPoolExtensions.cs:line 18
   at Miningcore.Api.ApiServer.<GetPoolInfosAsync>b__22_1(PoolConfig config) in /home/evanto/miningcore/miningcore-34/src/Miningcore/Api/ApiServer.cs:line 262
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Miningcore.Api.ApiServer.GetPoolInfosAsync(HttpContext context, Match m) in /home/evanto/miningcore/miningcore-34/src/Miningcore/Api/ApiServer.cs:line 251
   at Miningcore.Api.ApiServer.HandleRequest(HttpContext context) in /home/evanto/miningcore/miningcore-34/src/Miningcore/Api/ApiServer.cs:line 195 AutoMapper.AutoMapperMappingException: Error mapping types.

Mapping types:
PoolConfig -> PoolInfo
Miningcore.Configuration.PoolConfig -> Miningcore.Api.Responses.PoolInfo

Type Map configuration:
PoolConfig -> PoolInfo
Miningcore.Configuration.PoolConfig -> Miningcore.Api.Responses.PoolInfo

Property:
Coin ---> AutoMapper.AutoMapperConfigurationException:
Unmapped members were found. Review the types and members below.
Add a custom mapping expression, ignore, add a custom resolver, or modify the source/destination type
For no matching constructor, add a no-arg ctor, add optional arguments, or map all of the constructor parameters
========================================================
AutoMapper created this type map for you, but your types cannot be mapped using the current configuration.
String -> ApiCoinConfig (Destination member list)
System.String -> Miningcore.Api.Responses.ApiCoinConfig (Destination member list)

Unmapped properties:
Type
Algorithm

   at AutoMapper.ConfigurationValidator.AssertConfigurationIsValid(IEnumerable`1 typeMaps)
   at lambda_method(Closure , PoolConfig , PoolInfo , ResolutionContext )
   --- End of inner exception stack trace ---
   at lambda_method(Closure , PoolConfig , PoolInfo , ResolutionContext )
   at lambda_method(Closure , Object , Object , ResolutionContext )
   at AutoMapper.Mapper.AutoMapper.IMapper.Map[TDestination](Object source)
   at Miningcore.Api.Extensions.MiningPoolExtensions.ToPoolInfo(PoolConfig poolConfig, IComponentContext ctx, IMapper mapper, PoolStats stats, IMiningPool pool) in /home/evanto/miningcore/miningcore-34/src/Miningcore/Api/Extensions/MiningPoolExtensions.cs:line 18
   at Miningcore.Api.ApiServer.<GetPoolInfosAsync>b__22_1(PoolConfig config) in /home/evanto/miningcore/miningcore-34/src/Miningcore/Api/ApiServer.cs:line 262
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Miningcore.Api.ApiServer.GetPoolInfosAsync(HttpContext context, Match m) in /home/evanto/miningcore/miningcore-34/src/Miningcore/Api/ApiServer.cs:line 251
   at Miningcore.Api.ApiServer.HandleRequest(HttpContext context) in /home/evanto/miningcore/miningcore-34/src/Miningcore/Api/ApiServer.cs:line 195    at lambda_method(Closure , PoolConfig , PoolInfo , ResolutionContext )
   at lambda_method(Closure , Object , Object , ResolutionContext )
   at Miningcore.Api.Extensions.MiningPoolExtensions.ToPoolInfo(PoolConfig poolConfig, IComponentContext ctx, IMapper mapper, PoolStats stats, IMiningPool pool) in /home/evanto/miningcore/miningcore-34/src/Miningcore/Api/Extensions/MiningPoolExtensions.cs:line 18
   at Miningcore.Api.ApiServer.<GetPoolInfosAsync>b__22_1(PoolConfig config) in /home/evanto/miningcore/miningcore-34/src/Miningcore/Api/ApiServer.cs:line 262
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Miningcore.Api.ApiServer.GetPoolInfosAsync(HttpContext context, Match m) in /home/evanto/miningcore/miningcore-34/src/Miningcore/Api/ApiServer.cs:line 251
   at Miningcore.Api.ApiServer.HandleRequest(HttpContext context) in /home/evanto/miningcore/miningcore-34/src/Miningcore/Api/ApiServer.cs:line 195

```

## configuration

```
    "pools": [
		{
		"enabled": true,
			"id": "tube1",
            "coin": "bittube",
			"address": "bxdxxgoy3FVdJanV5bpsQB9oFwkd37b4yYkrpmZZzzJDP436mM5Xh3zD88FqtmSNTLPdF32CJjtJ1eDeVytF1YVG2ojmM8Ses",
			"rewardRecipients": [
				{
					"address": "bxdxxgoy3FVdJanV5bpsQB9oFwkd37b4yYkrpmZZzzJDP436mM5Xh3zD88FqtmSNTLPdF32CJjtJ1eDeVytF1YVG2ojmM8Ses",
					"percentage": 1
				}
			],
			"blockRefreshInterval": 0,
			"clientConnectionTimeout": 800,
			"banning": {
				"enabled": true,
				"time": 600,
				"invalidPercent": 50,
				"checkThreshold": 50
			},
			"ports": {
				"3032": {
					"listenAddress": "192.168.100.100",
					"difficulty": 7500,
					"name": "CPU Mining",
					"varDiff": {
						"minDiff": 1000,
						"maxDiff": null,
						"targetTime": 15,
						"retargetTime": 90,
						"variancePercent": 30
					}
				},
				"3033": {
					"listenAddress": "192.168.100.100",
					"difficulty": 25000,
					"name": "GPU Mining",
					"varDiff": {
						"minDiff": 10000,
						"maxDiff": null,
						"targetTime": 15,
						"retargetTime": 90,
						"variancePercent": 30
					}
				},
				"3034": {
					"listenAddress": "192.168.100.100",
					"difficulty": 200000,
					"name": "High-End Multi GPU Mining",
					"varDiff": {
						"minDiff": 200000,
						"maxDiff": null,
						"targetTime": 15,
						"retargetTime": 120,
						"variancePercent": 30
					}
				}
			},
			"daemons": [
				{
					"host": "127.0.0.1",
					"port": 24182,
					"user": "user",
					"password": "pass"
				},
				{
					"host": "127.0.0.1",
					"port": 18082,
					"user": "user",
					"password": "pass",
					"category": "wallet"
				}
			],
			"paymentProcessing": {
				"enabled": true,
				"minimumPayment": 0.25,
				"minimumPaymentToPaymentId": 1.0,
				"payoutScheme": "PPLNS",
				"payoutSchemeConfig": {
					"factor": 1.0
				}
			}
		}
	]
```

`./bittubed --data-dir=/tube/db --rpc-bind-ip 127.0.0.1  --rpc-login user:pass`

`./bittube-wallet-rpc --wallet-file=/tube/wallet --daemon-host 127.0.0.1:24182 --daemon-login user:pass --rpc-bind-port 18082 --rpc-bind-ip 127.0.0.1 --rpc-login user:pass --password-file=/tube/pass.txt --log-level 1`

**Comment by oliverw** [comment]
I've just noticed that as well. Fix coming in a couple minutes.

**Comment by Konstantin35** [comment]
Thanks
