### ISSUE TITLE
ShareReceiver  Resource temporarily unavailable EAGAIN

### ISSUE THREAD

**Issue by fathusband** [coinfoundry/miningcore#426]
### Description

I been trying to deploy miningcore pool with sharerelay features but I believe it doesnt work properly. 
during my test I found some error in corelog , I also check sharerelay port (6000) and its not running.
please let me know if theres is something missing here. 

these are my servers info

10.11.1.2 = masterserver
10.11.1.3 = slave (stratum)
10.11.1.4 = coinserver

### Steps to Reproduce

1. configure config.json with sharerelay option
2.  execute dotnet Miningcore.dll -c config.json
3. monitor the logs

### Expected behavior

1 - no error log
2 - sharerelay port in open status

### Actual behavior

the log file in masterserver throwing error messages  saying share receiver Resource temporarily unavailable
lsof -i|grep 6000 not showing any establish connection from master server.

root@slave:~# lsof -i |grep dotnet
dotnet    2509 miningcore  118u  IPv4  22956      0t0  TCP 10.11.1.3:44141->10.11.1.4:9998 (ESTABLISHED)
dotnet    2509 miningcore  132u  IPv4  22962      0t0  TCP 10.11.1.3:37272->10.11.1.4:15101 (ESTABLISHED)
dotnet    2509 miningcore  133u  IPv6  22967      0t0  TCP *:3082 (LISTEN)
root@slave:~# lsof -i |grep dotnet

### Reproduces how often

100%

### Additional Information

master server config.json
===========================

{
  "logging": {
    "level": "info",
    "enableConsoleLog": true,
    "enableConsoleColors": true,
    "logFile": "/home/userA/dashconf/corelog",
    "logBaseDirectory": "/home/userA/dashconf/poollog",
    "perPoolLogFile": true
  },
  "banning": {
    "manager": "integrated",
    "banOnJunkReceive": true,
    "banOnInvalidShares": false
  },
  "notifications": {
    "enabled": true,
    "email": {
      "host": "",
      "port": 587,
      "user": "",
      "password": "",
      "fromAddress": "",
      "fromName": "pool support"
    },
    "admin": {
      "enabled": true,
      "emailAddress": "",
      "notifyBlockFound": true
    }
  },
  "persistence": {
    "postgres": {
      "host": "",
      "port": 5432,
      "user": "",
      "password": "",
      "database": ""
    }
  },
  "shareRelays": [
    {
      "url": "tcp://10.11.1.3:6000",
      "sharedEncryptionKey": "foobar"
    }
  ],
 
  "paymentProcessing": {
    "enabled": true,
    "interval": 600,
    "shareRecoveryFile": "/home/userA/dashconf/recovered-shares.txt"
  },
  "api": {
    "enabled": false
  },
  "pools": [
    {
      "id": "dash",
      "enabled": true,
      "coin": "dash",
      "hasLegacyDaemon": true,
      "enableInternalStratum": false,
      "shareRelay": {
        "publishUrl": "tcp://10.11.1.3:6000",
        "sharedEncryptionKey": "foobar"
      },
      "address": "XnbMd6qQJqRf3orRu6y8gxowXXMt5xrUB",
      "rewardRecipients": [
        {
          "address": "XnbMd6qQJqRf3orRu6y8gxowXXMt5xrUB",
          "percentage": 0.75
        }
      ],
      "blockRefreshInterval": 0,
      "jobRebroadcastTimeout": 10,
      "clientConnectionTimeout": 600,
      "banning": {
        "enabled": true,
        "time": 600,
        "invalidPercent": 50,
        "checkThreshold": 50
      },
      "ports": {
        "3082": {
          "listenAddress": "0.0.0.0",
          "difficulty": 1,
          "varDiff": {
            "minDiff": 0.01,
            "maxDiff": null,
            "targetTime": 15,
            "retargetTime": 90,
            "variancePercent": 30,
            "maxDelta": 500
          }
        }
      },
      "daemons": [
        {
          "host": "10.1.1.4",
          "port": 9998,
          "user": "user",
          "password": "notrealpass",
          "zmqBlockNotifySocket": "tcp://10.11.1.4:15101"
        }
      ],
      "paymentProcessing": {
        "enabled": true,
        "minimumPayment": 0.03,
        "payoutScheme": "PPLNS",
        "payoutSchemeConfig": {
          "factor": 2
        },
        "minersPayTxFees": true
      }
    }
  ]
}

slave server config.json
=============================

{
  "logging": {
    "level": "info",
    "enableConsoleLog": true,
    "enableConsoleColors": true,
    "logFile": "/home/UserA/dashconf/corelog",
    "logBaseDirectory": "/home/UserA/dashconf/poollog",
    "perPoolLogFile": true
  },
  "banning": {
    "manager": "integrated",
    "banOnJunkReceive": true,
    "banOnInvalidShares": false
  },
  "notifications": {
    "enabled": false,
    "admin": {
      "enabled": false
    }
  },
  
  "paymentProcessing": {
    "enabled": false
  },

  "persistence": {},
  "api": {
    "enabled": false
  },
  "pools": [
    {
      "id": "dash",
      "enabled": true,
      "coin": "dash",
      "hasLegacyDaemon": true,
      "shareRelay": {
        "publishUrl": "tcp://10.11.1.3:6000",
        "sharedEncryptionKey": "foobar"
      },
      "address": "XnbMd6qQJqRf3orRu6y8gxowXXMt5xrUB",
      "rewardRecipients": [
        {
          "address": "XnbMd6qQJqRf3orRu6y8gxowXXMt5xrUB",
          "percentage": 0.75
        }
      ],
      "blockRefreshInterval": 0,
      "jobRebroadcastTimeout": 10,
      "clientConnectionTimeout": 600,
      "banning": {
        "enabled": true,
        "time": 600,
        "invalidPercent": 50,
        "checkThreshold": 50
      },
      "ports": {
        "3082": {
          "listenAddress": "0.0.0.0",
          "difficulty": 1,
          "varDiff": {
            "minDiff": 0.01,
            "maxDiff": null,
            "targetTime": 15,
            "retargetTime": 90,
            "variancePercent": 30,
            "maxDelta": 500
          }
        }
      },
      "daemons": [
        {
          "host": "10.11.1.4",
          "port": 9998,
          "user": "user",
          "password": "notrealpassword",
          "zmqBlockNotifySocket": "tcp://10.11.1.4:15101"
        }
      ]
    }
  ]
}

lsof -i |grep dotnet . 
======================

root@slave:~# lsof -i |grep dotnet
dotnet    2509 miningcore  118u  IPv4  22956      0t0  TCP 10.11.1.3:44141->10.11.1.4:9998 (ESTABLISHED)
dotnet    2509 miningcore  132u  IPv4  22962      0t0  TCP 10.11.1.3:37272->10.11.1.4:15101 (ESTABLISHED)
dotnet    2509 miningcore  133u  IPv6  22967      0t0  TCP *:3082 (LISTEN)
root@slave:~# lsof -i |grep dotnet

firewall configuration
===========================
I've allowed the whole 10.11.1.0/24  for testing purpose . 

master core log
====================

 ███╗   ███╗██╗███╗   ██╗██╗███╗   ██╗ ██████╗  ██████╗ ██████╗ ██████╗ ███████╗
 ████╗ ████║██║████╗  ██║██║████╗  ██║██╔════╝ ██╔════╝██╔═══██╗██╔══██╗██╔════╝
 ██╔████╔██║██║██╔██╗ ██║██║██╔██╗ ██║██║  ███╗██║     ██║   ██║██████╔╝█████╗
 ██║╚██╔╝██║██║██║╚██╗██║██║██║╚██╗██║██║   ██║██║     ██║   ██║██╔══██╗██╔══╝
 ██║ ╚═╝ ██║██║██║ ╚████║██║██║ ╚████║╚██████╔╝╚██████╗╚██████╔╝██║  ██║███████╗

 https://github.com/coinfoundry/miningcore

 Please contribute to the development of the project by donating:

 BTC  - 17QnVor1B6oK1rWnVVBrdX9gFzVkZZbhDm
 LTC  - LTK6CWastkmBzGxgQhTTtCUjkjDA14kxzC
 DASH - XqpBAV9QCaoLnz42uF5frSSfrJTrqHoxjp
 ZEC  - t1YHZHz2DGVMJiggD2P4fBQ2TAPgtLSUwZ7
 ZCL  - t1MFU1vD3YKgsK6Uh8hW7UTY8mKAV2xVqBr
 ETH  - 0xcb55abBfe361B12323eb952110cE33d5F28BeeE1
 ETC  - 0xF8cCE9CE143C68d3d4A7e6bf47006f21Cfcf93c0
 XMR  - 475YVJbPHPedudkhrcNp1wDcLMTGYusGPF5fqE7XjnragVLPdqbCHBdZg3dF4dN9hXMjjvGbykS6a77dTAQvGrpiQqHp2eH

Using configuration file dashmaster.json

[2018-10-10 17:10:26.9251] [I] [Core] .NET Core 4.6.26919.02 on Linux 4.15.0-1021-gcp #22~16.04.1-Ubuntu SMP Wed Sep 26 06:08:54 UTC 2018 [X64]
[2018-10-10 17:10:27.1030] [I] [Core] 38 coins loaded from /home/userA/miningcore/build/coins.json
[2018-10-10 17:10:27.2651] [I] [ShareRecorder] Online
[2018-10-10 17:10:27.2711] [I] [ShareReceiver] Online
[2018-10-10 17:10:27.2897] [I] [PayoutManager] Online
[2018-10-10 17:10:27.2923] [I] [StatsRecorder] Online
[2018-10-10 17:10:27.3115] [I] [PayoutManager] Processing payments for pool dash
[2018-10-10 17:10:27.3597] [I] [dash] Starting Pool ...
[2018-10-10 17:10:27.3824] [I] [ShareReceiver] Monitoring external stratum tcp://10.11.1.3:6000 using Curve public-key 622a69b55eef718fcad7f38830014a2a878faa79bba14bdb37fc142d                                      6b21e75a
[2018-10-10 17:10:27.4138] [I] [dash] Starting Job Manager ...
[2018-10-10 17:10:27.6811] [I] [dash] All daemons online
[2018-10-10 17:10:27.7689] [I] [dash] All daemons synched with blockchain
[2018-10-10 17:10:27.9540] [I] [dash] Subscribing to ZMQ push-updates from (tcp://10.11.1.4:15101, hashblock)
[2018-10-10 17:10:28.0112] [I] [dash] Job Manager Online
[2018-10-10 17:10:28.5480] [I] [PayoutManager] No updated blocks for pool dash
[2018-10-10 17:10:28.5683] [I] [PayoutManager] No balances over configured minimum payout for pool dash
[2018-10-10 17:10:28.6247] [I] [dash] Pool Online
[2018-10-10 17:10:28.6314] [I] [dash]

Mining Pool:            dash
Coin Type:              DASH [DASH]
Network Connected:      Main
Detected Reward Type:   POW
Current Block Height:   0
Current Connect Peers:  16
Network Difficulty:     0
Network Hash Rate:      0 KH/s
Stratum Port(s):        3082
Pool Fee:               0.75%

[2018-10-10 17:10:29.3522] [I] [dash] Detected new block 951638 via Initial template
[2018-10-10 17:10:37.3075] [I] [StatsRecorder] Updating hashrates for pool dash
[2018-10-10 17:11:27.4098] [E] [ShareReceiver] EAGAIN(11): Resource temporarily unavailable EAGAIN(11): Resource temporarily unavailable    at ZeroMQ.ZSocket.ReceiveMessage(Z                                      SocketFlags flags)
   at Miningcore.Mining.ShareReceiver.<>c__DisplayClass8_1.<StartListeners>b__2() in /home/userA/miningcore/src/Miningcore/Mining/ShareReceiver.cs:line 94
[2018-10-10 17:11:27.4135] [I] [ShareReceiver] Monitoring external stratum tcp://10.11.1.3:6000 using Curve public-key 622a69b55eef718fcad7f38830014a2a878faa79bba14bdb37fc142d                                      6b21e75a
[2018-10-10 17:12:27.4743] [E] [ShareReceiver] EAGAIN(11): Resource temporarily unavailable EAGAIN(11): Resource temporarily unavailable    at ZeroMQ.ZSocket.ReceiveMessage(Z                                      SocketFlags flags)
   at Miningcore.Mining.ShareReceiver.<>c__DisplayClass8_1.<StartListeners>b__2() in /home/userA/miningcore/src/Miningcore/Mining/ShareReceiver.cs:line 94
[2018-10-10 17:12:27.4743] [I] [ShareReceiver] Monitoring external stratum tcp://10.11.1.3:6000 using Curve public-key 622a69b55eef718fcad7f38830014a2a878faa79bba14bdb37fc142d                                      6b21e75a
[2018-10-10 17:13:27.5046] [E] [ShareReceiver] EAGAIN(11): Resource temporarily unavailable EAGAIN(11): Resource temporarily unavailable    at ZeroMQ.ZSocket.ReceiveMessage(Z                                      SocketFlags flags)
   at Miningcore.Mining.ShareReceiver.<>c__DisplayClass8_1.<StartListeners>b__2() in /home/userA/miningcore/src/Miningcore/Mining/ShareReceiver.cs:line 94
[2018-10-10 17:13:27.5046] [I] [ShareReceiver] Monitoring external stratum tcp://10.11.1.3:6000 using Curve public-key 622a69b55eef718fcad7f38830014a2a878faa79bba14bdb37fc142d                                      6b21e75a
[2018-10-10 17:14:27.5661] [E] [ShareReceiver] EAGAIN(11): Resource temporarily unavailable EAGAIN(11): Resource temporarily unavailable    at ZeroMQ.ZSocket.ReceiveMessage(Z                                      SocketFlags flags)
   at Miningcore.Mining.ShareReceiver.<>c__DisplayClass8_1.<StartListeners>b__2() in /home/userA/miningcore/src/Miningcore/Mining/ShareReceiver.cs:line 94
[2018-10-10 17:14:27.5672] [I] [ShareReceiver] Monitoring external stratum tcp://10.11.1.3:6000 using Curve public-key 622a69b55eef718fcad7f38830014a2a878faa79bba14bdb37fc142d                                      6b21e75a
[2018-10-10 17:15:27.6154] [E] [ShareReceiver] EAGAIN(11): Resource temporarily unavailable EAGAIN(11): Resource temporarily unavailable    at ZeroMQ.ZSocket.ReceiveMessage(Z                                      SocketFlags flags)
   at Miningcore.Mining.ShareReceiver.<>c__DisplayClass8_1.<StartListeners>b__2() in /home/userA/miningcore/src/Miningcore/Mining/ShareReceiver.cs:line 94
[2018-10-10 17:15:27.6154] [I] [ShareReceiver] Monitoring external stratum tcp://10.11.1.3:6000 using Curve public-key 622a69b55eef718fcad7f38830014a2a878faa79bba14bdb37fc142d                                      6b21e75a
[2018-10-10 17:15:37.3845] [I] [StatsRecorder] Updating hashrates for pool dash
[2018-10-10 17:16:27.6317] [E] [ShareReceiver] EAGAIN(11): Resource temporarily unavailable EAGAIN(11): Resource temporarily unavailable    at ZeroMQ.ZSocket.ReceiveMessage(Z                                      SocketFlags flags)
   at Miningcore.Mining.ShareReceiver.<>c__DisplayClass8_1.<StartListeners>b__2() in /home/userA/miningcore/src/Miningcore/Mining/ShareReceiver.cs:line 94
[2018-10-10 17:16:27.6317] [I] [ShareReceiver] Monitoring external stratum tcp://10.11.1.3:6000 using Curve public-key 622a69b55eef718fcad7f38830014a2a878faa79bba14bdb37fc142d                                      6b21e75a
[2018-10-10 17:17:10.6710] [I] [dash] Detected new block 951639 via ZMQ pub/sub
[2018-10-10 17:17:27.6937] [E] [ShareReceiver] EAGAIN(11): Resource temporarily unavailable EAGAIN(11): Resource temporarily unavailable    at ZeroMQ.ZSocket.ReceiveMessage(Z                                      SocketFlags flags)
   at Miningcore.Mining.ShareReceiver.<>c__DisplayClass8_1.<StartListeners>b__2() in /home/userA/miningcore/src/Miningcore/Mining/ShareReceiver.cs:line 94
[2018-10-10 17:17:27.6937] [I] [ShareReceiver] Monitoring external stratum tcp://10.11.1.3:6000 using Curve public-key 622a69b55eef718fcad7f38830014a2a878faa79bba14bdb37fc142d                                      6b21e75a
[2018-10-10 17:18:27.7103] [E] [ShareReceiver] EAGAIN(11): Resource temporarily unavailable EAGAIN(11): Resource temporarily unavailable    at ZeroMQ.ZSocket.ReceiveMessage(Z                                      SocketFlags flags)
   at Miningcore.Mining.ShareReceiver.<>c__DisplayClass8_1.<StartListeners>b__2() in /home/userA/miningcore/src/Miningcore/Mining/ShareReceiver.cs:line 94
[2018-10-10 17:18:27.7115] [I] [ShareReceiver] Monitoring external stratum tcp://10.11.1.3:6000 using Curve public-key 622a69b55eef718fcad7f38830014a2a878faa79bba14bdb37fc142d                                      6b21e75a
[2018-10-10 17:18:54.5957] [I] [dash] Detected new block 951640 via ZMQ pub/sub
[2018-10-10 17:19:27.7721] [E] [ShareReceiver] EAGAIN(11): Resource temporarily unavailable EAGAIN(11): Resource temporarily unavailable    at ZeroMQ.ZSocket.ReceiveMessage(Z                                      SocketFlags flags)
   at Miningcore.Mining.ShareReceiver.<>c__DisplayClass8_1.<StartListeners>b__2() in /home/userA/miningcore/src/Miningcore/Mining/ShareReceiver.cs:line 94
[2018-10-10 17:19:27.7721] [I] [ShareReceiver] Monitoring external stratum tcp://10.11.1.3:6000 using Curve public-key 622a69b55eef718fcad7f38830014a2a878faa79bba14bdb37fc142d                                      6b21e75a

core log from slave
====================

 ███╗   ███╗██╗███╗   ██╗██╗███╗   ██╗ ██████╗  ██████╗ ██████╗ ██████╗ ███████╗
 ████╗ ████║██║████╗  ██║██║████╗  ██║██╔════╝ ██╔════╝██╔═══██╗██╔══██╗██╔════╝
 ██╔████╔██║██║██╔██╗ ██║██║██╔██╗ ██║██║  ███╗██║     ██║   ██║██████╔╝█████╗
 ██║╚██╔╝██║██║██║╚██╗██║██║██║╚██╗██║██║   ██║██║     ██║   ██║██╔══██╗██╔══╝
 ██║ ╚═╝ ██║██║██║ ╚████║██║██║ ╚████║╚██████╔╝╚██████╗╚██████╔╝██║  ██║███████╗

 https://github.com/coinfoundry/miningcore

 Please contribute to the development of the project by donating:

 BTC  - 17QnVor1B6oK1rWnVVBrdX9gFzVkZZbhDm
 LTC  - LTK6CWastkmBzGxgQhTTtCUjkjDA14kxzC
 DASH - XqpBAV9QCaoLnz42uF5frSSfrJTrqHoxjp
 ZEC  - t1YHZHz2DGVMJiggD2P4fBQ2TAPgtLSUwZ7
 ZCL  - t1MFU1vD3YKgsK6Uh8hW7UTY8mKAV2xVqBr
 ETH  - 0xcb55abBfe361B12323eb952110cE33d5F28BeeE1
 ETC  - 0xF8cCE9CE143C68d3d4A7e6bf47006f21Cfcf93c0
 XMR  - 475YVJbPHPedudkhrcNp1wDcLMTGYusGPF5fqE7XjnragVLPdqbCHBdZg3dF4dN9hXMjjvGbykS6a77dTAQvGrpiQqHp2eH

Using configuration file dashslave.json

[2018-10-10 18:26:14.8546] [I] [Core] .NET Core 4.6.26919.02 on Linux 4.15.0-1021-gcp #22~16.04.1-Ubuntu SMP Wed Sep 26 06:08:54 UTC 2018 [X64]
[2018-10-10 18:26:15.0626] [I] [Core] 38 coins loaded from  /home/userA/miningcore/build/coins.json
[2018-10-10 18:26:15.2359] [I] [ShareRecorder] Online
[2018-10-10 18:26:15.2401] [I] [Core] Payment processing is not enabled
[2018-10-10 18:26:15.2448] [I] [StatsRecorder] Online
[2018-10-10 18:26:15.2834] [I] [dash] Starting Pool ...
[2018-10-10 18:26:15.3421] [I] [dash] Starting Job Manager ...
[2018-10-10 18:26:15.5404] [I] [dash] All daemons online
[2018-10-10 18:26:15.6120] [I] [dash] All daemons synched with blockchain
[2018-10-10 18:26:15.7309] [I] [dash] Subscribing to ZMQ push-updates from (tcp://10.11.1.4:15101, hashblock)
[2018-10-10 18:26:15.7679] [I] [dash] Job Manager Online
[2018-10-10 18:26:16.9022] [I] [dash] Detected new block 951666 via Initial template
[2018-10-10 18:26:16.9129] [I] [dash] Broadcasting job
[2018-10-10 18:26:16.9257] [W] [dash] Unable to load pool stats System.NotImplementedException: The method or operation is not implemented.
   at Miningcore.Persistence.Dummy.DummyConnectionFactory.OpenConnection() in /home/userA/miningcore/src/Miningcore/Persistence/Dummy/DummyConnectionFactory.cs:line 38
   at Miningcore.Extensions.ConnectionFactoryExtensions.Run[T](IConnectionFactory factory, Func`2 action) in /home/userA/miningcore/src/Miningcore/Extensions/ConnectionFactoryExtensions.cs:line 49
   at Miningcore.Mining.PoolBase.LoadStats() in /home/userA/miningcore/src/Miningcore/Mining/PoolBase.cs:line 273    at Miningcore.Persistence.Dummy.DummyConnectionFactory.OpenConnection() in /home/userA/miningcore/src/Miningcore/Persistence/Dummy/DummyConnectionFactory.cs:line 38
   at Miningcore.Extensions.ConnectionFactoryExtensions.Run[T](IConnectionFactory factory, Func`2 action) in /home/userA/miningcore/src/Miningcore/Extensions/ConnectionFactoryExtensions.cs:line 49
   at Miningcore.Mining.PoolBase.LoadStats() in /home/userA/miningcore/src/Miningcore/Mining/PoolBase.cs:line 273
[2018-10-10 18:26:16.9369] [I] [dash] Pool Online
[2018-10-10 18:26:16.9430] [I] [dash]

Mining Pool:            dash
Coin Type:              DASH [DASH]
Network Connected:      Main
Detected Reward Type:   POW
Current Block Height:   951666
Current Connect Peers:  16
Network Difficulty:     86561884.1221157
Network Hash Rate:      0 KH/s
Stratum Port(s):        3082
Pool Fee:               0.75%

[2018-10-10 18:26:16.9614] [I] [dash] Stratum ports 0.0.0.0:3082 online
[2018-10-10 18:26:25.2534] [I] [StatsRecorder] Updating hashrates for pool dash
[2018-10-10 18:26:25.2637] [E] [StatsRecorder] System.NotImplementedException: The method or operation is not implemented.
   at Miningcore.Persistence.Dummy.DummyConnectionFactory.OpenConnection() in /home/userA/miningcore/src/Miningcore/Persistence/Dummy/DummyConnectionFactory.cs:line 38
   at Miningcore.Extensions.ConnectionFactoryExtensions.Run[T](IConnectionFactory factory, Func`2 action) in /home/userA/miningcore/src/Miningcore/Extensions/ConnectionFactoryExtensions.cs:line 49
   at Polly.Policy.<>c__DisplayClass150_0`1.<Execute>b__0(Context ctx, CancellationToken ct)
   at Polly.Policy.<>c__DisplayClass143_0`1.<ExecuteInternal>b__0(Context ctx, CancellationToken ct)
   at Polly.RetrySyntax.<>c__DisplayClass5_1.<Retry>b__1(Context ctx, CancellationToken ct)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, IEnumerable`1 shouldRetryExceptionPredicates, IEnumerable`1 shouldRetryResultPredicates, Func`1 policyStateFactory)
   at Polly.RetrySyntax.<>c__DisplayClass5_0.<Retry>b__0(Action`2 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.ExecuteInternal[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Miningcore.Mining.StatsRecorder.UpdatePoolHashrates()
   at Miningcore.Mining.StatsRecorder.<Start>b__19_1() in /home/userA/miningcore/src/Miningcore/Mining/StatsRecorder.cs:line 93 System.NotImplementedException: The method or operation is not implemented.
   at Miningcore.Persistence.Dummy.DummyConnectionFactory.OpenConnection() in /home/userA/miningcore/src/Miningcore/Persistence/Dummy/DummyConnectionFactory.cs:line 38
   at Miningcore.Extensions.ConnectionFactoryExtensions.Run[T](IConnectionFactory factory, Func`2 action) in /home/userA/miningcore/src/Miningcore/Extensions/ConnectionFactoryExtensions.cs:line 49
   at Polly.Policy.<>c__DisplayClass150_0`1.<Execute>b__0(Context ctx, CancellationToken ct)
   at Polly.Policy.<>c__DisplayClass143_0`1.<ExecuteInternal>b__0(Context ctx, CancellationToken ct)
   at Polly.RetrySyntax.<>c__DisplayClass5_1.<Retry>b__1(Context ctx, CancellationToken ct)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, IEnumerable`1 shouldRetryExceptionPredicates, IEnumerable`1 shouldRetryResultPredicates, Func`1 policyStateFactory)
   at Polly.RetrySyntax.<>c__DisplayClass5_0.<Retry>b__0(Action`2 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.ExecuteInternal[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Miningcore.Mining.StatsRecorder.UpdatePoolHashrates()
   at Miningcore.Mining.StatsRecorder.<Start>b__19_1() in /home/userA/miningcore/src/Miningcore/Mining/StatsRecorder.cs:line 93    at Miningcore.Persistence.Dummy.DummyConnectionFactory.OpenConnection() in /home/userA/miningcore/src/Miningcore/Persistence/Dummy/DummyConnectionFactory.cs:line 38
   at Miningcore.Extensions.ConnectionFactoryExtensions.Run[T](IConnectionFactory factory, Func`2 action) in /home/userA/miningcore/src/Miningcore/Extensions/ConnectionFactoryExtensions.cs:line 49
   at Polly.Policy.<>c__DisplayClass150_0`1.<Execute>b__0(Context ctx, CancellationToken ct)
   at Polly.Policy.<>c__DisplayClass143_0`1.<ExecuteInternal>b__0(Context ctx, CancellationToken ct)
   at Polly.RetrySyntax.<>c__DisplayClass5_1.<Retry>b__1(Context ctx, CancellationToken ct)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, IEnumerable`1 shouldRetryExceptionPredicates, IEnumerable`1 shouldRetryResultPredicates, Func`1 policyStateFactory)
   at Polly.RetrySyntax.<>c__DisplayClass5_0.<Retry>b__0(Action`2 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.ExecuteInternal[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Miningcore.Mining.StatsRecorder.UpdatePoolHashrates()
   at Miningcore.Mining.StatsRecorder.<Start>b__19_1() in /home/userA/miningcore/src/Miningcore/Mining/StatsRecorder.cs:line 93
[2018-10-10 18:26:25.8578] [I] [dash] Broadcasting job
[2018-10-10 18:26:35.8602] [I] [dash] Broadcasting job
[2018-10-10 18:26:45.8738] [I] [dash] Broadcasting job
[2018-10-10 18:26:55.7941] [I] [dash] Detected new block 951667 via ZMQ pub/sub
[2018-10-10 18:26:55.7960] [I] [dash] Broadcasting job
[2018-10-10 18:27:05.7961] [I] [dash] Broadcasting job
[2018-10-10 18:27:15.7985] [I] [dash] Broadcasting job
[2018-10-10 18:27:25.7979] [I] [dash] Broadcasting job
[2018-10-10 18:27:35.8029] [I] [dash] Broadcasting job
[2018-10-10 18:27:45.8063] [I] [dash] Broadcasting job
[2018-10-10 18:27:55.8082] [I] [dash] Broadcasting job
[2018-10-10 18:28:05.8083] [I] [dash] Broadcasting job
[2018-10-10 18:28:15.8074] [I] [dash] Broadcasting job
[2018-10-10 18:28:25.8122] [I] [dash] Broadcasting job
[2018-10-10 18:28:35.8096] [I] [dash] Broadcasting job
[2018-10-10 18:28:45.8149] [I] [dash] Broadcasting job
[2018-10-10 18:28:55.8130] [I] [dash] Broadcasting job
[2018-10-10 18:29:05.8119] [I] [dash] Broadcasting job
[2018-10-10 18:29:15.8144] [I] [dash] Broadcasting job
[2018-10-10 18:29:25.8133] [I] [dash] Broadcasting job
[2018-10-10 18:29:35.8169] [I] [dash] Broadcasting job

**Comment by oliverw** [comment]
This warning is harmless and will go away in the next release.
