### ISSUE TITLE
Unable to find an entry point named 'equihash_verify_export' inshared library 'libmultihash'

### ISSUE THREAD

**Issue by RakaMaru** [coinfoundry/miningcore#433]
## Note
When a share is submitted in a ZCash pool, I get this error. It cannot find the entry point named 'equihash_verify_export'

### Description

Error is thrown and miner gets disconnected.

### Steps to Reproduce

1. Start zcashd
2. Run miningcore
3. Run a miner and wait until the share is submitted

### Expected behavior

'equihash_verify_export' should be found and no error happens.

### Actual behavior

The error occurs and the miner gets disconnected and then reconnects until this happens again in the next share found.

### Reproduces how often

100%

### Version

master, tag: v40, origin/master

Running on Ubuntu 18.04

### Additional Information

[2018-10-19 18:29:40.5476] [E] [zec1] [0HLHM8ICQ2ISF] Connection error state: System.EntryPointNotFoundException: Unable to find an entry point named 'equihash_verify_export' inshared library 'libmultihash'.
   at MiningCore.Native.LibMultihash.equihash_verify(Byte* header, Int32 headerLength, Byte* solution, Int32 solutionLength)
   at MiningCore.Crypto.Hashing.Equihash.EquihashSolver_ZCash.Verify(Byte[] header, Byte[] solution) in /home/rakamaru/source/miningcore/src/MiningCore/Crypto/Hashing/Equihash/EquihashSolver.cs:line 79
   at MiningCore.Blockchain.ZCash.ZCashJob.ProcessShareInternal(StratumClient worker, String nonce, UInt32 nTime, String solution) in /home/rakamaru/source/miningcore/src/MiningCore/Blockchain/ZCash/ZCashJob.cs:line 348
   at MiningCore.Blockchain.ZCash.ZCashJob.ProcessShare(StratumClient worker, String extraNonce2, String nTime, String solution) in /home/rakamaru/source/miningcore/src/MiningCore/Blockchain/ZCash/ZCashJob.cs:line 298
   at MiningCore.Blockchain.ZCash.ZCashJobManager`1.SubmitShareAsync(StratumClient worker, Object submission, Double stratumDifficultyBase, CancellationToken ct) in /home/rakamaru/source/miningcore/src/MiningCore/Blockchain/ZCash/ZCashJobManager.cs:line 174
   at MiningCore.Blockchain.Bitcoin.BitcoinPoolBase`2.OnSubmitAsync(StratumClient client, Timestamped`1 tsRequest, CancellationToken ct) in /home/rakamaru/source/miningcore/src/MiningCore/Blockchain/Bitcoin/BitcoinPoolBase.cs:line 187
   at MiningCore.Blockchain.ZCash.ZCashPoolBase`1.OnRequestAsync(StratumClient client, Timestamped`1 tsRequest, CancellationToken ct) in /home/rakamaru/source/miningcore/src/MiningCore/Blockchain/ZCash/ZCashPoolBase.cs:line 177
   at MiningCore.Stratum.StratumServer.OnRequestAsync(StratumClient client, JsonRpcRequest request, CancellationToken ct) in /home/rakamaru/source/miningcore/src/MiningCore/Stratum/StratumServer.cs:line 250
   at MiningCore.Stratum.StratumClient.ProcessRequestAsync(Func`4 onRequestAsync, ReadOnlySequence`1 lineBuffer) in /home/rakamaru/source/miningcore/src/MiningCore/Stratum/StratumClient.cs:line 374
   at MiningCore.Stratum.StratumClient.ProcessReceivePipeAsync(TcpProxyProtocolConfig proxyProtocol, Func`4 onRequestAsync) in /home/rakamaru/source/miningcore/src/MiningCore/Stratum/StratumClient.cs:line 320

**Comment by oliverw** [comment]
It doesn't look like you are really running Release 40. I can tell by the namespace "MiningCore.Native" in the callstack. The camel-casing of "MiningCore" was dropped some releases ago. Now its "Miningcore.Native". Could you try with a recent release?

**Comment by RakaMaru** [comment]
Thank you @oliverw, I'll delete and re-install the master version and try again.
