### ISSUE TITLE
Payment processing failed System.NullReferenceException

### ISSUE THREAD

**Issue by Konstantin35** [coinfoundry/miningcore#447]
Testing geth faced with such an error

```
[2018-10-26 16:06:11.7300] [E] [PayoutManager] [gol1] Payment processing failed System.NullReferenceException: Object reference not set to an instance of an object.
   at Miningcore.Blockchain.Ethereum.EthereumPayoutHandler.ClassifyBlocksAsync(Block[] blocks) in /home/user/NEW/miningcore/src/Miningcore/Blockchain/Ethereum/EthereumPayoutHandler.cs:line 152
   at Miningcore.Payments.PayoutManager.UpdatePoolBalancesAsync(PoolConfig pool, IPayoutHandler handler, IPayoutScheme scheme) in /home/user/NEW/miningcore/src/Miningcore/Payments/PayoutManager.cs:line 136
   at Miningcore.Payments.PayoutManager.ProcessPoolsAsync() in /home/user/NEW/miningcore/src/Miningcore/Payments/PayoutManager.cs:line 98    at Miningcore.Blockchain.Ethereum.EthereumPayoutHandler.ClassifyBlocksAsync(Block[] blocks) in /home/user/NEW/miningcore/src/Miningcore/Blockchain/Ethereum/EthereumPayoutHandler.cs:line 152
   at Miningcore.Payments.PayoutManager.UpdatePoolBalancesAsync(PoolConfig pool, IPayoutHandler handler, IPayoutScheme scheme) in /home/user/NEW/miningcore/src/Miningcore/Payments/PayoutManager.cs:line 136
   at Miningcore.Payments.PayoutManager.ProcessPoolsAsync() in /home/user/NEW/miningcore/src/Miningcore/Payments/PayoutManager.cs:line 98
```

`./geth --datadir /home/user/db -rpc --ws --wsorigins="*" `

```
"EnableDaemonWebsocketStreaming": true,
"daemons": [
	{
		"host": "127.0.0.1",
		"port": 2009,
		"portWs": 2018
		
	}
],
"paymentProcessing": {
	"enabled": true,
	"minimumPayment": 0.01,
	"payoutScheme": "PPLNS",
	"payoutSchemeConfig": {
		"factor": 0.1
	},
	"coinbasePassword": "pass",
	"keepUncles": false,
	"keepTransactionFees": false
}
```

there is also a problem with payments
`System.Exception: Unable to unlock coinbase account for sending transaction`

different coins of different reward per block would be good if the reward per block was exhibited in coins.json

**Comment by fathusband** [comment]
have you try to add --wsport in your geth? by default it listen on port 8546

https://github.com/ethereum/go-ethereum/wiki/Command-Line-Options

**Comment by Konstantin35** [comment]
I use a coin to test Goldiam her default `--wsport 2018`

**Comment by oliverw** [comment]
@Konstantin35 I need more info here. Any chance for you run this in the debugger?

**Comment by Konstantin35** [comment]
How to make it better tell me

**Comment by oliverw** [comment]
Umm, what?

**Comment by Konstantin35** [comment]
What kind of information do you need to understand what's going on

**Comment by oliverw** [comment]
Why did you close it?

**Comment by Konstantin35** [comment]
Without the support of the geth isn't working for me

**Comment by Konstantin35** [comment]
I made some changes and tested one coin everything works fine
[https://github.com/Konstantin35/miningcore](https://github.com/Konstantin35/miningcore)
