### ISSUE TITLE
Can not read RCP Json Difficulty

### ISSUE THREAD

**Issue by codefrx** [coinfoundry/miningcore#470]
[Description of the issue]
RCP Client on IgnitionCoin for example, response an array on difficulty:
￼
{
    "blocks" : 292896,
    "currentblocksize" : 2109,
    "currentblocktx" : 2,
    "difficulty" : {
        "proof-of-work" : 19.43194771,
        "proof-of-stake" : 206944.73437500,
        "search-interval" : 16
    },
    "blockvalue" : 95000000,
    "netmhashps" : 463.66431365,
    "netstakeweight" : 37192768469813.56250000,
    "errors" : "",
    "pooledtx" : 2,
    "stakeweight" : {
        "minimum" : 0,
        "maximum" : 0,
        "combined" : 0
    },
    "testnet" : false
}

Maybe thats why Miningcore throw an error?

 Newtonsoft.Json.JsonReaderException: Error reading double. Unexpected token: StartObject. Path 'difficulty'.

### Steps to Reproduce
getmininginfo rcp command, response an array on difficulty parameter:

"difficulty" : {
"proof-of-work" : 19.43194771,
"proof-of-stake" : 206944.73437500,
"search-interval" : 16
},

### Expected behavior

Miningcore reads PoW difficulty correctly.

### Actual behavior

throw an error:
 Newtonsoft.Json.JsonReaderException: Error reading double. Unexpected token: StartObject. Path 'difficulty'.

### Reproduces how often
100%

### Version
Release 44.
Net Core 2.1 on Windows.

**Comment by codefrx** [comment]
this is the log:
`
[2018-11-13 14:12:47.9925] [E] [IC] Newtonsoft.Json.JsonReaderException: Error reading double. Unexpected token: StartObject. Path 'difficulty'.
   at Newtonsoft.Json.JsonReader.ReadAsDouble()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
   at Miningcore.DaemonInterface.DaemonClient.MapDaemonResponse[TResponse](Int32 i, Task`1 x, Boolean throwOnError) in C:\MiningCore\DaemonInterface\DaemonClient.cs:line 470
   at Miningcore.DaemonInterface.DaemonClient.<>c__DisplayClass11_0`1.<ExecuteCmdAllAsync>b__1(Task`1 x, Int32 i) in C:\MiningCore\DaemonInterface\DaemonClient.cs:line 162
   at System.Linq.Enumerable.SelectIterator[TSource,TResult](IEnumerable`1 source, Func`3 selector)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Miningcore.DaemonInterface.DaemonClient.ExecuteCmdAllAsync[TResponse](ILogger logger, String method, Object payload, JsonSerializerSettings payloadJsonSerializerSettings)
   at Miningcore.Blockchain.Bitcoin.BitcoinJobManagerBase`1.AreDaemonsHealthyLegacyAsync() in C:\MiningCore\Blockchain\Bitcoin\BitcoinJobManagerBase.cs:line 324
   at Miningcore.Blockchain.Bitcoin.BitcoinJobManagerBase`1.AreDaemonsHealthyAsync() in C:\MiningCore\Blockchain\Bitcoin\BitcoinJobManagerBase.cs:line 411
   at Miningcore.Blockchain.JobManagerBase`1.StartDaemonAsync(CancellationToken ct) in C:\MiningCore\Blockchain\JobManagerBase.cs:line 70
   at Miningcore.Blockchain.JobManagerBase`1.StartAsync(CancellationToken ct) in C:\MiningCore\Blockchain\JobManagerBase.cs:line 133
   at Miningcore.Blockchain.Bitcoin.BitcoinPool.SetupJobManager(CancellationToken ct) in C:\MiningCore\Blockchain\Bitcoin\BitcoinPool.cs:line 389
   at Miningcore.Mining.PoolBase.StartAsync(CancellationToken ct) in C:\MiningCore\Mining\PoolBase.cs:line 375 Newtonsoft.Json.JsonReaderException: Error reading double. Unexpected token: StartObject. Path 'difficulty'.
   at Newtonsoft.Json.JsonReader.ReadAsDouble()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
   at Miningcore.DaemonInterface.DaemonClient.MapDaemonResponse[TResponse](Int32 i, Task`1 x, Boolean throwOnError) in C:\MiningCore\DaemonInterface\DaemonClient.cs:line 470
   at Miningcore.DaemonInterface.DaemonClient.<>c__DisplayClass11_0`1.<ExecuteCmdAllAsync>b__1(Task`1 x, Int32 i) in C:\MiningCore\DaemonInterface\DaemonClient.cs:line 162
   at System.Linq.Enumerable.SelectIterator[TSource,TResult](IEnumerable`1 source, Func`3 selector)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Miningcore.DaemonInterface.DaemonClient.ExecuteCmdAllAsync[TResponse](ILogger logger, String method, Object payload, JsonSerializerSettings payloadJsonSerializerSettings)
   at Miningcore.Blockchain.Bitcoin.BitcoinJobManagerBase`1.AreDaemonsHealthyLegacyAsync() in C:\MiningCore\Blockchain\Bitcoin\BitcoinJobManagerBase.cs:line 324
   at Miningcore.Blockchain.Bitcoin.BitcoinJobManagerBase`1.AreDaemonsHealthyAsync() in C:\MiningCore\Blockchain\Bitcoin\BitcoinJobManagerBase.cs:line 411
   at Miningcore.Blockchain.JobManagerBase`1.StartDaemonAsync(CancellationToken ct) in C:\MiningCore\Blockchain\JobManagerBase.cs:line 70
   at Miningcore.Blockchain.JobManagerBase`1.StartAsync(CancellationToken ct) in C:\MiningCore\Blockchain\JobManagerBase.cs:line 133
   at Miningcore.Blockchain.Bitcoin.BitcoinPool.SetupJobManager(CancellationToken ct) in C:\MiningCore\Blockchain\Bitcoin\BitcoinPool.cs:line 389
   at Miningcore.Mining.PoolBase.StartAsync(CancellationToken ct) in C:\MiningCore\Mining\PoolBase.cs:line 375    at Newtonsoft.Json.JsonReader.ReadAsDouble()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
   at Miningcore.DaemonInterface.DaemonClient.MapDaemonResponse[TResponse](Int32 i, Task`1 x, Boolean throwOnError) in C:\MiningCore\DaemonInterface\DaemonClient.cs:line 470
   at Miningcore.DaemonInterface.DaemonClient.<>c__DisplayClass11_0`1.<ExecuteCmdAllAsync>b__1(Task`1 x, Int32 i) in C:\MiningCore\DaemonInterface\DaemonClient.cs:line 162
   at System.Linq.Enumerable.SelectIterator[TSource,TResult](IEnumerable`1 source, Func`3 selector)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Miningcore.DaemonInterface.DaemonClient.ExecuteCmdAllAsync[TResponse](ILogger logger, String method, Object payload, JsonSerializerSettings payloadJsonSerializerSettings)
   at Miningcore.Blockchain.Bitcoin.BitcoinJobManagerBase`1.AreDaemonsHealthyLegacyAsync() in C:\MiningCore\Blockchain\Bitcoin\BitcoinJobManagerBase.cs:line 324
   at Miningcore.Blockchain.Bitcoin.BitcoinJobManagerBase`1.AreDaemonsHealthyAsync() in C:\MiningCore\Blockchain\Bitcoin\BitcoinJobManagerBase.cs:line 411
   at Miningcore.Blockchain.JobManagerBase`1.StartDaemonAsync(CancellationToken ct) in C:\MiningCore\Blockchain\JobManagerBase.cs:line 70
   at Miningcore.Blockchain.JobManagerBase`1.StartAsync(CancellationToken ct) in C:\MiningCore\Blockchain\JobManagerBase.cs:line 133
   at Miningcore.Blockchain.Bitcoin.BitcoinPool.SetupJobManager(CancellationToken ct) in C:\MiningCore\Blockchain\Bitcoin\BitcoinPool.cs:line 389
   at Miningcore.Mining.PoolBase.StartAsync(CancellationToken ct) in C:\MiningCore\Mining\PoolBase.cs:line 375
System.AggregateException: One or more errors occurred. (Error reading double. Unexpected token: StartObject. Path 'difficulty'.) ---> Newtonsoft.Json.JsonReaderException: Error reading double. Unexpected token: StartObject. Path 'difficulty'.
   at Newtonsoft.Json.JsonReader.ReadAsDouble()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
   at Miningcore.DaemonInterface.DaemonClient.MapDaemonResponse[TResponse](Int32 i, Task`1 x, Boolean throwOnError) in C:\MiningCore\DaemonInterface\DaemonClient.cs:line 470
   at Miningcore.DaemonInterface.DaemonClient.<>c__DisplayClass11_0`1.<ExecuteCmdAllAsync>b__1(Task`1 x, Int32 i) in C:\MiningCore\DaemonInterface\DaemonClient.cs:line 162
   at System.Linq.Enumerable.SelectIterator[TSource,TResult](IEnumerable`1 source, Func`3 selector)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Miningcore.DaemonInterface.DaemonClient.ExecuteCmdAllAsync[TResponse](ILogger logger, String method, Object payload, JsonSerializerSettings payloadJsonSerializerSettings)
   at Miningcore.Blockchain.Bitcoin.BitcoinJobManagerBase`1.AreDaemonsHealthyLegacyAsync() in C:\MiningCore\Blockchain\Bitcoin\BitcoinJobManagerBase.cs:line 324
   at Miningcore.Blockchain.Bitcoin.BitcoinJobManagerBase`1.AreDaemonsHealthyAsync() in C:\MiningCore\Blockchain\Bitcoin\BitcoinJobManagerBase.cs:line 411
   at Miningcore.Blockchain.JobManagerBase`1.StartDaemonAsync(CancellationToken ct) in C:\MiningCore\Blockchain\JobManagerBase.cs:line 70
   at Miningcore.Blockchain.JobManagerBase`1.StartAsync(CancellationToken ct) in C:\MiningCore\Blockchain\JobManagerBase.cs:line 133
   at Miningcore.Blockchain.Bitcoin.BitcoinPool.SetupJobManager(CancellationToken ct) in C:\MiningCore\Blockchain\Bitcoin\BitcoinPool.cs:line 389
   at Miningcore.Mining.PoolBase.StartAsync(CancellationToken ct) in C:\MiningCore\Mining\PoolBase.cs:line 375
   at Miningcore.Program.<>c.<<Start>b__40_2>d.MoveNext() in C:\MiningCore\Program.cs:line 841
--- End of stack trace from previous location where exception was thrown ---
   at Miningcore.Program.Start() in C:\MiningCore\Program.cs:line 825
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Miningcore.Program.Main(String[] args) in C:\MiningCore\Program.cs:line 108
---> (Inner Exception #0) Newtonsoft.Json.JsonReaderException: Error reading double. Unexpected token: StartObject. Path 'difficulty'.
   at Newtonsoft.Json.JsonReader.ReadAsDouble()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
   at Miningcore.DaemonInterface.DaemonClient.MapDaemonResponse[TResponse](Int32 i, Task`1 x, Boolean throwOnError) in C:\MiningCore\DaemonInterface\DaemonClient.cs:line 470
   at Miningcore.DaemonInterface.DaemonClient.<>c__DisplayClass11_0`1.<ExecuteCmdAllAsync>b__1(Task`1 x, Int32 i) in C:\MiningCore\DaemonInterface\DaemonClient.cs:line 162
   at System.Linq.Enumerable.SelectIterator[TSource,TResult](IEnumerable`1 source, Func`3 selector)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Miningcore.DaemonInterface.DaemonClient.ExecuteCmdAllAsync[TResponse](ILogger logger, String method, Object payload, JsonSerializerSettings payloadJsonSerializerSettings)
   at Miningcore.Blockchain.Bitcoin.BitcoinJobManagerBase`1.AreDaemonsHealthyLegacyAsync() in C:\MiningCore\Blockchain\Bitcoin\BitcoinJobManagerBase.cs:line 324
   at Miningcore.Blockchain.Bitcoin.BitcoinJobManagerBase`1.AreDaemonsHealthyAsync() in C:\MiningCore\Blockchain\Bitcoin\BitcoinJobManagerBase.cs:line 411
   at Miningcore.Blockchain.JobManagerBase`1.StartDaemonAsync(CancellationToken ct) in C:\MiningCore\Blockchain\JobManagerBase.cs:line 70
   at Miningcore.Blockchain.JobManagerBase`1.StartAsync(CancellationToken ct) in C:\MiningCore\Blockchain\JobManagerBase.cs:line 133
   at Miningcore.Blockchain.Bitcoin.BitcoinPool.SetupJobManager(CancellationToken ct) in C:\MiningCore\Blockchain\Bitcoin\BitcoinPool.cs:line 389
   at Miningcore.Mining.PoolBase.StartAsync(CancellationToken ct) in C:\MiningCore\Mining\PoolBase.cs:line 375
   at Miningcore.Program.<>c.<<Start>b__40_2>d.MoveNext() in C:\MiningCore\Program.cs:line 841
--- End of stack trace from previous location where exception was thrown ---
   at Miningcore.Program.Start() in C:\MiningCore\Program.cs:line 825<---

[2018-11-13 14:12:51.8707] [I] [PayoutManager] No updated blocks for pool IC
Cluster cannot start. Good Bye!
[2018-11-13 14:12:53.2826] [I] [Core] Shutdown ...
Shutdown...
`
