### ISSUE TITLE
System.AggregateException: One or more errors occurred.

### ISSUE THREAD

**Issue by edtrade** [coinfoundry/miningcore#478]
Hey guys,
i am getting this error trying to run a peercoin pool
.....
'[ppc1] Starting Pool ... 
[ppc1] Starting Job Manager ... 
[ppc1] All daemons online 
[ppc1] All daemons synched with blockchain 

[ppc1] System.AggregateException: One or more errors occurred. (Value cannot be null.
Parameter name: encoded) ---> System.ArgumentNullException: Value cannot be null.
Parameter name: encoded
   at NBitcoin.DataEncoders.HexEncoder.DecodeData(String encoded)
   at Miningcore.Blockchain.Bitcoin.BitcoinJobManagerBase 1.PostStartInitAsync(CancellationToken ct) in /root/miningcore/src/Miningcore/Blockchain/Bitcoin/BitcoinJobManagerBase.cs:line 519
   at Miningcore.Blockchain.JobManagerBase 1.StartAsync(CancellationToken ct) in /root/miningcore/src/Miningcore/Blockchain/JobManagerBase.cs:line 216
   at Miningcore.Blockchain.Bitcoin.BitcoinPool.SetupJobManager(CancellationToken ct) in /root/miningcore/src/Miningcore/Blockchain/Bitcoin/BitcoinPool.cs:line 319
   at Miningcore.Mining.PoolBase.StartAsync(CancellationToken ct) in /root/miningcore/src/Miningcore/Mining/PoolBase.cs:line 375
   at Miningcore.Program.<>c.<<Start>b__39_2>d.MoveNext() in /root/miningcore/src/Miningcore/Program.cs:line 833
--- End of stack trace from previous location where exception was thrown ---
   at Miningcore.Program.Start() in /root/miningcore/src/Miningcore/Program.cs:line 817
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Miningcore.Program.Main(String[] args) in /root/miningcore/src/Miningcore/Program.cs:line 108
---> (Inner Exception #0) System.ArgumentNullException: Value cannot be null.
Parameter name: encoded
   at NBitcoin.DataEncoders.HexEncoder.DecodeData(String encoded)
   at Miningcore.Blockchain.Bitcoin.BitcoinJobManagerBase 1.PostStartInitAsync(CancellationToken ct) in /root/miningcore/src/Miningcore/Blockchain/Bitcoin/BitcoinJobManagerBase.cs:line 519
   at Miningcore.Blockchain.JobManagerBase 1.StartAsync(CancellationToken ct) in /root/miningcore/src/Miningcore/Blockchain/JobManagerBase.cs:line 216
   at Miningcore.Blockchain.Bitcoin.BitcoinPool.SetupJobManager(CancellationToken ct) in /root/miningcore/src/Miningcore/Blockchain/Bitcoin/BitcoinPool.cs:line 319
   at Miningcore.Mining.PoolBase.StartAsync(CancellationToken ct) in /root/miningcore/src/Miningcore/Mining/PoolBase.cs:line 375
   at Miningcore.Program.<>c.<<Start>b__39_2>d.MoveNext() in /root/miningcore/src/Miningcore/Program.cs:line 833
--- End of stack trace from previous location where exception was thrown ---
   at Miningcore.Program.Start() in /root/miningcore/src/Miningcore/Program.cs:line 817<---
`

**Comment by edtrade** [comment]
@oliverw , I don't think so.
don't  know how to run with a segwit address

**Comment by oliverw** [comment]
What the first three characters of the pool address?
