### ISSUE TITLE
miningcore worker authorization Windows 10 Pro 64-bit

### ISSUE THREAD

**Issue by Xerxes7777** [coinfoundry/miningcore#487]
### Description
Mininingcore bans my ASIC Antminer S9i as unathorized user. I can't find any setting or clue where I can register my Antminer S9i so it is Authorized. I am not using any front end GUI for Miningcore.

I have some training in blockchain but no formal training in computer programing.
Platform use: Windows 10 Pro 64-bit
I have successfully changed Miningcore config.json and coins.json after build to accept Californium cryptocurrency which uses SHA256 POW similar to bitcoin. I am trying to connects this Miningcore Stratum server to use ASIC Antminer S9i. So far Californium Wallet v0.9.5.9-CF Node connected running well connecting to Miningcore without error.  PostgreSQL Datatbase set up connecting without error. I am trying to connect my Antminer S9i to Miningcore. It does connect but it gets banned after it connects to miningcore for 60 seconds

How Do I register my Miner or Worker as Authorized user so it does not get banned.
I have disabled all the Banning features in config.json I could find. It still does this.

See Below Miningcore output

 [2018-11-25 08:38:36.0192] [I] [Californium pool] Broadcasting job
[2018-11-25 08:38:46.0225] [I] [Californium pool] Broadcasting job
[2018-11-25 08:38:48.2951] [I] [Californium pool] [0HLIIUHSNBE7H] Connection from ::ffff:192.168.0.152:56401 accepted on port 44260
[2018-11-25 08:38:48.2951] [I] [Californium pool] [0HLIIUHSNBE7F] Connection from ::ffff:192.168.0.152:56399 accepted on port 44260
[2018-11-25 08:38:48.2951] [I] [Californium pool] [0HLIIUHSNBE7G] Connection from ::ffff:192.168.0.152:56400 accepted on port 44260
[2018-11-25 08:38:48.3599] [I] [Californium pool] [0HLIIUHSNBE7G] Banning unauthorized worker for 60 sec
[2018-11-25 08:38:48.3599] [I] [Californium pool] [0HLIIUHSNBE7H] Banning unauthorized worker for 60 sec
[2018-11-25 08:38:48.3599] [I] [Californium pool] [0HLIIUHSNBE7F] Banning unauthorized worker for 60 sec
[2018-11-25 08:38:48.3963] [I] [Californium pool] [0HLIIUHSNBE7H] Connection closed
[2018-11-25 08:38:48.3963] [I] [Californium pool] [0HLIIUHSNBE7G] Connection closed
[2018-11-25 08:38:48.3963] [I] [Californium pool] [0HLIIUHSNBE7F] Connection closed
[2018-11-25 08:38:56.0348] [I] [Californium pool] Broadcasting job
[2018-11-25 08:39:06.0384] [I] [Californium pool] Broadcasting job
[2018-11-25 08:39:16.0412] [I] [Californium pool] Broadcasting job
[2018-11-25 08:39:18.3811] [I] [Californium pool] [0HLIIUHSNBE7I] Connection from ::ffff:192.168.0.152:56402 accepted on port 44260
[2018-11-25 08:39:18.3811] [I] [Californium pool] [0HLIIUHSNBE7J] Connection from ::ffff:192.168.0.152:56403 accepted on port 44260
[2018-11-25 08:39:18.3811] [I] [Californium pool] [0HLIIUHSNBE7K] Connection from ::ffff:192.168.0.152:56405 accepted on port 44260
[2018-11-25 08:39:18.3964] [I] [Californium pool] [0HLIIUHSNBE7I] Banning unauthorized worker for 60 sec
[2018-11-25 08:39:18.3964] [I] [Californium pool] [0HLIIUHSNBE7J] Banning unauthorized worker for 60 sec
[2018-11-25 08:39:18.3964] [I] [Californium pool] [0HLIIUHSNBE7K] Banning unauthorized worker for 60 sec

**Comment by Xerxes7777** [comment]
Thank you for quick feed back I appreciate it.


 With actual values for your coin daemon and miner-address. But he ASIC  miner does not directly connect to the Wallet Daemon address and port . ASIC Miner connects to the Miningcore Address which is the same IP but different port (pool address and port). Correct me if I am wrong. The ASIC miner should connect to miningcore pool address and port.   

The curl --user user:pass --data-binary '{"jsonrpc": "1.0", "id":"1", "method": "validateaddress", "params": ["miner-address"] }' -H 'content-type: application/json;' http://127.0.0.1:8332/ 


gives following response:
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   138  100    51  100    87   3400   5800 --:--:-- --:--:-- --:--:--  9200{"result":{"isvalid":false},"error":null,"id":"1"}

I ran the Coin Wallet Daemon, Miningcore, and ACIC miner again but same problem
I included an additional error message I get which may be helpful. 

Thank you in advance

[2018-11-25 13:44:12.1616] [I] [Californium pool] Broadcasting job
[2018-11-25 13:44:22.1773] [I] [Californium pool] Broadcasting job
[2018-11-25 13:44:32.1495] [I] [Californium pool] [0HLIJ3OCVRMO7] Connection from ::ffff:192.168.0.152:37278 accepted on port 44260
[2018-11-25 13:44:32.1495] [I] [Californium pool] [0HLIJ3OCVRMO8] Connection from ::ffff:192.168.0.152:37279 accepted on port 44260
[2018-11-25 13:44:32.1495] [I] [Californium pool] [0HLIJ3OCVRMO9] Connection from ::ffff:192.168.0.152:37280 accepted on port 44260
[2018-11-25 13:44:32.1639] [I] [Californium pool] [0HLIJ3OCVRMO7] Banning unauthorized worker for 60 sec
[2018-11-25 13:44:32.1639] [E] [Californium pool] [0HLIJ3OCVRMO7] Connection error state: System.NullReferenceException: Object reference not set to an instance of an object.
   at Miningcore.Blockchain.Bitcoin.BitcoinPool.OnAuthorizeAsync(StratumClient client, Timestamped`1 tsRequest, CancellationToken ct) in C:\Users\Dariush\Documents\Blockchain Technology\Mining\Stratum\miningcore-master\miningcore-master\src\Miningcore\Blockchain\Bitcoin\BitcoinPool.cs:line 157
   at Miningcore.Blockchain.Bitcoin.BitcoinPool.OnRequestAsync(StratumClient client, Timestamped`1 tsRequest, CancellationToken ct) in C:\Users\Dariush\Documents\Blockchain Technology\Mining\Stratum\miningcore-master\miningcore-master\src\Miningcore\Blockchain\Bitcoin\BitcoinPool.cs:line 377
   at Miningcore.Stratum.StratumServer.OnRequestAsync(StratumClient client, JsonRpcRequest request, CancellationToken ct) in C:\Users\Dariush\Documents\Blockchain Technology\Mining\Stratum\miningcore-master\miningcore-master\src\Miningcore\Stratum\StratumServer.cs:line 250
   at Miningcore.Stratum.StratumClient.ProcessRequestAsync(Func`4 onRequestAsync, ReadOnlySequence`1 lineBuffer) in C:\Users\Dariush\Documents\Blockchain Technology\Mining\Stratum\miningcore-master\miningcore-master\src\Miningcore\Stratum\StratumClient.cs:line 376
   at Miningcore.Stratum.StratumClient.ProcessReceivePipeAsync(TcpProxyProtocolConfig proxyProtocol, Func`4 onRequestAsync) in C:\Users\Dariush\Documents\Blockchain Technology\Mining\Stratum\miningcore-master\miningcore-master\src\Miningcore\Stratum\StratumClient.cs:line 321
[2018-11-25 13:44:32.1712] [I] [Californium pool] [0HLIJ3OCVRMO8] Banning unauthorized worker for 60 sec
[2018-11-25 13:44:32.1712] [I] [Californium pool] [0HLIJ3OCVRMO9] Banning unauthorized worker for 60 sec
[2018-11-25 13:44:32.1712] [I] [Californium pool] [0HLIJ3OCVRMO8] Connection closed
[2018-11-25 13:44:32.1712] [I] [Californium pool] Broadcasting job
[2018-11-25 13:44:32.1712] [I] [Californium pool] [0HLIJ3OCVRMO7] Connection closed
[2018-11-25 13:44:32.1937] [I] [Californium pool] [0HLIJ3OCVRMO9] Connection closed
[2018-11-25 13:44:42.1923] [I] [Californium pool] Broadcasting job
[2018-11-25 13:44:52.1947] [I] [Californium pool] Broadcasting job
[2018-11-25 13:44:57.8177] [I] [Californium pool] Detected new block 731615 via RPC polling
[2018-11-25 13:44:57.8177] [I] [Californium pool] Broadcasting job
[2018-11-25 13:45:02.2035] [I] [Californium pool] Broadcasting job
[2018-11-25 13:45:12.2090] [I] [Californium pool] Broadcasting job

**Comment by oliverw** [comment]
> With actual values for your coin daemon and miner-address. But he ASIC miner does not directly connect to the Wallet Daemon address and port . ASIC Miner connects to the Miningcore Address which is the same IP but different port (pool address and port). Correct me if I am wrong. The ASIC miner should connect to miningcore pool address and port.

Yeah, thanks I know that, I wrote Miningcore. The reason I asked you to run that RPC request was to confirm my assumption that the address you are attempting to mine with, is not considered valid by the coin daemon Miningcore talks to. The result has confirmed that indeed. You are mining with an invalid wallet address for your coin.

**Comment by Xerxes7777** [comment]
I wanted to thank you for writing Miningcore. It is awesome. Thanks for all your hard work. 

oops. I thought you mean ASIC miner IP address not Miner/worker wallet address. So I put an IP address in the Curl command. 
I only found a place to put in pool Wallet address in config.json

So where should I enter the miner wallet address go so it is validated??

Also please let me know how should be the synthax for miner-address. Is it Miner name and miner wallet public address or just the miner wallet public address without miners name.
Thanks

**Comment by Xerxes7777** [comment]
It worked. Thank you very much.
