### ISSUE TITLE
The mining pool installation guide.

### ISSUE THREAD

**Issue by jeong760** [coinfoundry/miningcore#49]
Dears,

I am writing a guide for MiningPoolEngine installation on  Ubuntu 16.04LTS version as following.
Is there anything should I added here?
[MiningPoolEngine_Guide.txt](https://github.com/coinfoundry/miningcore/files/1440035/MiningPoolEngine_Guide.txt)

-------------- Contents ---------------------
0. Update and install of Ubuntu Linux patches
1. Inatllaiton a Microsoft .NET SDK
   1.1 Register the trusted Microsoft signature key:
   1.2 Register the Microsoft Product feed
      1.2.1 Ubuntu 14.04
	  1.2.2 Ubuntu 16.04
	  1.2.3 Ubuntu 17.04
   1.3 Install .NET SDK
2. Intallaiton a PostgreSQL
   2.1 Create a Postgres Database
   2.2 Import a Database Schema
3. Installation a each coin daemon cores 
   3.1 Bitcoin (BTC, BCH)
      3.1.1 Add a PPA repository 
      3.1.2 Create a .bitcoin folder on your home
      3.1.3 
   3.3 DASH
   3.4 Dogecoin
   3.5 Ethereum (ETH,ECC)
   3.6 GobalToken
   
4. Download and build a MiningPoolEngine
   4.1 
   4.2 
   4.3 
   4.4 
   4.5 
   
5. Running a MiningPoolEngine
-------------- End of Contents ------------------

Regards,
John Ahn

**Comment by oliverw** [comment]
Looks good for a first draft. 👍

**Comment by calvintam236** [comment]
Note that this draft looks like for standalone installation. If I have some time later, I would add how to use Docker container to run the pool instead. (Because using docker image is much simpler and faster.)

**Comment by 8bitidea** [comment]
sorry for this question ,
but i need help for this , i followed up this guild to build miningcore 
first there is some syntax error but i figure it out  , that was hard :D 
but now i am stuck with this 
`[2017-12-14 10:17:34.8146] [I] [ShareRecorder] Online 
[2017-12-14 10:17:34.9669] [I] [ApiServer] Launching ... 
[2017-12-14 10:17:35.3326] [I] [ApiServer] Online @ 127.0.0.1:4000 
[2017-12-14 10:17:35.3500] [I] [PayoutManager] Online 
[2017-12-14 10:17:35.3768] [I] [PayoutManager] Processing payments for pool eth1 
[2017-12-14 10:17:35.5033] [I] [eth1] [Pool] Launching ... 
[2017-12-14 10:17:35.7662] [I] [eth1] [Ethereum Job Manager] Launching ... 
[2017-12-14 10:17:35.9856] [E] [PayoutManager] [eth1] Payment processing failed System.Net.Sockets.SocketException (0x80004005): Connection refused
   at Npgsql.NpgsqlConnector.Connect(NpgsqlTimeout timeout)
   at Npgsql.NpgsqlConnector.<RawOpen>d__139.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlConnector.<Open>d__136.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.ConnectorPool.<AllocateLong>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Npgsql.NpgsqlConnection.<Open>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlConnection.Open()
   at MiningCore.Persistence.Postgres.ConnectionFactory.OpenConnection() in /home/sh/miningcore/src/MiningCore/Persistence/Postgres/ConnectionFactory.cs:line 43
   at MiningCore.Extensions.ConnectionFactoryExtensions.Run[T](IConnectionFactory factory, Func`2 action) in /home/sh/miningcore/src/MiningCore/Extensions/ConnectionFactoryExtensions.cs:line 47
   at MiningCore.Payments.PayoutManager.<UpdatePoolBalancesAsync>d__12.MoveNext() in /home/sh/miningcore/src/MiningCore/Payments/PayoutManager.cs:line 114
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Payments.PayoutManager.<ProcessPoolsAsync>d__11.MoveNext() in /home/sh/miningcore/src/MiningCore/Payments/PayoutManager.cs:line 95    at Npgsql.NpgsqlConnector.Connect(NpgsqlTimeout timeout)
   at Npgsql.NpgsqlConnector.<RawOpen>d__139.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlConnector.<Open>d__136.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.ConnectorPool.<AllocateLong>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Npgsql.NpgsqlConnection.<Open>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlConnection.Open()
   at MiningCore.Persistence.Postgres.ConnectionFactory.OpenConnection() in /home/sh/miningcore/src/MiningCore/Persistence/Postgres/ConnectionFactory.cs:line 43
   at MiningCore.Extensions.ConnectionFactoryExtensions.Run[T](IConnectionFactory factory, Func`2 action) in /home/sh/miningcore/src/MiningCore/Extensions/ConnectionFactoryExtensions.cs:line 47
   at MiningCore.Payments.PayoutManager.<UpdatePoolBalancesAsync>d__12.MoveNext() in /home/sh/miningcore/src/MiningCore/Payments/PayoutManager.cs:line 114
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Payments.PayoutManager.<ProcessPoolsAsync>d__11.MoveNext() in /home/sh/miningcore/src/MiningCore/Payments/PayoutManager.cs:line 95
[2017-12-14 10:17:36.0067] [I] [eth1] [Ethereum Job Manager] Waiting for daemons to come online ... 
[2017-12-14 10:17:46.0159] [I] [eth1] [Ethereum Job Manager] Waiting for daemons to come online ... `
and i don't know what to do , @calvintam236 @jeong760 @oliverw

**Comment by oliverw** [comment]
The exception means that the connection to the database failed.

**Comment by 8bitidea** [comment]
I’m sorry to ask i know you have lot to do , but could you tell me how to solve what ? 😌

**Comment by calvintam236** [comment]
@8bitidea are you sure your database is online?

**Comment by 8bitidea** [comment]
@oliverw @calvintam236  yes it was that database i connected it with wrong ip , and parity need to run manually ,i am running the parity on classic network and waiting it to finish sync and will connect the miners to test it out,  it was my mistake , sorry guys and thank you very much for this

**Comment by oliverw** [comment]
@8bitidea No excuses needed. Everyone has to start somewhere :)

**Comment by toboho** [comment]
have  video installation guide ?

**Comment by Sisyatek** [comment]
Did u have any guide for Ubunutu 20.04?
