### ISSUE TITLE
 System.OutOfMemoryException: ethash_full_n ew IO or memory error

### ISSUE THREAD

**Issue by tayfun91** [coinfoundry/miningcore#535]
Hi. I Need Help.

Windows Server 2012 R2
64Gb Ram

2x Xeon Cpu

Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. Tüm hakları saklıdır.

C:\build>dotnet Miningcore.dll -c config.json

 ███╗   ███╗██╗███╗   ██╗██╗███╗   ██╗ ██████╗  ██████╗ ██████╗ ██████╗ ███████╗

 ████╗ ████║██║████╗  ██║██║████╗  ██║██╔════╝ ██╔════╝██╔═══██╗██╔══██╗██╔════╝

 ██╔████╔██║██║██╔██╗ ██║██║██╔██╗ ██║██║  ███╗██║     ██║   ██║██████╔╝█████╗
 ██║╚██╔╝██║██║██║╚██╗██║██║██║╚██╗██║██║   ██║██║     ██║   ██║██╔══██╗██╔══╝
 ██║ ╚═╝ ██║██║██║ ╚████║██║██║ ╚████║╚██████╔╝╚██████╗╚██████╔╝██║  ██║███████╗

 https://github.com/coinfoundry/miningcore

 Please contribute to the development of the project by donating:

 BTC  - 17QnVor1B6oK1rWnVVBrdX9gFzVkZZbhDm
 LTC  - LTK6CWastkmBzGxgQhTTtCUjkjDA14kxzC
 DASH - XqpBAV9QCaoLnz42uF5frSSfrJTrqHoxjp
 ZEC  - t1YHZHz2DGVMJiggD2P4fBQ2TAPgtLSUwZ7
 ZCL  - t1MFU1vD3YKgsK6Uh8hW7UTY8mKAV2xVqBr
 ETH  - 0xcb55abBfe361B12323eb952110cE33d5F28BeeE1
 ETC  - 0xF8cCE9CE143C68d3d4A7e6bf47006f21Cfcf93c0
 XMR  - 475YVJbPHPedudkhrcNp1wDcLMTGYusGPF5fqE7XjnragVLPdqbCHBdZg3dF4dN9hXMjjvGb
ykS6a77dTAQvGrpiQqHp2eH

Using configuration file config.json

[2019-02-08 00:11:20.2979] [I] [Core] .NET Core 4.6.27129.04 on Microsoft Window
s 6.3.9600 [X64]
[2019-02-08 00:11:20.4314] [I] [Core] 45 coins loaded from C:\build\coins.json
[2019-02-08 00:11:20.5523] [I] [ShareRecorder] Online
[2019-02-08 00:11:20.7786] [I] [XmlKeyManager] User profile is available. Using
'C:\Users\Administrator\AppData\Local\ASP.NET\DataProtection-Keys' as key reposi
tory and Windows DPAPI to encrypt keys at rest.
[2019-02-08 00:11:20.8285] [I] [Core] API Access to /api/admin restricted to 127
.0.0.1,::1,::ffff:127.0.0.1
[2019-02-08 00:11:20.8285] [I] [Core] API Access to /metrics restricted to 127.0
.0.1,::1,::ffff:127.0.0.1
[2019-02-08 00:11:20.9567] [I] [Core] API access limited to 5 requests per 1s, e
xcept from 127.0.0.1, ::1, ::ffff:127.0.0.1
[2019-02-08 00:11:20.9850] [I] [Core] API Online @ 127.0.0.1:4000
[2019-02-08 00:11:20.9850] [I] [Core] Prometheus Metrics Online @ 127.0.0.1:4000
/metrics
[2019-02-08 00:11:20.9850] [I] [Core] WebSocket notifications streaming @ 127.0.
0.1:4000/notifications
[2019-02-08 00:11:20.9933] [I] [PayoutManager] Online
[2019-02-08 00:11:20.9933] [I] [StatsRecorder] Online
[2019-02-08 00:11:20.9933] [I] [PayoutManager] Processing payments for pool eth1

[2019-02-08 00:11:21.0248] [I] [eth1] Starting Pool ...
[2019-02-08 00:11:21.0408] [I] [eth1] Starting Job Manager ...
[2019-02-08 00:11:21.2117] [I] [eth1] All daemons online
[2019-02-08 00:11:21.2391] [I] [eth1] All daemons synched with blockchain
[2019-02-08 00:11:21.8822] [I] [PayoutManager] No updated blocks for pool eth1
[2019-02-08 00:11:21.8983] [I] [PayoutManager] No balances over configured minim
um payout for pool eth1
[2019-02-08 00:11:23.0276] [I] [eth1] Loading current DAG ...
[2019-02-08 00:11:23.0276] [I] [eth1] No pre-generated DAG available, creating n
ew for epoch 239
[2019-02-08 00:11:23.0276] [I] [eth1] Generating DAG for epoch 239
[2019-02-08 00:11:26.5048] [E] [eth1] System.OutOfMemoryException: ethash_full_n
ew IO or memory error
   at Miningcore.Crypto.Hashing.Ethash.Dag.<>c__DisplayClass13_0.<GenerateAsync>
b__0() in C:\src\Miningcore\Crypto\Hashing\Ethash\Dag.cs:line 94
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionCo
ntext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Miningcore.Crypto.Hashing.Ethash.Dag.GenerateAsync(String dagDir, ILogger
logger, CancellationToken ct) in C:\src\Miningcore\Crypto\Hashing\Ethash\Dag.cs:
line 65
   at Miningcore.Crypto.Hashing.Ethash.EthashFull.GetDagAsync(UInt64 block, ILog
ger logger, CancellationToken ct) in C:\src\Miningcore\Crypto\Hashing\Ethash\Eth
ashFull.cs:line 90
   at Miningcore.Blockchain.Ethereum.EthereumJobManager.PostStartInitAsync(Cance
llationToken ct) in C:\src\Miningcore\Blockchain\Ethereum\EthereumJobManager.cs:
line 622
   at Miningcore.Blockchain.JobManagerBase`1.StartAsync(CancellationToken ct) in
 C:\src\Miningcore\Blockchain\JobManagerBase.cs:line 136
   at Miningcore.Blockchain.Ethereum.EthereumPool.SetupJobManager(CancellationTo
ken ct) in C:\src\Miningcore\Blockchain\Ethereum\EthereumPool.cs:line 285
   at Miningcore.Mining.PoolBase.StartAsync(CancellationToken ct) in C:\src\Mini
ngcore\Mining\PoolBase.cs:line 375 System.OutOfMemoryException: ethash_full_new
IO or memory error
   at Miningcore.Crypto.Hashing.Ethash.Dag.<>c__DisplayClass13_0.<GenerateAsync>
b__0() in C:\src\Miningcore\Crypto\Hashing\Ethash\Dag.cs:line 94
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionCo
ntext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Miningcore.Crypto.Hashing.Ethash.Dag.GenerateAsync(String dagDir, ILogger
logger, CancellationToken ct) in C:\src\Miningcore\Crypto\Hashing\Ethash\Dag.cs:
line 65
   at Miningcore.Crypto.Hashing.Ethash.EthashFull.GetDagAsync(UInt64 block, ILog
ger logger, CancellationToken ct) in C:\src\Miningcore\Crypto\Hashing\Ethash\Eth
ashFull.cs:line 90
   at Miningcore.Blockchain.Ethereum.EthereumJobManager.PostStartInitAsync(Cance
llationToken ct) in C:\src\Miningcore\Blockchain\Ethereum\EthereumJobManager.cs:
line 622
   at Miningcore.Blockchain.JobManagerBase`1.StartAsync(CancellationToken ct) in
 C:\src\Miningcore\Blockchain\JobManagerBase.cs:line 136
   at Miningcore.Blockchain.Ethereum.EthereumPool.SetupJobManager(CancellationTo
ken ct) in C:\src\Miningcore\Blockchain\Ethereum\EthereumPool.cs:line 285
   at Miningcore.Mining.PoolBase.StartAsync(CancellationToken ct) in C:\src\Mini
ngcore\Mining\PoolBase.cs:line 375    at Miningcore.Crypto.Hashing.Ethash.Dag.<>
c__DisplayClass13_0.<GenerateAsync>b__0() in C:\src\Miningcore\Crypto\Hashing\Et
hash\Dag.cs:line 94
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionCo
ntext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Miningcore.Crypto.Hashing.Ethash.Dag.GenerateAsync(String dagDir, ILogger
logger, CancellationToken ct) in C:\src\Miningcore\Crypto\Hashing\Ethash\Dag.cs:
line 65
   at Miningcore.Crypto.Hashing.Ethash.EthashFull.GetDagAsync(UInt64 block, ILog
ger logger, CancellationToken ct) in C:\src\Miningcore\Crypto\Hashing\Ethash\Eth
ashFull.cs:line 90
   at Miningcore.Blockchain.Ethereum.EthereumJobManager.PostStartInitAsync(Cance
llationToken ct) in C:\src\Miningcore\Blockchain\Ethereum\EthereumJobManager.cs:
line 622
   at Miningcore.Blockchain.JobManagerBase`1.StartAsync(CancellationToken ct) in
 C:\src\Miningcore\Blockchain\JobManagerBase.cs:line 136
   at Miningcore.Blockchain.Ethereum.EthereumPool.SetupJobManager(CancellationTo
ken ct) in C:\src\Miningcore\Blockchain\Ethereum\EthereumPool.cs:line 285
   at Miningcore.Mining.PoolBase.StartAsync(CancellationToken ct) in C:\src\Mini
ngcore\Mining\PoolBase.cs:line 375
System.AggregateException: One or more errors occurred. (ethash_full_new IO or m
emory error) ---> System.OutOfMemoryException: ethash_full_new IO or memory erro
r
   at Miningcore.Crypto.Hashing.Ethash.Dag.<>c__DisplayClass13_0.<GenerateAsync>
b__0() in C:\src\Miningcore\Crypto\Hashing\Ethash\Dag.cs:line 94
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionCo
ntext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Miningcore.Crypto.Hashing.Ethash.Dag.GenerateAsync(String dagDir, ILogger
logger, CancellationToken ct) in C:\src\Miningcore\Crypto\Hashing\Ethash\Dag.cs:
line 65
   at Miningcore.Crypto.Hashing.Ethash.EthashFull.GetDagAsync(UInt64 block, ILog
ger logger, CancellationToken ct) in C:\src\Miningcore\Crypto\Hashing\Ethash\Eth
ashFull.cs:line 90
   at Miningcore.Blockchain.Ethereum.EthereumJobManager.PostStartInitAsync(Cance
llationToken ct) in C:\src\Miningcore\Blockchain\Ethereum\EthereumJobManager.cs:
line 622
   at Miningcore.Blockchain.JobManagerBase`1.StartAsync(CancellationToken ct) in
 C:\src\Miningcore\Blockchain\JobManagerBase.cs:line 136
   at Miningcore.Blockchain.Ethereum.EthereumPool.SetupJobManager(CancellationTo
ken ct) in C:\src\Miningcore\Blockchain\Ethereum\EthereumPool.cs:line 285
   at Miningcore.Mining.PoolBase.StartAsync(CancellationToken ct) in C:\src\Mini
ngcore\Mining\PoolBase.cs:line 375
   at Miningcore.Program.<>c.<<Start>b__40_2>d.MoveNext() in C:\src\Miningcore\P
rogram.cs:line 841
--- End of stack trace from previous location where exception was thrown ---
   at Miningcore.Program.Start() in C:\src\Miningcore\Program.cs:line 825
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationTo
ken cancellationToken)
   at Miningcore.Program.Main(String[] args) in C:\src\Miningcore\Program.cs:lin
e 108
---> (Inner Exception #0) System.OutOfMemoryException: ethash_full_new IO or mem
ory error
   at Miningcore.Crypto.Hashing.Ethash.Dag.<>c__DisplayClass13_0.<GenerateAsync>
b__0() in C:\src\Miningcore\Crypto\Hashing\Ethash\Dag.cs:line 94
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionCo
ntext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Miningcore.Crypto.Hashing.Ethash.Dag.GenerateAsync(String dagDir, ILogger
logger, CancellationToken ct) in C:\src\Miningcore\Crypto\Hashing\Ethash\Dag.cs:
line 65
   at Miningcore.Crypto.Hashing.Ethash.EthashFull.GetDagAsync(UInt64 block, ILog
ger logger, CancellationToken ct) in C:\src\Miningcore\Crypto\Hashing\Ethash\Eth
ashFull.cs:line 90
   at Miningcore.Blockchain.Ethereum.EthereumJobManager.PostStartInitAsync(Cance
llationToken ct) in C:\src\Miningcore\Blockchain\Ethereum\EthereumJobManager.cs:
line 622
   at Miningcore.Blockchain.JobManagerBase`1.StartAsync(CancellationToken ct) in
 C:\src\Miningcore\Blockchain\JobManagerBase.cs:line 136
   at Miningcore.Blockchain.Ethereum.EthereumPool.SetupJobManager(CancellationTo
ken ct) in C:\src\Miningcore\Blockchain\Ethereum\EthereumPool.cs:line 285
   at Miningcore.Mining.PoolBase.StartAsync(CancellationToken ct) in C:\src\Mini
ngcore\Mining\PoolBase.cs:line 375
   at Miningcore.Program.<>c.<<Start>b__40_2>d.MoveNext() in C:\src\Miningcore\P
rogram.cs:line 841
--- End of stack trace from previous location where exception was thrown ---
   at Miningcore.Program.Start() in C:\src\Miningcore\Program.cs:line 825<---

Cluster cannot start. Good Bye!
[2019-02-08 00:11:26.5654] [I] [Core] Shutdown ...
Shutdown...
[2019-02-08 00:11:26.5654] [I] [ShareReceiver] Stopping ..
[2019-02-08 00:11:26.5654] [I] [ShareReceiver] Stopped
[2019-02-08 00:11:26.5654] [I] [ShareRecorder] Stopping ..
[2019-02-08 00:11:26.5654] [I] [ShareRecorder] Stopped
[2019-02-08 00:11:26.5654] [I] [StatsRecorder] Stopping ..
[2019-02-08 00:11:31.0065] [I] [StatsRecorder] Updating hashrates for pool eth1

[2019-02-08 00:11:31.0518] [I] [StatsRecorder] Stopped

C:\build>

**Comment by tayfun91** [comment]
"pools": [{
        "id": "eth1",
	   
        "enabled": true,
	  "dagDir": "/data2/dag/eth1",  //Not Work
        "coin": "ethereum",
        "address": "0xxxxxxxxx",
        "rewardRecipients": [{
                "type": "op",
                "address": "0xxxxxxxx",
                "percentage": 0
        }],

**Comment by oliverw** [comment]
Ask yourself, have you ever seen a path like <code>/data2/dag/eth1</code> on Windows?

**Comment by tayfun91** [comment]
Yes, Program Created /data2/dag/eth1 in file 0 KB full-R23-4309e9a28e2f6257 @oliverw

**Comment by tayfun91** [comment]
please help me @oliverw

**Comment by eketubol** [comment]
@tayfun91 Would you not be required to give the full path? Seems like you are missing where exactly it is saved.

**Comment by tayfun91** [comment]
@eketubol @oliverw  I Solved This Problem.  I installed the windows subsystem linux just ran the miningcore program there
