### ISSUE TITLE
The given key 'version-rolling.min-bit-count' was not present in the dictionary.

### ISSUE THREAD

**Issue by peysab** [coinfoundry/miningcore#536]
Any one have any idea what might can cause this error?

```
Feb 08 08:42:52 server.persianmine.com miningcore-app[23895]: [2019-02-08 08:42:52.0672] [E] [lcc] [0HLKDGFDFRE5H] Connection error state: System.Collections.Generic.KeyNotFoundException: The given key 'version-rolling.min-bit-count' was not present in the dictionary.
Feb 08 08:42:52 server.persianmine.com miningcore-app[23895]:    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
Feb 08 08:42:52 server.persianmine.com miningcore-app[23895]:    at Miningcore.Blockchain.Bitcoin.BitcoinPool.ConfigureVersionRolling(StratumClient client, BitcoinWorkerContext context, Dictionary`2 extensionParams, Dictionary`2 result)
Feb 08 08:42:52 server.persianmine.com miningcore-app[23895]:    at Miningcore.Blockchain.Bitcoin.BitcoinPool.OnConfigureMiningAsync(StratumClient client, Timestamped`1 tsRequest) in /home/persianmine/src/miningcore/src/Miningcore/Blockchain/Bitcoin/BitcoinPool.cs:line 272
Feb 08 08:42:52 server.persianmine.com miningcore-app[23895]:    at Miningcore.Blockchain.Bitcoin.BitcoinPool.OnRequestAsync(StratumClient client, Timestamped`1 tsRequest, CancellationToken ct) in /home/persianmine/src/miningcore/src/Miningcore/Blockchain/Bitcoin/BitcoinPool.cs:line 467
Feb 08 08:42:52 server.persianmine.com miningcore-app[23895]:    at Miningcore.Stratum.StratumServer.OnRequestAsync(StratumClient client, JsonRpcRequest request, CancellationToken ct) in /home/persianmine/src/miningcore/src/Miningcore/Stratum/StratumServer.cs:line 250
Feb 08 08:42:52 server.persianmine.com miningcore-app[23895]:    at Miningcore.Stratum.StratumClient.ProcessRequestAsync(Func`4 onRequestAsync, ReadOnlySequence`1 lineBuffer) in /home/persianmine/src/miningcore/src/Miningcore/Stratum/StratumClient.cs:line 403
Feb 08 08:42:52 server.persianmine.com miningcore-app[23895]:    at Miningcore.Stratum.StratumClient.ProcessReceivePipeAsync(TcpProxyProtocolConfig proxyProtocol, Func`4 onRequestAsync) in /home/persianmine/src/miningcore/src/Miningcore/Stratum/StratumClient.cs:line 330
Feb 08 08:42:52 server.persianmine.com miningcore-app[23895]: [2019-02-08 08:42:52.0672] [I] [lcc] [0HLKDGFDFRE5H] Connection closed

```

**Comment by oliverw** [comment]
Fixed in dev already.

**Comment by peysab** [comment]
Hey @oliverw , can I please know in which commit in dev you fixed the issue? and do you have any plans on a new release?

Thanks

**Comment by peysab** [comment]
is the fix commenting out this line in the BitcoinPool.cs:
var requestedBits = extensionParams[BitcoinStratumExtensions.VersionRollingBits].Value<int>();

**Comment by oliverw** [comment]
Yes, that's the one.
