### ISSUE TITLE
System.AggregateException: One or more errors occurred

### ISSUE THREAD

**Issue by jeong760** [coinfoundry/miningcore#56]
Dears,

I have this error during pool operation with bitcoin. 
When this erros occurred then pool stop response and work.

[2017-11-09 14:03:13.0256] [E] [BTC] [Bitcoin Job Manager] Error during UpdateJob System.AggregateException: One or more errors occurred. (A task was canceled.) ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at MiningCore.DaemonInterface.DaemonClient.MapDaemonResponse[TResponse](Int32 i, Task`1 x) in /home/linuxadm/miningcore/src/MiningCore/DaemonInterface/DaemonClient.cs:line 318
   at MiningCore.DaemonInterface.DaemonClient.<ExecuteCmdAnyAsync>d__11`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Bitcoin.BitcoinJobManager`2.<GetBlockTemplateAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Bitcoin.BitcoinJobManager`2.<UpdateJob>d__49.MoveNext()
---> (Inner Exception #0) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---
    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at MiningCore.DaemonInterface.DaemonClient.MapDaemonResponse[TResponse](Int32 i, Task`1 x) in /home/linuxadm/miningcore/src/MiningCore/DaemonInterface/DaemonClient.cs:line 318
   at MiningCore.DaemonInterface.DaemonClient.<ExecuteCmdAnyAsync>d__11`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Bitcoin.BitcoinJobManager`2.<GetBlockTemplateAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Bitcoin.BitcoinJobManager`2.<UpdateJob>d__49.MoveNext()
[2017-11-09 14:03:18.0391] [E] [BTC] [Bitcoin Job Manager] Error during UpdateJob System.AggregateException: One or more errors occurred. (A task was canceled.) ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at MiningCore.DaemonInterface.DaemonClient.MapDaemonResponse[TResponse](Int32 i, Task`1 x) in /home/linuxadm/miningcore/src/MiningCore/DaemonInterface/DaemonClient.cs:line 318
   at MiningCore.DaemonInterface.DaemonClient.<ExecuteCmdAnyAsync>d__11`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Bitcoin.BitcoinJobManager`2.<GetBlockTemplateAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Bitcoin.BitcoinJobManager`2.<UpdateJob>d__49.MoveNext()
---> (Inner Exception #0) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---
    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at MiningCore.DaemonInterface.DaemonClient.MapDaemonResponse[TResponse](Int32 i, Task`1 x) in /home/linuxadm/miningcore/src/MiningCore/DaemonInterface/DaemonClient.cs:line 318
   at MiningCore.DaemonInterface.DaemonClient.<ExecuteCmdAnyAsync>d__11`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Bitcoin.BitcoinJobManager`2.<GetBlockTemplateAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Bitcoin.BitcoinJobManager`2.<UpdateJob>d__49.MoveNext()

Regards,
John Ahn

**Comment by jeong760** [comment]
Dears,

Also, miner does not display its hash rate and pool diff 
![capture](https://user-images.githubusercontent.com/18043565/32609648-b11b1a76-c5a3-11e7-99a3-02841055bca2.JPG)

**Comment by Gadflyii** [comment]
What was the fix for this error?
