### ISSUE TITLE
Payment processing failed

### ISSUE THREAD

**Issue by tenlans** [coinfoundry/miningcore#574]
## Note
There is a payout error when run payment process.

### Description

[2019-03-07 00:52:03.3090] [E] [PayoutManager] [eth] Payment processing failed System.Exception: Unable to determine block reward: Unsupported chain type

at MiningCore.Blockchain.Ethereum.EthereumPayoutHandler.GetBaseBlockReward(ParityChainType chainType, UInt64 height) in /data/miningcore/src/MiningCore/Blockchain/Ethereum/EthereumPayoutHandler.cs:line 364
   at MiningCore.Blockchain.Ethereum.EthereumPayoutHandler.ClassifyBlocksAsync(Block[] blocks) in /data/miningcore/src/MiningCore/Blockchain/Ethereum/EthereumPayoutHandler.cs:line 157
...

### Version

[Server]
Ubuntu 16.04
Latest miningcore as at Nov 6th 2018 from master
Parity v2.3.5-stable
Pool hashrate about 28GH/s
Pool sharespersecond about 12
Pool difficulty: 3G
[Client]
Windows 7 or Windows 10
EthDcrMiner64 v11.9

### Additional Information

"pools": [{
"id": "eth",
"enabled": true,
"coin": "ethereum",
"address": "0x",
"rewardRecipients": [{
"type": "op",
"address": "0x",
"percentage": 1.0
}],
"blockRefreshInterval": 500,
"clientConnectionTimeout": 600,
"banning": {
"enabled": true,
"time": 600,
"invalidPercent": 50,
"checkThreshold": 50
},
"ports": {
"3333": {
"listenAddress": "0.0.0.0",
"difficulty": 0.5
}
},
"daemons": [
{
"host": "127.0.0.1",
"port": 8545
}
],
"paymentProcessing": {
"enabled": true,
"minimumPayment": 0.05,
"minimumPaymentToPaymentId": 5.0,
"payoutScheme": "PPLNS",
"payoutSchemeConfig": {
"factor": 2.0
},
"coinbasePassword": "xxxx",
"keepUncles": false,
"keepTransactionFees": false
}
}]

**Comment by Konstantin35** [comment]
What parameters is Parity running with?

**Comment by ghost** [comment]
Hello were you able to fix this ?
