### ISSUE TITLE
ZClassic is now sapling activated

### ISSUE THREAD

**Issue by jeromemorignot** [coinfoundry/miningcore#575]
## Note
Please use the following format to file an issue. Issues that fail to comply will delay our responses.
Please remove this section when you submit the issue. Thank you for your cooperation.

### Description

I tried to add the same sapling settings than ZCash in coins.json, but with the correct height.
		  "overwinterActivationHeight": 476969,
          "overwinterTxVersion": 3,
          "overwinterTxVersionGroupId": 63210096,
          "saplingActivationHeight": 476969,
          "saplingTxVersion": 4,
          "saplingTxVersionGroupId": 2301567109

### Steps to Reproduce

1. I start the pool

### Actual behavior

[2019-03-07 15:20:28.4358] [E] [zclassic2] Error during UpdateJob System.ArgumentException: Field 'fOverwintered' defined on type 'NBitcoin.Zcash.ZcashTransaction' is not a field on the target object which is of type 'NBitcoin.Transaction'.
   at System.Reflection.RtFieldInfo.CheckConsistency(Object target)
   at System.Reflection.RtFieldInfo.InternalSetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, CultureInfo culture, StackCrawlMark& stackMark)
   at System.Reflection.RtFieldInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, CultureInfo culture)
   at Miningcore.Blockchain.Equihash.EquihashJob.CreateOutputTransaction() in /root/miningcore/src/Miningcore/Blockchain/Equihash/EquihashJob.cs:line 100
   at Miningcore.Blockchain.Equihash.EquihashJob.BuildCoinbase() in /root/miningcore/src/Miningcore/Blockchain/Equihash/EquihashJob.cs:line 158
   at Miningcore.Blockchain.Equihash.EquihashJob.Init(EquihashBlockTemplate blockTemplate, String jobId, PoolConfig poolConfig, ClusterConfig clusterConfig, IMasterClock clock, IDestination poolAddressDestination, Network network, EquihashSolver solver) in /root/miningcore/src/Miningcore/Blockchain/Equihash/EquihashJob.cs:line 399
   at Miningcore.Blockchain.Equihash.EquihashJobManager.UpdateJob(Boolean forceUpdate, String via, String json) in /root/miningcore/src/Miningcore/Blockchain/Equihash/EquihashJobManager.cs:line 149    at System.Reflection.RtFieldInfo.CheckConsistency(Object target)
   at System.Reflection.RtFieldInfo.InternalSetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, CultureInfo culture, StackCrawlMark& stackMark)
   at System.Reflection.RtFieldInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, CultureInfo culture)
   at Miningcore.Blockchain.Equihash.EquihashJob.CreateOutputTransaction() in /root/miningcore/src/Miningcore/Blockchain/Equihash/EquihashJob.cs:line 100
   at Miningcore.Blockchain.Equihash.EquihashJob.BuildCoinbase() in /root/miningcore/src/Miningcore/Blockchain/Equihash/EquihashJob.cs:line 158
   at Miningcore.Blockchain.Equihash.EquihashJob.Init(EquihashBlockTemplate blockTemplate, String jobId, PoolConfig poolConfig, ClusterConfig clusterConfig, IMasterClock clock, IDestination poolAddressDestination, Network network, EquihashSolver solver) in /root/miningcore/src/Miningcore/Blockchain/Equihash/EquihashJob.cs:line 399
   at Miningcore.Blockchain.Equihash.EquihashJobManager.UpdateJob(Boolean forceUpdate, String via, String json) in /root/miningcore/src/Miningcore/Blockchain/Equihash/EquihashJobManager.cs:line 149

### Reproduces how often

Keeps looping

### Version

latest version with https://github.com/coinfoundry/miningcore/commit/ad60fff850dc7ffd1eebbaad708e06dabaac564c
 applied

### Additional Information

Any additional information, log, configuration or data that might be necessary to reproduce the issue.

**Comment by peysab** [comment]
Anyone yet able to tackle this issue? @oliverw ?

**Comment by peysab** [comment]
I think the problem is with the implementation of reflection  in  (EquihashJob.cs)  https://github.com/coinfoundry/miningcore/blob/master/src/Miningcore/Blockchain/Equihash/EquihashJob.cs

I tried to create a new object instead of reflection :
just replace the line 92 with the following:

```
var tx1 = Transaction.Create(txNetwork);
var tx = new ZcashTransaction(tx1.ToHex());

```
I tried it with zelcash on testnet and it worked.
@oliverw  can you please confirm that if this is a good solution or not?

**Comment by peysab** [comment]
I tested my solution and it's working on ZCLassic I know that it's not the best solution and is very dirty but at least it's working.
