### ISSUE TITLE
Enable rateLimiting

### ISSUE THREAD

**Issue by Konstantin35** [coinfoundry/miningcore#576]
## Enabled rateLimiting
```
  "api": {
        "enabled": true,
        "listenAddress": "127.0.0.1",
        "port": 4000,
        "metricsIpWhitelist": [],
        "rateLimiting": {
            "disabled": false,
            "rules": [
                {
                    "Endpoint": "*",
                    "Period": "1s",
                    "Limit": 5
                }
            ],
            "ipWhitelist": []
        }
  },
```
## Start

```
dotnet --version
2.2.105
```

```

[2019-03-17 17:40:40.4539] [I] [Core] API Access to /api/admin restricted to 127.0.0.1,::1,::ffff:127.0.0.1
[2019-03-17 17:40:40.4539] [I] [Core] API Access to /metrics restricted to 127.0.0.1,::1,::ffff:127.0.0.1
[2019-03-17 17:40:40.7635] [I] [Core] API access limited to 2 requests per 1s, except from 127.0.0.1, ::1, ::ffff:127.0.0.1
Application startup exception: System.InvalidOperationException: Unable to resolve service for type 'AspNetCoreRateLimit.IRateLimitConfiguration' while attempting to activate 'AspNetCoreRateLimit.IpRateLimitMiddleware'.
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass4_0.<UseMiddleware>b__0(RequestDelegate next)
   at Microsoft.AspNetCore.Builder.Internal.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
System.AggregateException: One or more errors occurred. (Unable to resolve service for type 'AspNetCoreRateLimit.IRateLimitConfiguration' while attempting to activate 'AspNetCoreRateLimit.IpRateLimitMiddleware'.) ---> System.InvalidOperationException: Unable to resolve service for type 'AspNetCoreRateLimit.IRateLimitConfiguration' while attempting to activate 'AspNetCoreRateLimit.IpRateLimitMiddleware'.
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass4_0.<UseMiddleware>b__0(RequestDelegate next)
   at Microsoft.AspNetCore.Builder.Internal.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Start()
   at Miningcore.Program.StartApi() in /home/pool/miningcore/src/Miningcore/Program.cs:line 763
   at Miningcore.Program.Start() in /home/pool/miningcore/src/Miningcore/Program.cs:line 813
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Miningcore.Program.Main(String[] args) in /home/pool/miningcore/src/Miningcore/Program.cs:line 109
---> (Inner Exception #0) System.InvalidOperationException: Unable to resolve service for type 'AspNetCoreRateLimit.IRateLimitConfiguration' while attempting to activate 'AspNetCoreRateLimit.IpRateLimitMiddleware'.
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass4_0.<UseMiddleware>b__0(RequestDelegate next)
   at Microsoft.AspNetCore.Builder.Internal.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Start()
   at Miningcore.Program.StartApi() in /home/pool/miningcore/src/Miningcore/Program.cs:line 763
   at Miningcore.Program.Start() in /home/pool/miningcore/src/Miningcore/Program.cs:line 813<---

Cluster cannot start. Good Bye!

```
What's the problem?

**Comment by bitspill** [comment]
There was an update to AspNetCoreRateLimit which brought some breaking changes to the latest MiningCore release

A fix is in the dev branch -- https://github.com/coinfoundry/miningcore/commit/ad60fff850dc7ffd1eebbaad708e06dabaac564c
