### ISSUE TITLE
at MiningCore.Blockchain.Ethereum.EthereumPayoutHandler.<Payout>d__17.MoveNext()

### ISSUE THREAD

**Issue by 2zo** [coinfoundry/miningcore#59]
Here such error began to appear when it fails to pay the purse from the initial unlocked parity

```
System.Exception: Unable to unlock coinbase account for sending transaction
at MiningCore.Blockchain.Ethereum.EthereumPayoutHandler.<Payout>d__17.MoveNext() in /opt/POOL/miningcore-Nov-8-2017/src/MiningCore/Blockchain/Ethereum/EthereumPayoutHandler.cs:line 400
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Ethereum.EthereumPayoutHandler.<PayoutAsync>d__12.MoveNext() in /opt/POOL/miningcore-Nov-8-2017/src/MiningCore/Blockchain/Ethereum/EthereumPayoutHandler.cs:line 282 System.Exception: Unable to unlock coinbase account for sending transaction
   at MiningCore.Blockchain.Ethereum.EthereumPayoutHandler.<Payout>d__17.MoveNext() in /opt/POOL/miningcore-Nov-8-2017/src/MiningCore/Blockchain/Ethereum/EthereumPayoutHandler.cs:line 400
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Ethereum.EthereumPayoutHandler.<PayoutAsync>d__12.MoveNext() in /opt/POOL/miningcore-Nov-8-2017/src/MiningCore/Blockchain/Ethereum/EthereumPayoutHandler.cs:line 282    at MiningCore.Blockchain.Ethereum.EthereumPayoutHandler.<Payout>d__17.MoveNext() in /opt/POOL/miningcore-Nov-8-2017/src/MiningCore/Blockchain/Ethereum/EthereumPayoutHandler.cs:line 400
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Ethereum.EthereumPayoutHandler.<PayoutAsync>d__12.MoveNext() in /opt/POOL/miningcore-Nov-8-2017/src/MiningCore/Blockchain/Ethereum/EthereumPayoutHandler.cs:line 282

```
Launched version from Nov 5, 2017 payment went fine I do not understand why this option CoinbasePassword  purse initially unlock the team parity

**Comment by oliverw** [comment]
Ah you have a pre-unlocked wallet?

**Comment by oliverw** [comment]
Reason for closing?

**Comment by oliverw** [comment]
@2zo Was the payment about a block found in a production environment?
