### ISSUE TITLE
How I add a new coins for GlobalToken (GLT)?

### ISSUE THREAD

**Issue by jeong760** [coinfoundry/miningcore#61]
Dears,

I've modified a ClusterConfig.CS and CoinMatadata.cs in order to add a GlobalToken(GLT) 
However, after I compiled I've got following errors so which code related to this should I edit?

Based on following error it does not load a coin related daemon and Stratum interface for mining. 
So want to know where I can edit more

System.AggregateException: One or more errors occurred. (Sequence contains no matching element) ---> System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at MiningCore.Program.<>c.<<Start>b__26_1>d.MoveNext() in D:\git\miningcore\src\MiningCore\Program.cs:line 514
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Program.<Start>d__26.MoveNext() in D:\git\miningcore\src\MiningCore\Program.cs:line 531
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at MiningCore.Program.Main(String[] args) in D:\git\miningcore\src\MiningCore\Program.cs:line 82
---> (Inner Exception #0) System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at MiningCore.Program.<>c.<<Start>b__26_1>d.MoveNext() in D:\git\miningcore\src\MiningCore\Program.cs:line 514
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Program.<Start>d__26.MoveNext() in D:\git\miningcore\src\MiningCore\Program.cs:line 531<---

Regards,
John Ahn

**Comment by jeong760** [comment]
Dears,

I've found where I can be modified but still have an error related with Jobmanager.

ClusterConfig.cs
CoinMataData.cs
BitcoinPayoutHandler.cs
BitcoinPool.cs

The error is
[2017-11-12 18:33:24.1731] [I] [ShareRecorder] Online
[2017-11-12 18:33:24.2698] [I] [ApiServer] Launching ...
[2017-11-12 18:33:24.6397] [I] [ApiServer] Online @ 127.0.0.1:4000
[2017-11-12 18:33:24.6909] [I] [BTC] [Pool] Launching ...
[2017-11-12 18:33:24.7622] [I] [BTC] [Bitcoin Job Manager] Launching ...
[2017-11-12 18:33:24.8576] [I] [GLT] [Pool] Launching ...
[2017-11-12 18:33:24.8576] [I] [GLT] [Bitcoin Job Manager] Launching ...
[2017-11-12 18:33:24.9489] [I] [GLT] [Bitcoin Job Manager] All daemons online
[2017-11-12 18:33:24.9489] [I] [BTC] [Bitcoin Job Manager] All daemons online
[2017-11-12 18:33:25.0100] [I] [GLT] [Bitcoin Job Manager] All daemons synched with blockchain
**[2017-11-12 18:33:25.2667] [E] [GLT] [Bitcoin Job Manager] Coin Type 'GLT' not supported by this Job Manager**


Regards,
John Ahn

**Comment by jeong760** [comment]
Dears,

I am going to make a mining test with GlobalToken (GLT) and I found that similar algorithms just modified the following code. 

ClusterConfig.cs
CoinMataData.cs
BitcoinPayoutHandler.cs
BitcoinPool.cs
BitcoinProperties.cs (additionally found)

Regards,
John Ahn

**Comment by jeong760** [comment]
Dears,

Just before I found a GLT new blocks.

[2017-11-12 18:55:16.9602] [I] [BTC] [Pool] [0HL99MA8HM2V3] VarDiff update to 5500
[2017-11-12 18:55:19.0884] [I] [GLT] [Bitcoin Job Manager] Submitting block 255482 [0000000000000cbee695f595e451514758ce9cd5eb1dcebd628b4ed9bf32015d]
[2017-11-12 18:55:19.1770] [I] [GLT] [Bitcoin Job Manager] Daemon accepted block 255482 [0000000000000cbee695f595e451514758ce9cd5eb1dcebd628b4ed9bf32015d]

Regards,
John Ahn

**Comment by oliverw** [comment]
For this to work you need to extend the coin metadata on [the pool](https://github.com/coinfoundry/miningcore/blob/master/src/MiningCore/Blockchain/Bitcoin/BitcoinPool.cs#L33) and the [payout handler](https://github.com/coinfoundry/miningcore/blob/master/src/MiningCore/Blockchain/Bitcoin/BitcoinPayoutHandler.cs#L44). And you will also need to add the coin to the [Bitcoin Properties](https://github.com/coinfoundry/miningcore/blob/master/src/MiningCore/Blockchain/Bitcoin/BitcoinProperties.cs#L71).

**Comment by oliverw** [comment]
@jeong760 Did you get the coin working including payouts?

**Comment by jeong760** [comment]
@oliverw I've mint a 28 of new GLT blocks in total since Nov 12 until today. however, the payment I set every 12 hours to try to pay a mint blocks cost to my address. however these days there were many changes so whenever I found a change I stopped a pool to applies them. so there is no payment log yet.

**Comment by oliverw** [comment]
I'm absolutely open to adding it. Could you submit a PR?

**Comment by jeong760** [comment]
@oliverw Yes, I will open a PR request again. 

Regards,
John Ahn

**Comment by jeong760** [comment]
@oliverw I've opened a new PR request. please merge it your master branch.

**Comment by jeong760** [comment]
@oliverw  payment error has been gone after you several update on miningcore source code.
Only one problem is if pool wallet locked with password, then miningcore cannot prpceed ti payment .

So it could be better to add a wallet passphrase section in config.json and it will be used by miningcore payment process using wallet passphrase command.

**Comment by jeong760** [comment]
@oliverw  I confirmed that Globaltoken(GLT) has been work with miningcore without any issue.

**Comment by oliverw** [comment]
I will merge the PR as soon as the few changes I've requested have been done. Good work!
