### ISSUE TITLE
Retry 1 due to Pgsql: Postgres Exception (42501: no access to shares table)

### ISSUE THREAD

**Issue by Konstantin35** [coinfoundry/miningcore#631]
`psql (PostgreSQL) 11.3 (Ubuntu 11.3-1.pgdg16.04+1)`

After completing these steps
https://github.com/coinfoundry/miningcore#advanced-postgresql-database-setup
or is it just for the cluster
```
[2019-05-20 21:12:05.9887] [I] [StatsRecorder] Updating hashrates for pool reosc1
[2019-05-20 21:12:06.0331] [D] [ShareRepository] GetHashAccumulationBetweenCreatedAsync(reosc1)
[2019-05-20 21:12:06.1027] [W] [StatsRecorder] Retry 1 due to Npgsql: PostgresException (42501: нет доступа к таблице shares)
[2019-05-20 21:12:06.1027] [D] [ShareRepository] GetHashAccumulationBetweenCreatedAsync(reosc1)
[2019-05-20 21:12:06.1171] [W] [StatsRecorder] Retry 2 due to Npgsql: PostgresException (42501: нет доступа к таблице shares)
[2019-05-20 21:12:06.1171] [D] [ShareRepository] GetHashAccumulationBetweenCreatedAsync(reosc1)
[2019-05-20 21:12:06.1201] [W] [StatsRecorder] Retry 3 due to Npgsql: PostgresException (42501: нет доступа к таблице shares)
[2019-05-20 21:12:06.1201] [D] [ShareRepository] GetHashAccumulationBetweenCreatedAsync(reosc1)
[2019-05-20 21:12:06.1201] [W] [StatsRecorder] Retry 4 due to Npgsql: PostgresException (42501: нет доступа к таблице shares)
[2019-05-20 21:12:06.1201] [D] [ShareRepository] GetHashAccumulationBetweenCreatedAsync(reosc1)
[2019-05-20 21:12:06.1365] [E] [StatsRecorder] Npgsql.PostgresException (0x80004005): 42501: нет доступа к таблице shares
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming)
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 419
   at Miningcore.Persistence.Postgres.Repositories.ShareRepository.GetHashAccumulationBetweenCreatedAsync(IDbConnection con, String poolId, DateTime start, DateTime end) in /home/evanto/mining/pool/miningcore/src/Miningcore/Persistence/Postgres/Repositories/ShareRepository.cs:line 197
   at Miningcore.Extensions.ConnectionFactoryExtensions.Run[T](IConnectionFactory factory, Func`2 action)
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Miningcore.Mining.StatsRecorder.UpdatePoolHashratesAsync() in /home/evanto/mining/pool/miningcore/src/Miningcore/Mining/StatsRecorder.cs:line 141
   at Miningcore.Mining.StatsRecorder.<Start>b__20_0() in /home/evanto/mining/pool/miningcore/src/Miningcore/Mining/StatsRecorder.cs:line 97 Npgsql.PostgresException (0x80004005): 42501: нет доступа к таблице shares
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming)
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 419
   at Miningcore.Persistence.Postgres.Repositories.ShareRepository.GetHashAccumulationBetweenCreatedAsync(IDbConnection con, String poolId, DateTime start, DateTime end) in /home/evanto/mining/pool/miningcore/src/Miningcore/Persistence/Postgres/Repositories/ShareRepository.cs:line 197
   at Miningcore.Extensions.ConnectionFactoryExtensions.Run[T](IConnectionFactory factory, Func`2 action)
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Miningcore.Mining.StatsRecorder.UpdatePoolHashratesAsync() in /home/evanto/mining/pool/miningcore/src/Miningcore/Mining/StatsRecorder.cs:line 141
   at Miningcore.Mining.StatsRecorder.<Start>b__20_0() in /home/evanto/mining/pool/miningcore/src/Miningcore/Mining/StatsRecorder.cs:line 97    at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming)
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 419
   at Miningcore.Persistence.Postgres.Repositories.ShareRepository.GetHashAccumulationBetweenCreatedAsync(IDbConnection con, String poolId, DateTime start, DateTime end) in /home/evanto/mining/pool/miningcore/src/Miningcore/Persistence/Postgres/Repositories/ShareRepository.cs:line 197
   at Miningcore.Extensions.ConnectionFactoryExtensions.Run[T](IConnectionFactory factory, Func`2 action)
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Miningcore.Mining.StatsRecorder.UpdatePoolHashratesAsync() in /home/evanto/mining/pool/miningcore/src/Miningcore/Mining/StatsRecorder.cs:line 141
   at Miningcore.Mining.StatsRecorder.<Start>b__20_0() in /home/evanto/mining/pool/miningcore/src/Miningcore/Mining/StatsRecorder.cs:line 97
[2019-05-20 21:12:06.9172] [D] [reosc1] [0HLMT9QJP88VM] [NET] Received data: {"id":42,"method":"mining.submit","params":["0xf2dc0f79394ffcb1d9480b360475afa39a1a3e54","00000001","10000f1d5018"]}
```

**Comment by oliverw** [comment]
@Konstantin35 Is this a migration scenario or a new database?

**Comment by Konstantin35** [comment]
New database

**Comment by oliverw** [comment]
Could you run `sudo -u postgres psql -d miningcore` and then run `\d`?

**Comment by Konstantin35** [comment]
I probably found what it was.
![share](https://user-images.githubusercontent.com/28952414/58043709-89b86100-7b46-11e9-8616-b1a3fadf0fc7.png)

**Comment by oliverw** [comment]
Please run: 

```
ALTER TABLE shares OWNER TO miningcore;
ALTER TABLE shares_reosc1 OWNER TO miningcore;
```

**Comment by Konstantin35** [comment]
Sorry for the carelessness thanks for the help.

**Comment by oliverw** [comment]
@Konstantin35 That was my mistake, not yours. Thanks for bringing this to my attention.
