### ISSUE TITLE
System.ArgumentException when accessing miner API

### ISSUE THREAD

**Issue by craziest** [coinfoundry/miningcore#641]
### Description

An API error occures when accessing /api/pools/{pool}/miners/{address}. 

### Steps to Reproduce

This happened on a completely new set up pool for Ethereum Classic. Three miners are mining on the pool. When trying to access the api page for 2 of the three miners, the following error appears.

### Expected behavior

JSON response with miner summary.

### Actual behavior

500 Error and an error stack that is shown below.

### Reproduces how often

Reproduces every time after it initially appears (not completely sure why some addresses work and others not).

### Version

Running clone of master branch to commit 849cc0d

### Additional Information

Copied from api.log:

[2019-05-31 12:15:46.1680] [I] [WebHost] Request starting HTTP/1.0 GET http://api/api/pools/etc1/miners/0x1B79f9689374915c768aCB95a4C3A4C9f9bd4d3A   
[2019-05-31 12:15:46.1680] [I] [EndpointMiddleware] Executing endpoint 'Miningcore.Api.Controllers.PoolApiController.GetMinerInfoAsync (Miningcore)' 
[2019-05-31 12:15:46.1745] [I] [EndpointMiddleware] Executed endpoint 'Miningcore.Api.Controllers.PoolApiController.GetMinerInfoAsync (Miningcore)' 
[2019-05-31 12:15:46.1745] [E] [Kestrel] Connection id "0HLN5NL54J37H", Request id "0HLN5NL54J37H:00000001": An unhandled exception was thrown by the application. System.ArgumentException: An item with the same key has already been added. Key: VOLI-R0-M1211
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](TSource[] source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Miningcore.Persistence.Postgres.Repositories.StatsRepository.GetMinerStatsAsync(IDbConnection con, IDbTransaction tx, String poolId, String miner) in /var/miningcore/src/Miningcore/Persistence/Postgres/Repositories/StatsRepository.cs:line 219
   at Miningcore.Extensions.ConnectionFactoryExtensions.RunTx[T](IConnectionFactory factory, Func`3 func, Boolean autoCommit, IsolationLevel isolation)
   at Miningcore.Api.Controllers.PoolApiController.GetMinerInfoAsync(String poolId, String address, SampleRange perfMode) in /var/miningcore/src/Miningcore/Api/Controllers/PoolApiController.cs:line 281
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Miningcore.Api.Middlewares.IPAccessWhitelistMiddleware.Invoke(HttpContext context) in /var/miningcore/src/Miningcore/Api/Middlewares/IPAccessWhitelistMiddleware.cs:line 41
   at Miningcore.Api.Middlewares.IPAccessWhitelistMiddleware.Invoke(HttpContext context) in /var/miningcore/src/Miningcore/Api/Middlewares/IPAccessWhitelistMiddleware.cs:line 41
   at Miningcore.Api.Middlewares.ApiExceptionHandlingMiddleware.InvokeAsync(HttpContext context) in /var/miningcore/src/Miningcore/Api/Middlewares/ApiExceptionHandlingMiddleware.cs:line 20
   at AspNetCoreRateLimit.RateLimitMiddleware`1.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)    at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](TSource[] source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Miningcore.Persistence.Postgres.Repositories.StatsRepository.GetMinerStatsAsync(IDbConnection con, IDbTransaction tx, String poolId, String miner) in /var/miningcore/src/Miningcore/Persistence/Postgres/Repositories/StatsRepository.cs:line 219
   at Miningcore.Extensions.ConnectionFactoryExtensions.RunTx[T](IConnectionFactory factory, Func`3 func, Boolean autoCommit, IsolationLevel isolation)
   at Miningcore.Api.Controllers.PoolApiController.GetMinerInfoAsync(String poolId, String address, SampleRange perfMode) in /var/miningcore/src/Miningcore/Api/Controllers/PoolApiController.cs:line 281
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Miningcore.Api.Middlewares.IPAccessWhitelistMiddleware.Invoke(HttpContext context) in /var/miningcore/src/Miningcore/Api/Middlewares/IPAccessWhitelistMiddleware.cs:line 41
   at Miningcore.Api.Middlewares.IPAccessWhitelistMiddleware.Invoke(HttpContext context) in /var/miningcore/src/Miningcore/Api/Middlewares/IPAccessWhitelistMiddleware.cs:line 41
   at Miningcore.Api.Middlewares.ApiExceptionHandlingMiddleware.InvokeAsync(HttpContext context) in /var/miningcore/src/Miningcore/Api/Middlewares/ApiExceptionHandlingMiddleware.cs:line 20
   at AspNetCoreRateLimit.RateLimitMiddleware`1.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
[2019-05-31 12:15:46.1848] [I] [WebHost] Request finished in 16.7774ms 500

**Comment by Konstantin35** [comment]
You can show config.json

**Comment by craziest** [comment]
Here is the config:

`{
    "logging": {
        "level": "info",
        "enableConsoleLog": true,
        "enableConsoleColors": true,
        "logFile": "core.log",
        "apiLogFile": "api.log",
        "logBaseDirectory": "/var/log/miningcore",
        "perPoolLogFile": false
    },

    "banning": {
        "manager": "integrated",
        "banOnJunkReceive": true,
        "banOnInvalidShares": false
    },

    "notifications": {
        "enabled": true,
        "email": {
            "host": "smtp.mailgun.org",
            "port": 587,
            "user": "xxxx",
            "password": "xxxx",
            "fromAddress": "info@lumen.gg",
            "fromName": "Lumen (ETC) Support"
        },
        "admin": {
            "enabled": true,
            "emailAddress": "luka@lumen.gg",
            "notifyBlockFound": true
        }
    },

    "persistence": {
        "postgres": {
            "host": "127.0.0.1",
            "port": 5432,
            "user": "xxxx",
            "password": "xxxx",
            "database": "miningcore"
        }
    },
    "paymentProcessing": {
        "enabled": true,
        "interval": 600,
        "shareRecoveryFile": "recovered-shares.txt"
    },

    "api": {
        "enabled": true,
        "listenAddress": "127.0.0.1",
        "port": 4000,
        "metricsIpWhitelist": [],
        "rateLimiting": {
            "disabled": false,
            "rules": [
                {
                    "Endpoint": "*",
                    "Period": "1s",
                    "Limit": 5
                }
            ],
            "ipWhitelist": []
        }
    },

    "pools": [
        {
            "id": "etc1",
            "enabled": true,
            "coin": "ethereum-classic",
            "address": "xxxx",
            "rewardRecipients": [
                {
                    "address": "xxxx",
                    "percentage": 0.75
                }
            ],
            "blockRefreshInterval": 0,
            "jobRebroadcastTimeout": 10,
            "clientConnectionTimeout": 600,

            "banning": {
                "enabled": true,
                "time": 600,
                "invalidPercent": 50,
                "checkThreshold": 50
            },

            "ports": {
                "4444": {
                    "listenAddress": "0.0.0.0",
                    "difficulty": 0.1,
                    "tls": false,
                    "tlsPfxFile": "/var/lib/certs/mycert.pfx",
                    "varDiff": {
                        "minDiff": 0.05,
                        "maxDiff": null,
                        "targetTime": 15,
                        "retargetTime": 45,
                        "variancePercent": 30,
                        "maxDelta": 500
                    }
                }
            },

            "daemons": [
                {
                    "host": "127.0.0.1",
                    "port": 8945,
                    "user": "user",
                    "password": "password",
                    "portWs": 18545
                }
            ],

            "paymentProcessing": {
                "enabled": true,
                "minimumPayment": 1.0,
                "minimumPaymentToPaymentId": 5.0,
                "payoutScheme": "PPLNS",
                "payoutSchemeConfig": {
                    "factor": 2.0
                },
                "coinbasePassword": "xxxx",
                "keepUncles": false,
                "keepTransactionFees": false
            },

            "minimumConfirmations": 120
        }
    ]
}
`

**Comment by Konstantin35** [comment]
Add IP `"ipWhitelist": []`
`"ipWhitelist": ["ip_on_server_with_web_interface" ]`

**Comment by ultra-pool** [comment]
Iv had the same problem. My api jas beem broken for months. Ipwhitelist doesnt help any
