### ISSUE TITLE
Payout issue after update

### ISSUE THREAD

**Issue by jeong760** [coinfoundry/miningcore#65]
Dears,

I checked a log and found that was related with PPLNS calculation.
- First, it calculated a 1.5% to pool op 
- Second, it calculated a remaining reward after deducted a 1.5% for pool op
- Third, it calculated a PPLNS percent of GLT miner 
- Fourth, it tried to send a reward to two separte address, which poolop and GLT miner
               however following error occurred.

[2017-11-13 00:57:12.1365] [E] [PayoutManager] [GLT] Payment processing failed MiningCore.DaemonInterface.DaemonClientException: Internal Server Error
   at MiningCore.DaemonInterface.DaemonClient.<BuildRequestTask>d__15.MoveNext() in D:\git\miningcore\src\MiningCore\DaemonInterface\DaemonClient.cs:line 235
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.DaemonInterface.DaemonClient.<ExecuteCmdSingleAsync>d__13`1.MoveNext() in D:\git\miningcore\src\MiningCore\DaemonInterface\DaemonClient.cs:line 179
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Bitcoin.BitcoinPayoutHandler.<PayoutAsync>d__9.MoveNext() in D:\git\miningcore\src\MiningCore\Blockchain\Bitcoin\BitcoinPayoutHandler.cs:line 233
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Payments.PayoutManager.<PayoutPoolBalancesAsync>d__13.MoveNext() in D:\git\miningcore\src\MiningCore\Payments\PayoutManager.cs:line 164
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at MiningCore.Payments.PayoutManager.<PayoutPoolBalancesAsync>d__13.MoveNext() in D:\git\miningcore\src\MiningCore\Payments\PayoutManager.cs:line 175
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Payments.PayoutManager.<ProcessPoolsAsync>d__11.MoveNext() in D:\git\miningcore\src\MiningCore\Payments\PayoutManager.cs:line 97    at MiningCore.DaemonInterface.DaemonClient.<BuildRequestTask>d__15.MoveNext() in D:\git\miningcore\src\MiningCore\DaemonInterface\DaemonClient.cs:line 235
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.DaemonInterface.DaemonClient.<ExecuteCmdSingleAsync>d__13`1.MoveNext() in D:\git\miningcore\src\MiningCore\DaemonInterface\DaemonClient.cs:line 179
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Bitcoin.BitcoinPayoutHandler.<PayoutAsync>d__9.MoveNext() in D:\git\miningcore\src\MiningCore\Blockchain\Bitcoin\BitcoinPayoutHandler.cs:line 233
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Payments.PayoutManager.<PayoutPoolBalancesAsync>d__13.MoveNext() in D:\git\miningcore\src\MiningCore\Payments\PayoutManager.cs:line 164
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at MiningCore.Payments.PayoutManager.<PayoutPoolBalancesAsync>d__13.MoveNext() in D:\git\miningcore\src\MiningCore\Payments\PayoutManager.cs:line 175
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Payments.PayoutManager.<ProcessPoolsAsync>d__11.MoveNext() in D:\git\miningcore\src\MiningCore\Payments\PayoutManager.cs:line 97

**Comment by jeong760** [comment]
[2017-11-12 23:55:15.6853] [I] [PayoutManager] Processing payments for pool GLT 
[2017-11-12 23:55:15.7078] [I] [GLT] [Bitcoin Payout Handler] Unlocked block 255482 worth 100 GLT 
[2017-11-12 23:55:15.7133] [I] [PayoutManager] Processing payments for pool GLT, block 255482 
[2017-11-12 23:55:15.7342] [I] [GLT] Adding 1.5 GLT to balance of GR75m73cMwbgjVXUsUdDaTtVa7zRdfFtFS 
[2017-11-12 23:55:16.3006] [I] [PayPerLastNShares] Balance-calculation completed with accumulated score 0.0444 (2.2%) 
[2017-11-12 23:55:16.3217] [I] [PayPerLastNShares] Adding 2.18503 GLT to balance of GVrPkXik9dFYvx7jF8eH1v3UMrr6H7XvxG for 39 shares 
[2017-11-12 23:55:16.7159] [I] [PayPerLastNShares] 39 shares contributed to a total payout of 2.18503 GLT (2.22% of block reward)

[2017-11-12 23:55:16.8040] [E] [PayoutManager] [GLT] Payment processing failed MiningCore.DaemonInterface.DaemonClientException: Internal Server Error

**Comment by jeong760** [comment]
I use a local wallet address of both (sender and receiver). I mean that send a coin from pool wallet to pool wallet address.

**Comment by oliverw** [comment]
Strange. It crashes in Line 233 but I'm missing the log output from Line 219 in your log - https://github.com/coinfoundry/miningcore/blob/master/src/MiningCore/Blockchain/Bitcoin/BitcoinPayoutHandler.cs#L219

**Comment by oliverw** [comment]
Any chance for you to debug this?

**Comment by jeong760** [comment]
@oliverw, What should I post or give related with this  error? 

I  am under test a miningcore on  windows computer, there installed a BTC and GLT wallet. for sure I uses a both of wallet and its address for payment send and received. 

**Total GLT balance on payment address is 200GLT.**

**Payment step.** 

Unlocked a block(255482) ---> Processing paymnets for pool  GLT, block 255482 ----> Adding 1.5 GLT to OP address ---> PPLNS adding 2.18503 GLT to blance of miner addrerss (2.22%) ---> Payment failed 

**The paymanet process  log of GLT.** 

[2017-11-12 23:55:15.7078] [I] [GLT] [Bitcoin Payout Handler] Unlocked block 255482 worth 100 GLT
[2017-11-12 23:55:15.7133] [I] [PayoutManager] Processing payments for pool GLT, block 255482
[2017-11-12 23:55:15.7342] [I] [GLT] Adding 1.5 GLT to balance of GR75m73cMwbgjVXUsUdDaTtVa7zRdfFtFS
[2017-11-12 23:55:16.3006] [I] [PayPerLastNShares] Balance-calculation completed with accumulated score 0.0444 (2.2%)
[2017-11-12 23:55:16.3217] [I] [PayPerLastNShares] Adding 2.18503 GLT to balance of GVrPkXik9dFYvx7jF8eH1v3UMrr6H7XvxG for 39 shares
[2017-11-12 23:55:16.7159] [I] [PayPerLastNShares] 39 shares contributed to a total payout of 2.18503 GLT (2.22% of block reward)
[2017-11-12 23:55:16.8040] [E] [PayoutManager] [GLT] Payment processing failed MiningCore.DaemonInterface.DaemonClientException: Internal Server Error

**Comment by jeong760** [comment]
@oliverw could you write here exactly what you needed for debug?
