### ISSUE TITLE
Clustering - ZeroMQ.lib.zmq threw and exception

### ISSUE THREAD

**Issue by danielbjornadal** [coinfoundry/miningcore#667]
### Description
config.json: (trunkated)
```
{
    ...
    "api": {
        "enabled": true,
        "listenAddress": "0.0.0.0",
        "port": 80,
        "adminPort": 8080
    },
    "shareRelay": {
        "publishUrl": "tcp://0.0.0.0:6000",
        "sharedEncryptionKey": "testkey"
    },
    ...
}
```

Error:
```
[2019-07-12 07:27:07.7708] [W] [Core] Running as root is discouraged!
[2019-07-12 07:27:07.9630] [I] [Core] .NET Core 4.6.27617.05 on Linux 4.4.0-142-generic #168-Ubuntu SMP Wed Jan 16 21:00:45 UTC 2019 [X64]
[2019-07-12 07:27:08.6642] [I] [Core] 46 coins loaded from /dotnetapp/coins.json
System.AggregateException: One or more errors occurred. (The type initializer for 'ZeroMQ.lib.zmq' threw an exception.) ---> System.TypeInitializationException: The type initializer for 'ZeroMQ.lib.zmq' threw an exception. ---> System.DllNotFoundException: Unable to load shared library 'libzmq' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibzmq: cannot open shared object file: No such file or directory
at ZeroMQ.lib.zmq.version(Int32& major, Int32& minor, Int32& patch)
at ZeroMQ.lib.zmq..cctor()
--- End of inner exception stack trace ---
at ZeroMQ.lib.zmq.ctx_new()
at ZeroMQ.ZContext..ctor()
at ZeroMQ.ZContext.get_Current()
at Miningcore.Mining.ShareRelay.Start(ClusterConfig clusterConfig) in /tmp/miningcore/src/Miningcore/Mining/ShareRelay.cs:line 58
at Miningcore.Program.Start() in /tmp/miningcore/src/Miningcore/Program.cs:line 818
--- End of inner exception stack trace ---
at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
at Miningcore.Program.Main(String[] args) in /tmp/miningcore/src/Miningcore/Program.cs:line 109
---> (Inner Exception #0) System.TypeInitializationException: The type initializer for 'ZeroMQ.lib.zmq' threw an exception. ---> System.DllNotFoundException: Unable to load shared library 'libzmq' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibzmq: cannot open shared object file: No such file or directory
at ZeroMQ.lib.zmq.version(Int32& major, Int32& minor, Int32& patch)
at ZeroMQ.lib.zmq..cctor()
--- End of inner exception stack trace ---
at ZeroMQ.lib.zmq.ctx_new()
at ZeroMQ.ZContext..ctor()
at ZeroMQ.ZContext.get_Current()
at Miningcore.Mining.ShareRelay.Start(ClusterConfig clusterConfig) in /tmp/miningcore/src/Miningcore/Mining/ShareRelay.cs:line 58
at Miningcore.Program.Start() in /tmp/miningcore/src/Miningcore/Program.cs:line 818<---
Cluster cannot start. Good Bye!
[2019-07-12 07:27:09.3346] [I] [Core] Shutdown ...
Shutdown...
[2019-07-12 07:27:09.3698] [I] [ShareRelay] Stopping ..
[2019-07-12 07:27:09.4002] [E] [Core] System.NullReferenceException: Object reference not set to an instance of an object.
at Miningcore.Mining.ShareRelay.Stop() in /tmp/miningcore/src/Miningcore/Mining/ShareRelay.cs:line 90
at Miningcore.Program.Shutdown() in /tmp/miningcore/src/Miningcore/Program.cs:line 929
at Miningcore.Program.Main(String[] args) in /tmp/miningcore/src/Miningcore/Program.cs:line 179 System.NullReferenceException: Object reference not set to an instance of an object.
at Miningcore.Mining.ShareRelay.Stop() in /tmp/miningcore/src/Miningcore/Mining/ShareRelay.cs:line 90
at Miningcore.Program.Shutdown() in /tmp/miningcore/src/Miningcore/Program.cs:line 929
at Miningcore.Program.Main(String[] args) in /tmp/miningcore/src/Miningcore/Program.cs:line 179 at Miningcore.Mining.ShareRelay.Stop() in /tmp/miningcore/src/Miningcore/Mining/ShareRelay.cs:line 90
at Miningcore.Program.Shutdown() in /tmp/miningcore/src/Miningcore/Program.cs:line 929
at Miningcore.Program.Main(String[] args) in /tmp/miningcore/src/Miningcore/Program.cs:line 179
** AppDomain unhandled exception: System.NullReferenceException: Object reference not set to an instance of an object.
at Miningcore.Mining.ShareRelay.Stop() in /tmp/miningcore/src/Miningcore/Mining/ShareRelay.cs:line 90
at Miningcore.Program.Shutdown() in /tmp/miningcore/src/Miningcore/Program.cs:line 929
at Miningcore.Program.Main(String[] args) in /tmp/miningcore/src/Miningcore/Program.cs:line 179
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
at Miningcore.Mining.ShareRelay.Stop() in /tmp/miningcore/src/Miningcore/Mining/ShareRelay.cs:line 90
at Miningcore.Program.Shutdown() in /tmp/miningcore/src/Miningcore/Program.cs:line 929
at Miningcore.Program.Main(String[] args) in /tmp/miningcore/src/Miningcore/Program.cs:line 179
Aborted (core dumped)
```

### Version

Master branch on this Github repo.

**Comment by Konstantin35** [comment]
[https://gist.github.com/Konstantin35/9cc735c75ef20124d755c1736ffdeae6](https://gist.github.com/Konstantin35/9cc735c75ef20124d755c1736ffdeae6)

**Comment by saltyminer** [comment]
Did you figure this out?  What OS?

**Comment by saltyminer** [comment]
For Ubuntu 18.04 I had to use this to get past your error.

sudo apt-get install libzmq3-dev
