### ISSUE TITLE
problem while connecting monero daemons 

### ISSUE THREAD

**Issue by mostafa-helmy13** [coinfoundry/miningcore#670]
### Description

pool unable to connect to monero daemons 

Using configuration file config.json

[2019-07-21 21:30:29.0710] [I] [Core] .NET Core 4.6.27817.03 on Linux 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 [X64] 
[2019-07-21 21:30:29.3641] [I] [Core] 46 coins loaded from /home/monero/miningcore/build/coins.json 
[2019-07-21 21:30:29.7005] [I] [ShareRecorder] Online 
[2019-07-21 21:30:31.5115] [I] [XmlKeyManager] User profile is available. Using '/home/monero/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest. 
[2019-07-21 21:30:31.8923] [I] [Core] API Access to /api/admin restricted to 127.0.0.1,::1,::ffff:127.0.0.1 
[2019-07-21 21:30:31.8923] [I] [Core] API Access to /metrics restricted to 127.0.0.1,::1,::ffff:127.0.0.1 
[2019-07-21 21:30:32.3964] [I] [Core] API access limited to 5 requests per 1s, except from 127.0.0.1, ::1, ::ffff:127.0.0.1 
[2019-07-21 21:30:32.4440] [I] [Core] API Online @ 127.0.0.1:4000 
[2019-07-21 21:30:32.4440] [I] [Core] Prometheus Metrics Online @ 127.0.0.1:4000/metrics 
[2019-07-21 21:30:32.4440] [I] [Core] WebSocket notifications streaming @ 127.0.0.1:4000/notifications 
[2019-07-21 21:30:32.4806] [I] [PayoutManager] Online 
[2019-07-21 21:30:32.4806] [I] [StatsRecorder] Online 
[2019-07-21 21:30:32.4974] [I] [PayoutManager] Processing payments for pool xmr1 
[2019-07-21 21:30:32.5789] [I] [xmr1] Starting Pool ... 
[2019-07-21 21:30:32.6517] [I] [xmr1] Starting Job Manager ... 
[2019-07-21 21:30:32.8463] [I] [xmr1] Waiting for daemons to come online ... 
[2019-07-21 21:30:32.8501] [E] [PayoutManager] [xmr1] Payment processing failed Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Miningcore.DaemonInterface.DaemonClient.MapDaemonResponse[TResponse](Int32 i, Task`1 x, Boolean throwOnError) in /home/monero/miningcore/src/Miningcore/DaemonInterface/DaemonClient.cs:line 446
   at Miningcore.DaemonInterface.DaemonClient.ExecuteCmdAnyAsync[TResponse](ILogger logger, String method, Object payload, JsonSerializerSettings payloadJsonSerializerSettings, Boolean throwOnError)
   at Miningcore.Blockchain.Cryptonote.CryptonotePayoutHandler.GetNetworkTypeAsync() in /home/monero/miningcore/src/Miningcore/Blockchain/Cryptonote/CryptonotePayoutHandler.cs:line 137
   at Miningcore.Blockchain.Cryptonote.CryptonotePayoutHandler.ConfigureAsync(ClusterConfig clusterConfig, PoolConfig poolConfig) in /home/monero/miningcore/src/Miningcore/Blockchain/Cryptonote/CryptonotePayoutHandler.cs:line 340
   at Miningcore.Payments.PayoutManager.ProcessPoolsAsync() in /home/monero/miningcore/src/Miningcore/Payments/PayoutManager.cs:line 97    at Miningcore.DaemonInterface.DaemonClient.MapDaemonResponse[TResponse](Int32 i, Task`1 x, Boolean throwOnError) in /home/monero/miningcore/src/Miningcore/DaemonInterface/DaemonClient.cs:line 446
   at Miningcore.DaemonInterface.DaemonClient.ExecuteCmdAnyAsync[TResponse](ILogger logger, String method, Object payload, JsonSerializerSettings payloadJsonSerializerSettings, Boolean throwOnError)
   at Miningcore.Blockchain.Cryptonote.CryptonotePayoutHandler.GetNetworkTypeAsync() in /home/monero/miningcore/src/Miningcore/Blockchain/Cryptonote/CryptonotePayoutHandler.cs:line 137
   at Miningcore.Blockchain.Cryptonote.CryptonotePayoutHandler.ConfigureAsync(ClusterConfig clusterConfig, PoolConfig poolConfig) in /home/monero/miningcore/src/Miningcore/Blockchain/Cryptonote/CryptonotePayoutHandler.cs:line 340
   at Miningcore.Payments.PayoutManager.ProcessPoolsAsync() in /home/monero/miningcore/src/Miningcore/Payments/PayoutManager.cs:line 97
[2019-07-21 21:30:42.4986] [I] [StatsRecorder] Updating hashrates for pool xmr1 
[2019-07-21 21:30:42.8599] [I] [xmr1] Waiting for daemons to come online ... 
[2019-07-21 21:30:44.6812] [I] [StatsRecorder] Reset performance stats for pool xmr1 
[2019-07-21 21:30:45.0324] [I] [StatsRecorder] Performing Stats GC 
[2019-07-21 21:30:45.0502] [I] [StatsRecorder] Stats GC complete 
[2019-07-21 21:30:52.8599] [I] [xmr1] Waiting for daemons to come online ... 
[2019-07-21 21:31:02.8617] [I] [xmr1] Waiting for daemons to come online ... 
[2019-07-21 21:31:12.8625] [I] [xmr1] Waiting for daemons to come online ... 
[2019-07-21 21:31:22.8638] [I] [xmr1] Waiting for daemons to come online ... 
[2019-07-21 21:31:32.8645] [I] [xmr1] Waiting for daemons to come online ... 
[2019-07-21 21:31:42.8656] [I] [xmr1] Waiting for daemons to come online ... 
[2019-07-21 21:31:52.8712] [I] [xmr1] Waiting for daemons to come online ... 
[2019-07-21 21:32:02.8724] [I] [xmr1] Waiting for daemons to come online ... 
[2019-07-21 21:32:12.8741] [I] [xmr1] Waiting for daemons to come online ... 
[2019-07-21 21:32:22.8793] [I] [xmr1] Waiting for daemons to come online ... 
[2019-07-21 21:32:32.8818] [I] [xmr1] Waiting for daemons to come online ... 
[2019-07-21 21:32:42.8827] [I] [xmr1] Waiting for daemons to come online ... 
[2019-07-21 21:32:52.8847] [I] [xmr1] Waiting for daemons to come online ... 
[2019-07-21 21:33:02.8816] [I] [xmr1] Waiting for daemons to come online ... 
[2019-07-21 21:33:12.8846] [I] [xmr1] Waiting for daemons to come online ... 
[2019-07-21 21:33:22.8846] [I] [xmr1] Waiting for daemons to come online ... 
[2019-07-21 21:33:32.8859] [I] [xmr1] Waiting for daemons to come online ... 
[2019-07-21 21:33:42.8878] [I] [xmr1] Waiting for daemons to come online ... 
[2019-07-21 21:33:52.8894] [I] [xmr1] Waiting for daemons to come online ... 
[2019-07-21 21:34:02.8931] [I] [xmr1] Waiting for daemons to come online ... 
[2019-07-21 21:34:12.8928] [I] [xmr1] Waiting for daemons to come online ... 
[2019-07-21 21:34:22.8963] [I] [xmr1] Waiting for daemons to come online ... 
[2019-07-21 21:34:32.8971] [I] [xmr1] Waiting for daemons to come online ... 
[2019-07-21 21:34:42.8979] [I] [xmr1] Waiting for daemons to come online ... 
[2019-07-21 21:34:52.8968] [I] [xmr1] Waiting for daemons to come online ... 

### Steps to Reproduce

1. started monerod using this command 
/home/monero/monero/./monerod --log-file /home/monero/logs/monerod.log --log-level 0 --data-dir /home/monero/.bitmonero --rpc-bind-ip 127.0.0.1  --rpc-bind-port 18081 --rpc-login mem:<removed>  --confirm-external-bind --hide-my-port --p2p-bind-ip 0.0.0.0 --p2p-bind-port 18080 --detach
2. started monero-wallet-rpc using this command 
/home/monero/monero/./monero-wallet-rpc --daemon-address 127.0.0.1:18081 --trusted-daemon --daemon-login mem:<removed>  --rpc-bind-port 28081 --rpc-bind-ip 127.0.0.1 --rpc-login mem:<removed>--confirm-external-bind --wallet-file /home/monero/wallet/mem --password <removed>  --log-file /home/monero/logs/monero-rpc.log --log-level 0  --detach

3. started mining core 

### Expected behavior

connect to demons 
### Actual behavior

throu msg wating daemons to come online

### Reproduces how often

all ways 

### Version

mining core v 50 and monero core v 14.1

### Additional Information

monerod logs 
[monerod.log](https://github.com/coinfoundry/miningcore/files/3414995/monerod.log)
rpclogs 
[monero-rpc.log](https://github.com/coinfoundry/miningcore/files/3414996/monero-rpc.log)  
miningcore config 
'''
      "daemons": [
        {
          "host": "127.0.0.1",
          "port": 18081,
           "user": "mem",
          "password": "xxxx"
       },
        {
          "host": "127.0.0.1",
          "port": 28081,
          "user": "mem",
          "password": "xxxx",
          "category": "wallet"
        }
      ],
      "paymentProcessing": {
        "enabled": true,
        "minimumPayment": 0.01   ,
        "minimumPaymentToPaymentId": 0.1,
        "payoutScheme": "PPLNS",
        "payoutSchemeConfig": {
          "factor": 2.0
        }
      }
    }]

'''

**Comment by saltyminer** [comment]
Try this:

**start monerod using this command**
monerod  --log-file monerod.log --detach --rpc-bind-ip 127.0.0.1 --rpc-bind-port 18081 --out-peers 32 --p2p-bind-ip 0.0.0.0 --p2p-bind-port 18080 

**start monero-wallet-rpc using this command**
monero-wallet-rpc --wallet-file <WalletFileName>--daemon-address 127.0.0.1:18081 --log-level 1 --password <Password>--rpc-bind-port 18083 --rpc-bind-ip 127.0.0.1 --rpc-login <RPCLoginName>:<RPCPassword>

**Config file**
"daemons": [
        {
          "host": "127.0.0.1",
          "port": 18081,
          "user": "<RPCLoginName>",
          "password": "<RPCPassword>"
        },
        {
          "host": "127.0.0.1",
          "port": 18083,
          "user": "<RPCLoginName>",
          "password": "<RPCPassword>",
          "category": "wallet"
        }
      ],
