### ISSUE TITLE
Peercoin Correctly Implemented? 

### ISSUE THREAD

**Issue by pfeiflelukas** [coinfoundry/miningcore#75]
@oliverw I have successfully got Dash, Namecoin, Vertcoin and Monacoin working but when i try to implement Peercoin the server crashes. It isnt a networking issue.

  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.JobManagerBase`1.<StartDaemonAsync>d__12.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockchain/JobManagerBase.cs:line 57
--- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.JobManagerBase`1.<StartAsync>d__19.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockchain/JobManagerBase.cs:line 110
--- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Bitcoin.BitcoinPoolBase`2.<SetupJobManager>d__10.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockchain/Bitcoin/BitcoinPoolBase.cs:line 
273                                                                                                                                                                                     
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()   at system.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Mining.PoolBase`1.<StartAsync>d__42.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Mining/PoolBase.cs:line 404 at Newtonsoft.Json.JsonReader.ReadInt32String(String s)                                                                                                                                                                     
   at Newtonsoft.Json.JsonReader.ReadAsInt32() at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract cont
ainerContract, JsonProperty containerMember, Object existingValue)                                                                                                                  
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
   at MiningCore.DaemonInterface.DaemonClient.MapDaemonResponse[TResponse](Int32 i, Task`1 x) in /home/cryptocentralized/miningcore/src/MiningCore/DaemonInterface/DaemonClient.cs:line 
319                                                                                                                                                                                     
   at System.Linq.Enumerable.<SelectIterator>d__154`2.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at MiningCore.DaemonInterface.DaemonClient.<ExecuteCmdAllAsync>d__9`1.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/DaemonInterface/DaemonClient.cs:line 119
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Bitcoin.BitcoinJobManager`2.<AreDaemonsHealthy>d__43.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockchain/Bitcoin/BitcoinJobManager.cs
:line 372                                                                                                                                                                               
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.JobManagerBase`1.<StartDaemonAsync>d__12.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockchain/JobManagerBase.cs:line 57
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.JobManagerBase`1.<StartAsync>d__19.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockchain/JobManagerBase.cs:line 110
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Bitcoin.BitcoinPoolBase`2.<SetupJobManager>d__10.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockchain/Bitcoin/BitcoinPoolBase.cs:line 
273                                                                                                                                                                                     
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Mining.PoolBase`1.<StartAsync>d__42.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Mining/PoolBase.cs:line 404

**Comment by oliverw** [comment]
Should be fixed now.
