### ISSUE TITLE
New Commits Crash Server

### ISSUE THREAD

**Issue by pfeiflelukas** [coinfoundry/miningcore#82]
@oliverw I just pulled the new commits and now the server wont start with the previous config file. Did the config file change in anyway?

[2017-11-19 03:58:24.1193] [E] [litecoin] System.NullReferenceException: Object reference not set to an instance of an object.
   at MiningCore.Blockchain.Bitcoin.BitcoinJobManager`2.<AreDaemonsConnected>d__44.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockchain/Bitcoin/BitcoinJobManager.cs:line 386
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.JobManagerBase`1.<StartDaemonAsync>d__12.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockchain/JobManagerBase.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.JobManagerBase`1.<StartAsync>d__19.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockchain/JobManagerBase.cs:line 110
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Bitcoin.BitcoinPoolBase`2.<SetupJobManager>d__10.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockchain/Bitcoin/BitcoinPoolBase.cs:line 281
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Mining.PoolBase`1.<StartAsync>d__42.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Mining/PoolBase.cs:line 404 System.NullReferenceException: Object reference not set to an instance of an object.
   at MiningCore.Blockchain.Bitcoin.BitcoinJobManager`2.<AreDaemonsConnected>d__44.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockchain/Bitcoin/BitcoinJobManager.cs:line 386
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.JobManagerBase`1.<StartDaemonAsync>d__12.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockchain/JobManagerBase.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.JobManagerBase`1.<StartAsync>d__19.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockchain/JobManagerBase.cs:line 110
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Bitcoin.BitcoinPoolBase`2.<SetupJobManager>d__10.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockchain/Bitcoin/BitcoinPoolBase.cs:line 281
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Mining.PoolBase`1.<StartAsync>d__42.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Mining/PoolBase.cs:line 404    at MiningCore.Blockchain.Bitcoin.BitcoinJobManager`2.<AreDaemonsConnected>d__44.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockchain/Bitcoin/BitcoinJobManager.cs:line 386
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.JobManagerBase`1.<StartDaemonAsync>d__12.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockchain/JobManagerBase.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.JobManagerBase`1.<StartAsync>d__19.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockchain/JobManagerBase.cs:line 110
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Bitcoin.BitcoinPoolBase`2.<SetupJobManager>d__10.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockchain/Bitcoin/BitcoinPoolBase.cs:line 281
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Mining.PoolBase`1.<StartAsync>d__42.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Mining/PoolBase.cs:line 404
[2017-11-19 03:58:24.1193] [E] [namecoin] System.NullReferenceException: Object reference not set to an instance of an object.
   at MiningCore.Blockchain.Bitcoin.BitcoinJobManager`2.<AreDaemonsConnected>d__44.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockchain/Bitcoin/BitcoinJobManager.cs:line 386
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.JobManagerBase`1.<StartDaemonAsync>d__12.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockchain/JobManagerBase.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.JobManagerBase`1.<StartAsync>d__19.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockchain/JobManagerBase.cs:line 110
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Bitcoin.BitcoinPoolBase`2.<SetupJobManager>d__10.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockchain/Bitcoin/BitcoinPoolBase.cs:line 281
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Mining.PoolBase`1.<StartAsync>d__42.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Mining/PoolBase.cs:line 404 System.NullReferenceException: Object reference not set to an instance of an object.
   at MiningCore.Blockchain.Bitcoin.BitcoinJobManager`2.<AreDaemonsConnected>d__44.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockchain/Bitcoin/BitcoinJobManager.cs:line 386
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.JobManagerBase`1.<StartDaemonAsync>d__12.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockchain/JobManagerBase.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.JobManagerBase`1.<StartAsync>d__19.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockchain/JobManagerBase.cs:line 110
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Bitcoin.BitcoinPoolBase`2.<SetupJobManager>d__10.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockchain/Bitcoin/BitcoinPoolBase.cs:line 281
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Mining.PoolBase`1.<StartAsync>d__42.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Mining/PoolBase.cs:line 404    at MiningCore.Blockchain.Bitcoin.BitcoinJobManager`2.<AreDaemonsConnected>d__44.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockchain/Bitcoin/BitcoinJobManager.cs:line 386
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.JobManagerBase`1.<StartDaemonAsync>d__12.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockchain/JobManagerBase.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.JobManagerBase`1.<StartAsync>d__19.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockchain/JobManagerBase.cs:line 110
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Bitcoin.BitcoinPoolBase`2.<SetupJobManager>d__10.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockchain/Bitcoin/BitcoinPoolBase.cs:line 281
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Mining.PoolBase`1.<StartAsync>d__42.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Mining/PoolBase.cs:line 404
[2017-11-19 03:58:24.1366] [E] [vertcoin] System.NullReferenceException: Object reference not set to an instance of an object.
   at MiningCore.Blockchain.Bitcoin.BitcoinJobManager`2.<AreDaemonsConnected>d__44.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockchain/Bitcoin/BitcoinJobManager.cs:line 386
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.JobManagerBase`1.<StartDaemonAsync>d__12.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockchain/JobManagerBase.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.JobManagerBase`1.<StartAsync>d__19.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockchain/JobManagerBase.cs:line 110
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Bitcoin.BitcoinPoolBase`2.<SetupJobManager>d__10.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockchain/Bitcoin/BitcoinPoolBase.cs:line 281
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Mining.PoolBase`1.<StartAsync>d__42.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Mining/PoolBase.cs:line 404 System.NullReferenceException: Object reference not set to an instance of an object.
   at MiningCore.Blockchain.Bitcoin.BitcoinJobManager`2.<AreDaemonsConnected>d__44.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockchain/Bitcoin/BitcoinJobManager.cs:line 386
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.JobManagerBase`1.<StartDaemonAsync>d__12.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockchain/JobManagerBase.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.JobManagerBase`1.<StartAsync>d__19.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockchain/JobManagerBase.cs:line 110
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Bitcoin.BitcoinPoolBase`2.<SetupJobManager>d__10.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockchain/Bitcoin/BitcoinPoolBase.cs:line 281
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Mining.PoolBase`1.<StartAsync>d__42.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Mining/PoolBase.cs:line 404    at MiningCore.Blockchain.Bitcoin.BitcoinJobManager`2.<AreDaemonsConnected>d__44.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockchain/Bitcoin/BitcoinJobManager.cs:line 386
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.JobManagerBase`1.<StartDaemonAsync>d__12.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockchain/JobManagerBase.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.JobManagerBase`1.<StartAsync>d__19.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockchain/JobManagerBase.cs:line 110
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Bitcoin.BitcoinPoolBase`2.<SetupJobManager>d__10.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockchain/Bitcoin/BitcoinPoolBase.cs:line 281
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Mining.PoolBase`1.<StartAsync>d__42.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Mining/PoolBase.cs:line 404
[2017-11-19 03:58:24.2080] [E] [monacoin] System.NullReferenceException: Object reference not set to an instance of an object.
   at MiningCore.Blockchain.Bitcoin.BitcoinJobManager`2.<AreDaemonsConnected>d__44.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockchain/Bitcoin/BitcoinJobManager.cs:line 386
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.JobManagerBase`1.<StartDaemonAsync>d__12.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockchain/JobManagerBase.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.JobManagerBase`1.<StartAsync>d__19.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockchain/JobManagerBase.cs:line 110
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Bitcoin.BitcoinPoolBase`2.<SetupJobManager>d__10.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockchain/Bitcoin/BitcoinPoolBase.cs:line 281
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Mining.PoolBase`1.<StartAsync>d__42.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Mining/PoolBase.cs:line 404 System.NullReferenceException: Object reference not set to an instance of an object.
   at MiningCore.Blockchain.Bitcoin.BitcoinJobManager`2.<AreDaemonsConnected>d__44.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockchain/Bitcoin/BitcoinJobManager.cs:line 386
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.JobManagerBase`1.<StartDaemonAsync>d__12.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockchain/JobManagerBase.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.JobManagerBase`1.<StartAsync>d__19.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockchain/JobManagerBase.cs:line 110
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Bitcoin.BitcoinPoolBase`2.<SetupJobManager>d__10.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockchain/Bitcoin/BitcoinPoolBase.cs:line 281
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Mining.PoolBase`1.<StartAsync>d__42.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Mining/PoolBase.cs:line 404    at MiningCore.Blockchain.Bitcoin.BitcoinJobManager`2.<AreDaemonsConnected>d__44.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockchain/Bitcoin/BitcoinJobManager.cs:line 386
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.JobManagerBase`1.<StartDaemonAsync>d__12.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockchain/JobManagerBase.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.JobManagerBase`1.<StartAsync>d__19.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockchain/JobManagerBase.cs:line 110
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Bitcoin.BitcoinPoolBase`2.<SetupJobManager>d__10.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockchain/Bitcoin/BitcoinPoolBase.cs:line 281
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Mining.PoolBase`1.<StartAsync>d__42.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Mining/PoolBase.cs:line 404
[2017-11-19 03:58:24.6229] [I] [dash] [Bitcoin Job Manager] All daemons online 
[2017-11-19 03:58:25.4038] [E] [dash] System.NullReferenceException: Object reference not set to an instance of an object.
   at MiningCore.Blockchain.Bitcoin.BitcoinJobManager`2.<AreDaemonsConnected>d__44.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockchain/Bitcoin/BitcoinJobManager.cs:line 386
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.JobManagerBase`1.<StartDaemonAsync>d__12.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockchain/JobManagerBase.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.JobManagerBase`1.<StartAsync>d__19.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockchain/Jo
bManagerBase.cs:line 110
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Bitcoin.BitcoinPoolBase`2.<SetupJobManager>d__10.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore
/Blockchain/Bitcoin/BitcoinPoolBase.cs:line 281
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Mining.PoolBase`1.<StartAsync>d__42.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Mining/PoolBase.cs:line
 404 System.NullReferenceException: Object reference not set to an instance of an object.
   at MiningCore.Blockchain.Bitcoin.BitcoinJobManager`2.<AreDaemonsConnected>d__44.MoveNext() in /home/cryptocentralized/miningcore/src/Mini
ngCore/Blockchain/Bitcoin/BitcoinJobManager.cs:line 386
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.JobManagerBase`1.<StartDaemonAsync>d__12.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockch
ain/JobManagerBase.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.JobManagerBase`1.<StartAsync>d__19.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockchain/Jo
bManagerBase.cs:line 110
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Bitcoin.BitcoinPoolBase`2.<SetupJobManager>d__10.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore
/Blockchain/Bitcoin/BitcoinPoolBase.cs:line 281
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Mining.PoolBase`1.<StartAsync>d__42.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Mining/PoolBase.cs:line
 404    at MiningCore.Blockchain.Bitcoin.BitcoinJobManager`2.<AreDaemonsConnected>d__44.MoveNext() in /home/cryptocentralized/miningcore/src
/MiningCore/Blockchain/Bitcoin/BitcoinJobManager.cs:line 386
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.JobManagerBase`1.<StartDaemonAsync>d__12.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockch
ain/JobManagerBase.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.JobManagerBase`1.<StartAsync>d__19.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockchain/Jo
bManagerBase.cs:line 110
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Bitcoin.BitcoinPoolBase`2.<SetupJobManager>d__10.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore
/Blockchain/Bitcoin/BitcoinPoolBase.cs:line 281
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Mining.PoolBase`1.<StartAsync>d__42.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Mining/PoolBase.cs:line
 404

**Comment by oliverw** [comment]
No not in this area. Looking at the top level error suggests that the Job Manager does not have a daemon at all. As if your config didn't contain any.

**Comment by pfeiflelukas** [comment]
I am using the default config file with only one coin. Any suggestions?

**Comment by oliverw** [comment]
Could you send the config with sensitive elements replaced by dummies to info@poolmining.org

**Comment by pfeiflelukas** [comment]
Just did :)

**Comment by pfeiflelukas** [comment]
@oliverw I have moved to a different VM reinstalled postgresql and setup, installed dependencies and recompiled miningcore. The build succeeded and i placed the config file in the build directory and then re-ran the program and the same output occurred.

Using configuration file config.json
[2017-11-20 03:53:11.5335] [I] [ShareRecorder] Online 
[2017-11-20 03:53:11.5649] [I] [ApiServer] Launching ... 
[2017-11-20 03:53:11.7888] [I] [ApiServer] Online @ 127.0.0.1:4000 
[2017-11-20 03:53:11.8150] [I] [dash] [Pool] Launching ... 
[2017-11-20 03:53:11.8446] [I] [dash] [Bitcoin Job Manager] Launching ... 
[2017-11-20 03:53:11.9467] [I] [dash] [Bitcoin Job Manager] All daemons online 
[2017-11-20 03:53:11.9593] [E] [dash] System.NullReferenceException: Object reference not set to an instance of an object.
   at MiningCore.Blockchain.Bitcoin.BitcoinJobManager`2.<AreDaemonsConnected>d__44.MoveNext() in /home/cryptocentralized/miningcore/src/MiningCore/Blockchain/Bitcoin/BitcoinJobManager.cs:line 386

**Comment by pfeiflelukas** [comment]
Managed to solve the issue by replacing the pools address for each coin.
