### ISSUE TITLE
Docker image have issues loading libmultihash 

### ISSUE THREAD

**Issue by kabilanvk** [coinfoundry/miningcore#838]
### Description
Built the code as a docker image using .net5 failed to load libmultihash at runtime.

### Steps to Reproduce
Launching Miningcore.dll from docker image fails to load libmultihash.

### Expected behavior
Should launch pool without any errors 

### Actual behavior
Fails with error as in description.

```console
[2021-06-15 01:18:19.7255] [E] [eth1] System.DllNotFoundException: Unable to load shared library 'libmultihash' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibmultihash: cannot open shared object file: No such file or directory   at Miningcore.Native.LibMultihash.ethash_get_default_dirname(Byte* data, Int32 length)
   at Miningcore.Crypto.Hashing.Ethash.Dag.GetDefaultDagDirectory() in /src/src/Miningcore/Crypto/Hashing/Ethash/Dag.cs:line 34
   at Miningcore.Blockchain.Ethereum.EthereumJobManager.Configure(PoolConfig poolConfig, ClusterConfig clusterConfig) in /src/src/Miningcore/Blockchain/Ethereum/EthereumJobManager.cs:line 425
   at Miningcore.Blockchain.Ethereum.EthereumPool.SetupJobManager(CancellationToken ct) in /src/src/Miningcore/Blockchain/Ethereum/EthereumPool.cs:line 369   at Miningcore.Mining.PoolBase.StartAsync(CancellationToken ct) in /src/src/Miningcore/Mining/PoolBase.cs:line 351 System.DllNotFoundException: Unable to load shared library 'libmultihash' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibmultihash: cannot open shared object file: No such file or directory
   at Miningcore.Native.LibMultihash.ethash_get_default_dirname(Byte* data, Int32 length)
   at Miningcore.Crypto.Hashing.Ethash.Dag.GetDefaultDagDirectory() in /src/src/Miningcore/Crypto/Hashing/Ethash/Dag.cs:line 34
   at Miningcore.Blockchain.Ethereum.EthereumJobManager.Configure(PoolConfig poolConfig, ClusterConfig clusterConfig) in /src/src/Miningcore/Blockchain/Ethereum/EthereumJobManager.cs:line 425
   at Miningcore.Blockchain.Ethereum.EthereumPool.SetupJobManager(CancellationToken ct) in /src/src/Miningcore/Blockchain/Ethereum/EthereumPool.cs:line 369   at Miningcore.Mining.PoolBase.StartAsync(CancellationToken ct) in /src/src/Miningcore/Mining/PoolBase.cs:line 351    at Miningcore.Native.LibMultihash.ethash_get_default_dirname(Byte* data, Int32 length)
   at Miningcore.Crypto.Hashing.Ethash.Dag.GetDefaultDagDirectory() in /src/src/Miningcore/Crypto/Hashing/Ethash/Dag.cs:line 34
   at Miningcore.Blockchain.Ethereum.EthereumJobManager.Configure(PoolConfig poolConfig, ClusterConfig clusterConfig) in /src/src/Miningcore/Blockchain/Ethereum/EthereumJobManager.cs:line 425
   at Miningcore.Blockchain.Ethereum.EthereumPool.SetupJobManager(CancellationToken ct) in /src/src/Miningcore/Blockchain/Ethereum/EthereumPool.cs:line 369   at Miningcore.Mining.PoolBase.StartAsync(CancellationToken ct) in /src/src/Miningcore/Mining/PoolBase.cs:line 351
```

### Reproduces how often
Everytime

### Version
Latest version 

### Additional Information
Dockerfile

```dockerfile
FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["src/Miningcore/Miningcore.csproj", "src/Miningcore/"]
RUN dotnet restore "src/Miningcore/Miningcore.csproj"
RUN apt-get update -y && \
    apt-get install -y --no-install-recommends apt-transport-https cmake build-essential libssl-dev pkg-config libboost-all-dev libsodium-dev libzmq5
COPY . .
WORKDIR "/src/src/Miningcore"
RUN dotnet build "Miningcore.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Miningcore.csproj" -c Release --framework net5.0 -o /app/publish
COPY ["src/Miningcore/config.json", "/app/publish/"]

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Miningcore.dll", "-c", "config.json"]
```

**Comment by oliverw** [comment]
That because neither the docker image nor Ethereum have been maintained for a long time. The latter is already gone from the latest release and I think the docker image should be scrapped too.

**Comment by oliverw** [comment]
Tracked in #844
