### ISSUE TITLE
Miningcore Fails to start, throws Autofac.Core.DependencyResolutionException:

### ISSUE THREAD

**Issue by MrChzl** [coinfoundry/miningcore#883]
### Description
Regardless of building from source or downloading binaries, on a fresh Ubuntu 20.04 install I keep encountering:

 Autofac.Core.DependencyResolutionException: An exception was thrown while activating λ:Microsoft.Extensions.Hosting.IHostedService[] -> Microsoft.AspNetCore.Hosting.GenericWebHostService -> Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.

### Steps to Reproduce

1. Provision Ubuntu 
2. Build Miningcore from source following steps in README
3. create config file
4. launch miningcore with ./Miningcore -c config.json

### Expected behavior

Launch Miningcore Backend

### Actual behavior

[2021-06-27 15:33:28.2982] [I] [Core] .NET 5.0.7 on Linux 5.4.0-77-generic #86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021 [X64]
[2021-06-27 15:33:28.3966] [I] [Core] Prometheus Metrics 127.0.0.1:4000/metrics
[2021-06-27 15:33:28.3966] [I] [Core] WebSocket notifications streaming 127.0.0.1:4000/notifications
[2021-06-27 15:33:29.0711] [I] [XmlKeyManager] User profile is available. Using '/home/$USER/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
Autofac.Core.DependencyResolutionException: An exception was thrown while activating λ:Microsoft.Extensions.Hosting.IHostedService[] -> Microsoft.AspNetCore.Hosting.GenericWebHostService -> Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.
 ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Microsoft.Extensions.Options.IOptions`1[Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerOptions], System.Collections.Generic.IEnumerable`1[Microsoft.AspNetCore.Connections.IConnectionListenerFactory], System.Collections.Generic.IEnumerable`1[Microsoft.AspNetCore.Connections.Experimental.IMultiplexedConnectionListenerFactory], Microsoft.Extensions.Logging.ILoggerFactory)' on type 'KestrelServerImpl'.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Miningcore.Program.<>c.<Main>b__0_10(ListenOptions listenOptions) in /home/$USER/miningcorev54/src/Miningcore/Program.cs:line 182
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerOptions.Listen(EndPoint endPoint, Action`1 configure)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerOptions.Listen(IPAddress address, Int32 port, Action`1 configure)
   at Miningcore.Program.<>c__DisplayClass0_0.<Main>b__4(KestrelServerOptions options) in /home/$USER/miningcorev54/src/Miningcore/Program.cs:line 180
   at Microsoft.Extensions.Options.ConfigureNamedOptions`1.Configure(String name, TOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.OptionsManager`1.<>c__DisplayClass5_0.<Get>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd(String name, Func`1 createOptions)
   at Microsoft.Extensions.Options.OptionsManager`1.Get(String name)
   at Microsoft.Extensions.Options.OptionsManager`1.get_Value()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.CreateServiceContext(IOptions`1 options, ILoggerFactory loggerFactory)
   at lambda_method220(Closure , Object[] )
   at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()
   --- End of inner exception stack trace ---
   at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Reflection.ReflectionActivator.<ConfigurePipeline>b__11_0(ResolveRequestContext ctxt, Action`1 next)
   at Autofac.Core.Resolving.Middleware.DelegateMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.DisposalTrackingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Pipeline.ResolvePipeline.Invoke(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.RegistrationPipelineInvokeMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.SharingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.CircularDependencyDetectorMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Pipeline.ResolvePipeline.Invoke(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.ExecuteOperation(ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.Execute(ResolveRequest request)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(ResolveRequest request)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveOptionalService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.ResolveOptional(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.ResolveOptional(IComponentContext context, Type serviceType)
   at Autofac.Extensions.DependencyInjection.AutofacServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Miningcore.Program.Main(String[] args) in /home/$user/miningcorev54/src/Miningcore/Program.cs:line 214
Cluster cannot start. Good Bye!

### Reproduces how often

100% Unless it's something I failed to cover in steps to build from source

### Version

V54, V55 and Master

### Additional Information

Thought it could have been incompatibilities with Ubuntu, so I provisioned a Windows Server 2019 machine and encountered the same exact error.

**Comment by Konstantin35** [comment]
Maybe you should run it like this `Miningcore.dll -c config. json`

**Comment by oliverw** [comment]
Its your config. Please post a redacted version of your config.

**Comment by seperatis** [comment]
As Oliver said, it's your config. You probably need to enable and add the API snippet. 

If that doesn't work, post your config with passwords etc removed.

**Comment by oliverw** [comment]
@MrChzl add this to your configuration file:

```
    "api": {
        "port": 4000
    },

```
