### ISSUE TITLE
Miner Stats not set

### ISSUE THREAD

**Issue by Kukks** [coinfoundry/miningcore#97]
Started getting this exception after I pulled latest( into my straks branch)

```
[2017-11-27 09:35:58.5260] [E] [straks1] [Pool] [0HL9LE6IP1OK9] Error processing request mining.submit [4] System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.) ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at MiningCore.Blockchain.Bitcoin.BitcoinPoolBase`2.<OnSubmitAsync>d__5.MoveNext() in D:\Projects\miningcore\src\MiningCore\Blockchain\Bitcoin\BitcoinPoolBase.cs:line 170
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Bitcoin.BitcoinPoolBase`2.<OnRequestAsync>d__11.MoveNext() in D:\Projects\miningcore\src\MiningCore\Blockchain\Bitcoin\BitcoinPoolBase.cs:line 303
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at MiningCore.Stratum.StratumServer`1.<>c__DisplayClass13_1.<OnClientConnected>b__4() in D:\Projects\miningcore\src\MiningCore\Stratum\StratumServer.cs:line 175
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at MiningCore.Blockchain.Bitcoin.BitcoinPoolBase`2.<OnSubmitAsync>d__5.MoveNext() in D:\Projects\miningcore\src\MiningCore\Blockchain\Bitcoin\BitcoinPoolBase.cs:line 170
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Bitcoin.BitcoinPoolBase`2.<OnRequestAsync>d__11.MoveNext() in D:\Projects\miningcore\src\MiningCore\Blockchain\Bitcoin\BitcoinPoolBase.cs:line 303<---
    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at MiningCore.Stratum.StratumServer`1.<>c__DisplayClass13_1.<OnClientConnected>b__4() in D:\Projects\miningcore\src\MiningCore\Stratum\StratumServer.cs:line 175
[2017-11-27 09:36:09.7412] [I] [straks1] [Bitcoin Job Manager] Submitting block 87646 [e63ae3e65997687ef8e2844da686af08820a48414b9ada68758eafab983493dd]
[2017-11-27 09:36:09.7412] [I] [straks1] [Bitcoin Job Manager] New block 87647 detected
[2017-11-27 09:36:09.7412] [W] [straks1] [Bitcoin Job Manager] Block 87646 submission failed with: inconclusive
[2017-11-27 09:36:09.7491] [I] [straks1] [Pool] [0HL9LE6IP1OK9] Share accepted: D=0.5
[2017-11-27 09:36:10.9504] [E] [straks1] [Pool] [0HL9LE6IP1OK9] Error processing request mining.submit [4] System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.) ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at MiningCore.Blockchain.Bitcoin.BitcoinPoolBase`2.<OnSubmitAsync>d__5.MoveNext() in D:\Projects\miningcore\src\MiningCore\Blockchain\Bitcoin\BitcoinPoolBase.cs:line 170
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Bitcoin.BitcoinPoolBase`2.<OnRequestAsync>d__11.MoveNext() in D:\Projects\miningcore\src\MiningCore\Blockchain\Bitcoin\BitcoinPoolBase.cs:line 303
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at MiningCore.Stratum.StratumServer`1.<>c__DisplayClass13_1.<OnClientConnected>b__4() in D:\Projects\miningcore\src\MiningCore\Stratum\StratumServer.cs:line 175
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at MiningCore.Blockchain.Bitcoin.BitcoinPoolBase`2.<OnSubmitAsync>d__5.MoveNext() in D:\Projects\miningcore\src\MiningCore\Blockchain\Bitcoin\BitcoinPoolBase.cs:line 170
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Bitcoin.BitcoinPoolBase`2.<OnRequestAsync>d__11.MoveNext() in D:\Projects\miningcore\src\MiningCore\Blockchain\Bitcoin\BitcoinPoolBase.cs:line 303<---
    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at MiningCore.Stratum.StratumServer`1.<>c__DisplayClass13_1.<OnClientConnected>b__4() in D:\Projects\miningcore\src\MiningCore\Stratum\StratumServer.cs:line 175
```

**Comment by oliverw** [comment]
Fixed in latest commit. Sorry for the confusion.
