### ISSUE TITLE
Crash on start of latest build.

### ISSUE THREAD

**Issue by Serpent6877** [coinfoundry/miningcore#99]
[2017-11-27 10:11:09.6201] [I] [etc1] [Pool] Launching ... 
[2017-11-27 10:11:09.6563] [I] [etc1] [Ethereum Job Manager] Launching ... 
[2017-11-27 10:11:09.8307] [I] [etc1] [Ethereum Job Manager] All daemons online 
[2017-11-27 10:11:09.8521] [I] [etc1] [Ethereum Job Manager] All daemons synched with blockchain 
[2017-11-27 10:11:10.0236] [I] [Dag] Generating DAG for epoch 164 
[2017-11-27 10:11:10.0236] [I] [Dag] Generating DAG for epoch 163 
[2017-11-27 10:11:13.1789] [I] [Dag] Done generating DAG for epoch 163 after 00:00:03.1548797 
[2017-11-27 10:11:13.2048] [I] [etc1] [Ethereum Job Manager] Online 
[2017-11-27 10:11:13.2494] [E] [etc1] System.InvalidOperationException: Sequence contains no elements.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Ethereum.EthereumPool.<SetupJobManager>d__8.MoveNext() in /opt/devpool/miningcore/src/MiningCore/Blockchain/Ethereum/EthereumPool.cs:line 259
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Mining.PoolBase`1.<StartAsync>d__41.MoveNext() in /opt/devpool/miningcore/src/MiningCore/Mining/PoolBase.cs:line 403 System.InvalidOperationException: Sequence contains no elements.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Ethereum.EthereumPool.<SetupJobManager>d__8.MoveNext() in /opt/devpool/miningcore/src/MiningCore/Blockchain/Ethereum/EthereumPool.cs:line 259
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Mining.PoolBase`1.<StartAsync>d__41.MoveNext() in /opt/devpool/miningcore/src/MiningCore/Mining/PoolBase.cs:line 403    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Ethereum.EthereumPool.<SetupJobManager>d__8.MoveNext() in /opt/devpool/miningcore/src/MiningCore/Blockchain/Ethereum/EthereumPool.cs:line 259
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Mining.PoolBase`1.<StartAsync>d__41.MoveNext() in /opt/devpool/miningcore/src/MiningCore/Mining/PoolBase.cs:line 403
System.AggregateException: One or more errors occurred. (Sequence contains no elements.) ---> System.InvalidOperationException: Sequence contains no elements.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Ethereum.EthereumPool.<SetupJobManager>d__8.MoveNext() in /opt/devpool/miningcore/src/MiningCore/Blockchain/Ethereum/EthereumPool.cs:line 259
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Mining.PoolBase`1.<StartAsync>d__41.MoveNext() in /opt/devpool/miningcore/src/MiningCore/Mining/PoolBase.cs:line 424
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Program.<>c.<<Start>b__26_1>d.MoveNext() in /opt/devpool/miningcore/src/MiningCore/Program.cs:line 527
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Program.<Start>d__26.MoveNext() in /opt/devpool/miningcore/src/MiningCore/Program.cs:line 531
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at MiningCore.Program.Main(String[] args) in /opt/devpool/miningcore/src/MiningCore/Program.cs:line 82
---> (Inner Exception #0) System.InvalidOperationException: Sequence contains no elements.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Ethereum.EthereumPool.<SetupJobManager>d__8.MoveNext() in /opt/devpool/miningcore/src/MiningCore/Blockchain/Ethereum/EthereumPool.cs:line 259
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Mining.PoolBase`1.<StartAsync>d__41.MoveNext() in /opt/devpool/miningcore/src/MiningCore/Mining/PoolBase.cs:line 424
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Program.<>c.<<Start>b__26_1>d.MoveNext() in /opt/devpool/miningcore/src/MiningCore/Program.cs:line 527
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Program.<Start>d__26.MoveNext() in /opt/devpool/miningcore/src/MiningCore/Program.cs:line 531<---

Cluster cannot start. Good Bye!

**Comment by oliverw** [comment]
Could you post your config?

**Comment by Serpent6877** [comment]
{
    "logging": {
        "level": "info",
        "enableConsoleLog": true,
        "enableConsoleColors": false,
        "logFile": "pool.log",
        "logBaseDirectory": "/opt/devpool/logs",
        "perPoolLogFile": false
    },
    "banning": {
        "manager": "integrated"
    },
    "notifications": {
        "enabled": false,
        "email": {
            "host": "smtp.example.com",
            "port": 587,
            "user": "user",
            "password": "password",
            "fromAddress": "info@yourpool.org",
            "fromName": "support"
        },
        "admin": {
            "enabled": false,
            "emailAddress": "user@example.com",
            "notifyBlockFound": true
        }
    },
    "persistence": {
        "postgres": {
            "host": "127.0.0.1",
            "port": 5432,
            "user": "miningcore",
            "password": "xxxxxxxxx",
            "database": "miningcore"
        }
    },
    "devDonation": 0.0,
    "paymentProcessing": {
        "enabled": true,
        "interval": 600,
        "shareRecoveryFile": "recovered-shares.txt"
    },
    // Api Settings
    "api": {
        "enabled": true,
        "listenAddress": "127.0.0.1", // Binding address for API, Default: 127.0.0.1
        "port": 4000 // Binding port for API, Default: 4000
    },
    "pools": [{
      "id": "etc1",
      "enabled": true,
      "coin": {
        "type": "ETC"
      },
      "address": "0x3ff93f45e06a0dd7d8acb7d6f5ef2b5d7bfe4ab7",
      "rewardRecipients": [
        {
          "type": "op",
          "address": "0x3ff93f45e06a0dd7d8acb7d6f5ef2b5d7bfe4ab7",
          "percentage": 0
        }
      ],
      "blockRefreshInterval": 120,
      "jobRebroadcastTimeout": 55,
      "clientConnectionTimeout": 600,
      "banning": {
        "enabled": true,
        "time": 600,
        "invalidPercent": 50,
        "checkThreshold": 50
      },
      "ports": {
        "3333": {
          "listenAddress": "0.0.0.0",
          "difficulty": 0.1,
          "name": "GPU Mining",
          "varDiff": {
            "minDiff": 0.1,
            "maxDiff": null,
            "targetTime": 15,
            "retargetTime": 90,
            "variancePercent": 30,
            "maxDelta": 0.2
          }
        },
        "3334": {
          "listenAddress": "0.0.0.0",
          "difficulty": 1.0,
          "name": "High-End Multi GPU Mining",
          "varDiff": {
            "minDiff": 0.5,
            "maxDiff": null,
            "targetTime": 15,
            "retargetTime": 90,
            "variancePercent": 30,
            "maxDelta": 0.5
          }
        }
      },
      "daemons": [
        {
          "host": "127.0.0.1",
          "port": 8548,
          "user": "root"
       }
      ],
      "paymentProcessing": {
        "enabled": true,
        "minimumPayment": 0.5,
        "payoutScheme": "PPLNS",
        "payoutSchemeConfig": {
          "factor": 1.0
        },
        "coinbasePassword": "xxxxxxxxxx",
        "keepUncles": false, 
        "keepTransactionFees": false
      }
    }]
}
