### ISSUE TITLE
Error starting in ubuntu 20.04

### ISSUE THREAD

**Issue by edcomrocha** [coinfoundry/miningcore#995]
Hello !!

I've been trying for a few days without success to run Miningcore.
I already have the eth network node running.
Postgres ok and online with all configured database.

however when I run dotnet Miningcore.dll -c config.json I get the following message:

Using configuration file config.json

[2021-11-21 15:01:53.8218] [I] [Core] Version 61.0.0.0-master [9f183a14359e0246a40416f7efea7a82a2b7851d]
[2021-11-21 15:01:53.8713] [I] [Core] Runtime .NET 6.0.0-rtm.21522.10 on Linux 5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021 [X64]
[2021-11-21 15:01:53.8897] [I] [Core] Prometheus Metrics 0.0.0.0:4000/metrics
[2021-11-21 15:01:53.8897] [I] [Core] WebSocket notifications streaming 0.0.0.0:4000/notifications
System.NullReferenceException: Object reference not set to an instance of an object.
   at Miningcore.Program.<>c.<ConfigurePostgres>b__29_0(Type t) in /home/edvaldo/miningcore/src/Miningcore/Program.cs:line 746
   at Autofac.Features.Scanning.ScanningRegistrationExtensions.<>c__DisplayClass4_1`2.<CanBeRegistered>b__1(Func`2 p)
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
   at Autofac.Features.Scanning.ScanningRegistrationExtensions.<>c__DisplayClass4_0`2.<CanBeRegistered>b__0(Type t)
   at System.Linq.Utilities.<>c__DisplayClass1_0`1.<CombinePredicates>b__0(TSource x)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Autofac.Features.Scanning.ScanningRegistrationExtensions.ScanTypesTemplate[TActivatorData,TScanStyle,TRegistrationBuilderStyle](IEnumerable`1 types, IComponentRegistryBuilder cr, IRegistrationBuilder`3 rb, Func`2 scannedConstructorFunc, Action`2 register)
   at Autofac.Features.Scanning.ScanningRegistrationExtensions.ScanTypes(IEnumerable`1 types, IComponentRegistryBuilder cr, IRegistrationBuilder`3 rb)
   at Autofac.Features.Scanning.ScanningRegistrationExtensions.ScanAssemblies(IEnumerable`1 assemblies, IComponentRegistryBuilder cr, IRegistrationBuilder`3 rb)
   at Autofac.Features.Scanning.ScanningRegistrationExtensions.<>c__DisplayClass11_0.<RegisterAssemblyTypes>b__0(IComponentRegistryBuilder cr)
   at Autofac.ContainerBuilder.Build(IComponentRegistryBuilder componentRegistry, Boolean excludeDefaultModules)
   at Autofac.ContainerBuilder.Build(ContainerBuildOptions options)
   at Autofac.Extensions.DependencyInjection.AutofacServiceProviderFactory.CreateServiceProvider(ContainerBuilder containerBuilder)
   at Microsoft.Extensions.Hosting.Internal.ServiceFactoryAdapter`1.CreateServiceProvider(Object containerBuilder)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Miningcore.Program.Main(String[] args) in /home/edvaldo/miningcore/src/Miningcore/Program.cs:line 203
Cluster cannot start. Good Bye!

I can't see what I've missed.
If you can tell me where I can look, I would be very grateful.

Thanks

Hugs.

**Comment by oliverw** [comment]
Could you post your (redacted) `config.json`?

**Comment by edcomrocha** [comment]
Thanks for the quick response

Here's my https://gist.github.com/edcomrocha/47ca24a6fa19d0bf1a1e6f7dc7413cb2#file-config-json

**Comment by synergy-promotions** [comment]
Hello folks, I am also getting this error and would greatly appreciate some pointers.
I can dt the database and can see the table schema, grants etc look fine. Config has the right credentials and host, port.

**Comment by oliverw** [comment]
Please use the latest `master` branch which fixes the problem.
